defIO({
  Abfahrt: 'Abfahrt der Kabine (TRUE = Kabine fährt ab)',
  Ampel_Gelb: 'Gelbe Signallampe (TRUE = leuchtet)',
  Ampel_Gruen: 'Grüne Signallampe (TRUE = leuchtet)',
  Ampel_Rot: 'Rote Signallampe (TRUE = leuchtet)',
  Ankunft: 'Kabine ist in der Station angekommen (TRUE = angekommen)',
  Anlauf: 'Merker Anlaufwarnung (TRUE = Vorwarnung vor der Fahrt läuft)',
  Antrieb: 'Antriebsmotor (TRUE = Antrieb läuft)',
  Anzeige: 'Zahlenanzeige am Leitstand (Wert je nach Aufgabe)',
  Auto: 'Betriebsart (TRUE = Automatik, FALSE = Hand)',
  Beleuchtung: 'Beleuchtung im Wartebereich (TRUE = an)',
  Berg_1000: 'Meldung: 1000 Bergfahrten erreicht',
  Blink: 'Hilfsmerker Blinkzustand, wechselt bei jedem Impuls',
  Bremse: 'Meldung Bremse eingefallen (TRUE = Bremse zu)',
  Drehkreuz: 'Drehkreuz am Einstieg (TRUE = ein Gast geht durch)',
  Fahrt: 'Fahrtfreigabe des Bedieners (TRUE = Fahrt erlaubt)',
  Freigabe: 'Grüne Fahrfreigabe (TRUE = Fahrt freigegeben)',
  Hupe: 'Signalhupe der Station (TRUE = ertönt)',
  Impuls: 'Hilfsmerker Taktimpuls, einen Zyklus lang',
  Kabine_da: 'Kabine ist in der Station eingefahren (TRUE = da)',
  Kabine_voll: 'Meldung Kabine voll (TRUE = Zähler hat die Kapazität erreicht)',
  Kabinen_Nr: 'Nummer der eingefahrenen Kabine',
  Kabinengaeste: 'Anzahl Gäste in der abfahrenden Kabine',
  Karte_OK: 'Skipass am Leser gültig (TRUE = gültig)',
  Kette_Fehler: 'Gespeicherte Unterbrechung der Sicherheitskette',
  Kette_OK: 'Sicherheitskette in Ordnung (TRUE = geschlossen)',
  Not_Halt_OK: 'Not-Halt-Kreis in Ordnung (TRUE = Not-Halt frei)',
  Person_da: 'Person im Wartebereich (TRUE = jemand wartet)',
  Quittieren: 'Taster Quittieren (TRUE = gedrückt)',
  Revision: 'Revisionskontakt (TRUE = Revision aktiv)',
  Richtung_Berg: 'Fahrtrichtung (TRUE = bergwärts, FALSE = talwärts)',
  S_Abfahrt: 'Taster Abfahrt (TRUE = gedrückt)',
  S_Langsam: 'Taster langsame Fahrt (TRUE = gedrückt)',
  S_Schnell: 'Taster schnelle Fahrt (TRUE = gedrückt)',
  S_Start: 'Taster Start (TRUE = gedrückt)',
  S_Stopp: 'Taster Stopp (TRUE = gedrückt)',
  S_Tippen: 'Tipptaster Handbetrieb (TRUE = gedrückt)',
  S_Tuer_Auf: 'Taster Tür auf (TRUE = gedrückt)',
  S_Weiter: 'Taster Weiter zur Fahrt (TRUE = gedrückt)',
  Schritt_Einsteigen: 'Schrittmerker Einsteigen (TRUE = Schritt aktiv)',
  Schritt_Fahrt: 'Schrittmerker Fahrt (TRUE = Schritt aktiv)',
  Schritt_Warnen: 'Schrittmerker Vorwarnung (TRUE = Schritt aktiv)',
  Seil_OK: 'Seil in der Rolle (TRUE = in Ordnung)',
  Seil_Stoerung: 'Gespeicherte Seilstörung (Seil bewegt sich nicht)',
  Seil_bewegt: 'Drehzahlwächter am Seil (TRUE = Seil bewegt sich)',
  Seil_kmh: 'Seilgeschwindigkeit in km/h (REAL)',
  Seil_ms: 'Seilgeschwindigkeit in m/s (REAL)',
  Sollwert: 'Geschwindigkeits-Sollwert an den Umrichter in m/s',
  Sperre_Auf: 'Zugangssperre am Einstieg (TRUE = offen)',
  Stoerung: 'Gespeicherte Störungsmeldung (TRUE = Störung)',
  Tagesgaeste: 'Summe der beförderten Gäste am Tag',
  Takt_1Hz: 'Taktmerker 1 Hz (wechselt jede halbe Sekunde)',
  Takt_2Hz: 'Taktmerker 2 Hz (wechselt alle 0,25 Sekunden)',
  Tal_1000: 'Meldung: 1000 Talfahrten erreicht',
  Tuer_Auf: 'Kabinentür (TRUE = Tür öffnet)',
  Tuer_Schliessen: 'Befehl Tür schliessen (TRUE = Tür soll schliessen)',
  Tuer_Zu: 'Rückmeldung Tür geschlossen (TRUE = Tür zu)',
  Warnen: 'Merker Hupwarnung vor der Abfahrt (TRUE = aktiv)',
  Warnung: 'Merker Warnung (TRUE = Warnlampe soll blinken)',
  Wartung_OK: 'Wartung erledigt (TRUE = Zähler wird neu geladen)',
  Wartung_faellig: 'Meldung Wartung fällig (TRUE = Seilprüfung nötig)',
  Wind_OK: 'Windwächter ruhig (TRUE = Wind unkritisch)',
  Wind_Stopp: 'Merker Sturmstopp (TRUE = Fahrt wegen Wind gestoppt)',
  Wind_hoch: 'Windwächter (TRUE = Wind zu stark)',
  Wind_kmh: 'Windgeschwindigkeit in km/h',
  Windwarnung: 'Windwarnung (TRUE = Wind über dem Warnwert)'
});
