defIO({
  Tuer_Zu: 'Endschalter: Türen geschlossen',
  Seil_OK: 'Seilüberwachung: Seil liegt in der Rolle',
  Not_Halt_OK: 'Not-Halt-Kreis in Ordnung (nicht gedrückt)',
  Freigabe: 'Fahrfreigabe der Station',
  Wind_kmh: 'Windgeschwindigkeit in km/h (Anemometer)',
  Wind_Stopp: 'Windstopp: Wind über der Abschaltgrenze',
  Kabine_Berg: 'Kabine steht in der Bergstation',
  S_Tuer_Berg: 'Taster Tür öffnen, Bergstation',
  Kabine_Tal: 'Kabine steht in der Talstation',
  S_Tuer_Tal: 'Taster Tür öffnen, Talstation',
  Fahrt: 'Meldung: Antrieb läuft / Fahrbefehl',
  Tuer_Berg: 'Befehl Tür öffnen, Bergstation',
  Tuer_Tal: 'Befehl Tür öffnen, Talstation',
  Seil_ms: 'Seilgeschwindigkeit in m/s (Umrichter)',
  Seil_kmh: 'Seilgeschwindigkeit in km/h (Anzeige)',
  Windwarnung: 'Warnlampe: Wind ist stark',
  Stoerung: 'Sammelstörung der Anlage',
  Ampel_Rot: 'Signalampel: rote Lampe',
  Ampel_Gruen: 'Signalampel: grüne Lampe',
  S_Start: 'Taster Start (Schliesser)',
  Antrieb: 'Ausgang Hauptantrieb (Motor)',
  S_Stopp: 'Taster Stopp',
  Kette_OK: 'Sicherheitskette geschlossen und in Ordnung',
  Seil_Fehler: 'Meldung: Seilfehler',
  Quittieren: 'Taster Störung quittieren',
  S_Licht_Ein: 'Taster Beleuchtung ein',
  S_Licht_Aus: 'Taster Beleuchtung aus',
  Beleuchtung: 'Ausgang Stationsbeleuchtung',
  Drehkreuz: 'Sensor Drehkreuz: ein Fahrgast geht durch',
  Abfahrt: 'Meldung: Kabine fährt ab',
  Fahrgaeste: 'Anzahl der Fahrgäste (Zähler)',
  Kabine_da: 'Kabine steht im Bahnsteig',
  Tuer_Auf: 'Befehl Türantrieb: Tür öffnen',
  Kabine_voll: 'Meldung: Kabine ist voll',
  Anzeige: 'Zahlenanzeige am Leitstand',
  Hupe: 'Ausgang Warnhupe',
  Ampel_Gelb: 'Signalampel: gelbe Lampe',
  Bereit: 'Meldung: Kabine abfahrbereit',
  Bereit_1: 'Kabine 1 ist abfahrbereit',
  Voll_1: 'Kabine 1 ist voll',
  Bereit_2: 'Kabine 2 ist abfahrbereit',
  Voll_2: 'Kabine 2 ist voll',
  Abfahrt_frei: 'Abfahrt beider Kabinen frei',
  S_Tuer: 'Taster Tür öffnen',
  Wind_OK: 'Windüberwachung in Ordnung (Wind unter Grenze)',
  Bremse_Auf: 'Meldung: Bremse gelüftet',
  Kette_Tal_OK: 'Sicherheitskette Talstation in Ordnung',
  Auto: 'Wahlschalter: 1 = Automatik, 0 = Hand',
  Schritt_Fahrt: 'Fahrbefehl der Schrittkette',
  S_Tippen: 'Tipptaster für Handbetrieb',
  Drehkreuz_1: 'Sensor Drehkreuz 1',
  Drehkreuz_2: 'Sensor Drehkreuz 2',
  Wind_Fehler: 'Meldung: Windstörung',
  Takt_1Hz: 'Blinktakt 1 Hz (Systemtakt)',
  Lampe_Seil: 'Meldelampe Seilstörung',
  Lampe_Wind: 'Meldelampe Windstörung',
  Bremse: 'Ausgang Haltebremse (1 = eingefallen)',
  Anzahl: 'Anzahl anstehender Meldungen',
  Sammelstoerung: 'Sammelmeldung: mindestens eine Störung ansteht',
  S_Abfahrt: 'Taster Abfahrt',
  Ankunft: 'Meldung: Kabine ist angekommen',
  Halt: 'Haltebefehl der Schrittkette'
});
