/* PLC-Variablen KOP Quest (Feedback-Auftrag Paket 5.2) – erzeugt mit node gen_tags.js kop, Kommentare von Hand gepflegt.
   Dieselbe Variable hat in allen Aufgaben dieselbe Adresse. Eingänge %I, Ausgänge %Q, Merker %M; Texte/Felder im DB "Daten"; Timer/Zähler als IEC-Instanz. */
(function(root){
root.PLC_TAGS = {
  "Abfahrt": { addr: "%Q0.0", type: "Bool", comment: "Abfahrt ausgelöst (Kabine fährt ab)" },
  "Abfahrt_frei": { addr: "%Q0.1", type: "Bool", comment: "Abfahrt beider Kabinen freigegeben" },
  "Ampel_Gelb": { addr: "%Q0.2", type: "Bool", comment: "Ampel am Bahnsteig gelb" },
  "Ampel_Gruen": { addr: "%Q0.3", type: "Bool", comment: "Ampel am Bahnsteig grün" },
  "Ampel_Rot": { addr: "%Q0.4", type: "Bool", comment: "Ampel am Bahnsteig rot" },
  "Ankunft": { addr: "%I0.0", type: "Bool", comment: "Kabine an der Station angekommen" },
  "Anlauf": { addr: "%Q0.5", type: "Bool", comment: "Anlaufwarnung läuft (vor dem Start)" },
  "Antrieb": { addr: "%Q0.6", type: "Bool", comment: "Antrieb Seilbahn ein" },
  "Antrieb_Ein": { addr: "%Q0.7", type: "Bool", comment: "Einschaltbefehl Antrieb" },
  "Anzahl": { addr: "%QW64", type: "Int", comment: "Anzahl (Zählerstand)" },
  "Anzeige": { addr: "%QW66", type: "Int", comment: "Anzeige am Pult (Zahlenwert)" },
  "Auto": { addr: "%I0.1", type: "Bool", comment: "Betriebsart Automatik gewählt" },
  "Beleuchtung": { addr: "%Q1.0", type: "Bool", comment: "Beleuchtung Station ein" },
  "Bereit": { addr: "%Q1.1", type: "Bool", comment: "Kabine abfahrbereit (Meldelampe)" },
  "Bereit_1": { addr: "%Q1.2", type: "Bool", comment: "Kabine 1 abfahrbereit" },
  "Bereit_2": { addr: "%Q1.3", type: "Bool", comment: "Kabine 2 abfahrbereit" },
  "Berg_1000": { addr: "%M10.0", type: "Bool", comment: "1000 Bergfahrten erreicht" },
  "Blink": { addr: "%M10.1", type: "Bool", comment: "Blinkmerker (wechselt im Takt)" },
  "Bremse": { addr: "%Q1.4", type: "Bool", comment: "Bremse eingefallen (TRUE = bremst)" },
  "Bremse_Auf": { addr: "%Q1.5", type: "Bool", comment: "Bremse gelüftet" },
  "Drehkreuz": { addr: "%I0.2", type: "Bool", comment: "Drehkreuz meldet Durchgang (Impuls)" },
  "Drehkreuz_1": { addr: "%I0.3", type: "Bool", comment: "Drehkreuz 1 meldet Durchgang" },
  "Drehkreuz_2": { addr: "%I0.4", type: "Bool", comment: "Drehkreuz 2 meldet Durchgang" },
  "Fahrgaeste": { addr: "%QW68", type: "Int", comment: "Fahrgäste gezählt" },
  "Fahrt": { addr: "%Q1.6", type: "Bool", comment: "Fahrbefehl Seilbahn" },
  "Fahrt_Berg": { addr: "%Q1.7", type: "Bool", comment: "Fahrt bergwärts aktiv (Selbsthaltung)" },
  "Fahrt_Tal": { addr: "%Q2.0", type: "Bool", comment: "Fahrt talwärts aktiv (Selbsthaltung)" },
  "Freigabe": { addr: "%Q2.1", type: "Bool", comment: "Freigabe Fahrt (Sicherheitskette OK)" },
  "Gewitter": { addr: "%I0.5", type: "Bool", comment: "Gewittermelder: Blitz in der Nähe" },
  "Halt": { addr: "%Q2.2", type: "Bool", comment: "Kabine halten (Stoppbefehl)" },
  "Hand": { addr: "%I0.6", type: "Bool", comment: "Betriebsart Hand gewählt" },
  "Hupe": { addr: "%Q2.3", type: "Bool", comment: "Hupe Station" },
  "Impuls": { addr: "%Q2.4", type: "Bool", comment: "Impulsmerker (ein Zyklus lang 1)" },
  "Kabine_bereit": { addr: "%I0.7", type: "Bool", comment: "Kabine startbereit" },
  "Kabine_Berg": { addr: "%Q2.5", type: "Bool", comment: "Kabine in der Bergstation" },
  "Kabine_da": { addr: "%I1.0", type: "Bool", comment: "Kabine in der Station (Lichtschranke)" },
  "Kabine_Tal": { addr: "%I1.1", type: "Bool", comment: "Kabine in der Talstation" },
  "Kabine_voll": { addr: "%Q2.6", type: "Bool", comment: "Kabine voll besetzt" },
  "Kabinen_Nr": { addr: "%QW70", type: "Int", comment: "Nummer der eingefahrenen Kabine" },
  "Kabinengaeste": { addr: "%IW64", type: "Int", comment: "Fahrgäste in der Kabine" },
  "Karte_OK": { addr: "%I1.2", type: "Bool", comment: "Skipass gültig (Kartenleser)" },
  "Kette_Fehler": { addr: "%Q2.7", type: "Bool", comment: "Sicherheitskette unterbrochen (gespeichert)" },
  "Kette_OK": { addr: "%Q3.0", type: "Bool", comment: "Sicherheitskette geschlossen" },
  "Kette_Tal_OK": { addr: "%Q3.1", type: "Bool", comment: "Sicherheitskette Talstation geschlossen" },
  "Lampe_Seil": { addr: "%Q3.2", type: "Bool", comment: "Meldelampe Seilstörung" },
  "Lampe_Wind": { addr: "%Q3.3", type: "Bool", comment: "Meldelampe Windstörung" },
  "Not_Halt_OK": { addr: "%I1.3", type: "Bool", comment: "Not-Halt-Kreis OK (Öffner, TRUE = OK)" },
  "Person_da": { addr: "%I1.4", type: "Bool", comment: "Person erkannt (Drehkreuz, Präsenzmelder)" },
  "Quittieren": { addr: "%I1.5", type: "Bool", comment: "Taster Quittieren am Pult" },
  "Revision": { addr: "%I1.6", type: "Bool", comment: "Revisionsschalter (Wartungsbetrieb)" },
  "Richtung_Berg": { addr: "%Q3.4", type: "Bool", comment: "Fahrtrichtung bergwärts (FALSE = talwärts)" },
  "S_Abfahrt": { addr: "%I1.7", type: "Bool", comment: "Taster Abfahrt am Pult (Schliesser)" },
  "S_Aus": { addr: "%I2.0", type: "Bool", comment: "Taster Aus (Schliesser)" },
  "S_Berg": { addr: "%I2.1", type: "Bool", comment: "Taster Fahrt bergwärts (Schliesser)" },
  "S_Ein": { addr: "%I2.2", type: "Bool", comment: "Taster Ein (Schliesser)" },
  "S_Einstieg": { addr: "%I2.3", type: "Bool", comment: "Taster Einstieg freigeben (Schliesser)" },
  "S_Fahrt": { addr: "%I2.4", type: "Bool", comment: "Taster Fahrt (Schliesser)" },
  "S_Hupe": { addr: "%I2.5", type: "Bool", comment: "Taster Hupe am Pult (Schliesser)" },
  "S_Hupe_Kabine": { addr: "%I2.6", type: "Bool", comment: "Taster Hupe in der Kabine (Schliesser)" },
  "S_Hupe_Pult": { addr: "%I2.7", type: "Bool", comment: "Taster Hupe am Pult (Schliesser)" },
  "S_Langsam": { addr: "%I3.0", type: "Bool", comment: "Taster langsame Fahrt (Schliesser)" },
  "S_Licht": { addr: "%I3.1", type: "Bool", comment: "Taster Licht (Schliesser)" },
  "S_Licht_Aus": { addr: "%I3.2", type: "Bool", comment: "Taster Licht aus (Schliesser)" },
  "S_Licht_Ein": { addr: "%I3.3", type: "Bool", comment: "Taster Licht ein (Schliesser)" },
  "S_Schnell": { addr: "%I3.4", type: "Bool", comment: "Taster schnelle Fahrt (Schliesser)" },
  "S_Start": { addr: "%I3.5", type: "Bool", comment: "Taster Start Antrieb (Schliesser)" },
  "S_Stopp": { addr: "%I3.6", type: "Bool", comment: "Taster Stopp (Schliesser, 1 = gedrückt)" },
  "S_Tal": { addr: "%I3.7", type: "Bool", comment: "Taster Fahrt talwärts (Schliesser)" },
  "S_Taster": { addr: "%I4.0", type: "Bool", comment: "Taster am Pult (Schliesser)" },
  "S_Tipp": { addr: "%I4.1", type: "Bool", comment: "Taster Tippbetrieb (Schliesser)" },
  "S_Tippen": { addr: "%I4.2", type: "Bool", comment: "Taster Tippbetrieb (Schliesser)" },
  "S_Tuer": { addr: "%I4.3", type: "Bool", comment: "Taster Tür öffnen (Schliesser)" },
  "S_Tuer_Auf": { addr: "%I4.4", type: "Bool", comment: "Taster Tür auf (Schliesser)" },
  "S_Tuer_Berg": { addr: "%I4.5", type: "Bool", comment: "Taster Tür Bergstation (Schliesser)" },
  "S_Tuer_Kabine": { addr: "%I4.6", type: "Bool", comment: "Taster Tür in der Kabine (Schliesser)" },
  "S_Tuer_Station": { addr: "%I4.7", type: "Bool", comment: "Taster Tür am Bahnsteig (Schliesser)" },
  "S_Tuer_Tal": { addr: "%I5.0", type: "Bool", comment: "Taster Tür Talstation (Schliesser)" },
  "S_Tuer_Zu": { addr: "%I5.1", type: "Bool", comment: "Taster Tür zu (Schliesser)" },
  "S_Weiter": { addr: "%I5.2", type: "Bool", comment: "Taster Weiter (Schliesser)" },
  "S_Zaehlen": { addr: "%I5.3", type: "Bool", comment: "Taster Zählen (Schliesser)" },
  "Sammelstoerung": { addr: "%Q3.5", type: "Bool", comment: "Sammelstörung (irgendeine Störung aktiv)" },
  "Schritt_Einsteigen": { addr: "%Q3.6", type: "Bool", comment: "Schritt Einsteigen aktiv" },
  "Schritt_Fahrt": { addr: "%M10.2", type: "Bool", comment: "Schritt Fahrt aktiv" },
  "Schritt_Warnen": { addr: "%Q3.7", type: "Bool", comment: "Schritt Vorwarnung aktiv" },
  "Seil_bewegt": { addr: "%I5.4", type: "Bool", comment: "Drehzahlwächter: Seil bewegt sich" },
  "Seil_Fehler": { addr: "%I5.5", type: "Bool", comment: "Seilüberwachung meldet Fehler" },
  "Seil_kmh": { addr: "%MD200", type: "Real", comment: "Seilgeschwindigkeit in km/h" },
  "Seil_ms": { addr: "%MD204", type: "Real", comment: "Seilgeschwindigkeit in m/s" },
  "Seil_OK": { addr: "%Q4.0", type: "Bool", comment: "Seil liegt in der Rolle" },
  "Seil_Stoerung": { addr: "%Q4.1", type: "Bool", comment: "Störung Seil blockiert (gespeichert)" },
  "Sensorfehler": { addr: "%I5.6", type: "Bool", comment: "Türschalter widersprechen sich" },
  "Sollwert": { addr: "%QW72", type: "Int", comment: "Sollgeschwindigkeit in m/s" },
  "Sperre_Auf": { addr: "%Q4.2", type: "Bool", comment: "Drehkreuzsperre öffnen" },
  "St_Seil": { addr: "%Q4.3", type: "Bool", comment: "Störung Seil gespeichert" },
  "St_Wind": { addr: "%I5.7", type: "Bool", comment: "Störung Wind gespeichert" },
  "Stoerung": { addr: "%Q4.4", type: "Bool", comment: "Störung gespeichert (Meldelampe)" },
  "Tagesgaeste": { addr: "%QW74", type: "Int", comment: "Fahrgäste heute gesamt" },
  "Takt_1Hz": { addr: "%I6.0", type: "Bool", comment: "Taktmerker 1 Hz" },
  "Takt_2Hz": { addr: "%I6.1", type: "Bool", comment: "Taktmerker 2 Hz" },
  "Tal_1000": { addr: "%M10.3", type: "Bool", comment: "1000 Talfahrten erreicht" },
  "Tuer_Auf": { addr: "%Q4.5", type: "Bool", comment: "Tür öffnen" },
  "Tuer_Berg": { addr: "%Q4.6", type: "Bool", comment: "Tür Bergstation öffnen" },
  "Tuer_Fehler": { addr: "%I6.2", type: "Bool", comment: "Türüberwachung meldet Fehler" },
  "Tuer_L": { addr: "%I6.3", type: "Bool", comment: "Endschalter linker Türflügel zu" },
  "Tuer_Offen": { addr: "%I6.4", type: "Bool", comment: "Tür offen (Endschalter)" },
  "Tuer_R": { addr: "%I6.5", type: "Bool", comment: "Endschalter rechter Türflügel zu" },
  "Tuer_Schliessen": { addr: "%I6.6", type: "Bool", comment: "Befehl Tür schliessen" },
  "Tuer_Tal": { addr: "%Q4.7", type: "Bool", comment: "Tür Talstation öffnen" },
  "Tuer_Zu": { addr: "%I6.7", type: "Bool", comment: "Tür geschlossen (Endschalter)" },
  "Voll_1": { addr: "%Q5.0", type: "Bool", comment: "Kabine 1 voll" },
  "Voll_2": { addr: "%Q5.1", type: "Bool", comment: "Kabine 2 voll" },
  "Warnen": { addr: "%Q5.2", type: "Bool", comment: "Abfahrtswarnung aktiv" },
  "Warnhupe": { addr: "%Q5.3", type: "Bool", comment: "Warnhupe" },
  "Warnung": { addr: "%Q5.4", type: "Bool", comment: "Warnung aktiv (Lampe soll blinken)" },
  "Wartung_faellig": { addr: "%Q5.5", type: "Bool", comment: "Wartung fällig (Meldelampe)" },
  "Wartung_OK": { addr: "%I7.0", type: "Bool", comment: "Quittung Wartung erledigt (Techniker)" },
  "Wind_Fehler": { addr: "%I7.1", type: "Bool", comment: "Windmesser meldet Fehler" },
  "Wind_hoch": { addr: "%Q5.6", type: "Bool", comment: "Windmesser: Wind zu stark" },
  "Wind_kmh": { addr: "%IW66", type: "Int", comment: "Windgeschwindigkeit in km/h" },
  "Wind_OK": { addr: "%Q5.7", type: "Bool", comment: "Wind im zulässigen Bereich" },
  "Wind_Stopp": { addr: "%I7.2", type: "Bool", comment: "Sturmabschaltung aktiv (gespeichert)" },
  "Windwarnung": { addr: "%Q6.0", type: "Bool", comment: "Windwarnung (Lampe am Pult)" }
};
})(typeof window !== 'undefined' ? window : globalThis);
