/* ===== KAPITEL-METADATEN: Titel, Icon, Intro-Text, Intro-Animation ===== */
(function(){
const A = (inner) => '<svg viewBox="0 0 300 160" xmlns="http://www.w3.org/2000/svg" font-family="monospace">' + inner + '</svg>';
defChapter({ n:1, title:'Erste Bewegungen', subtitle:'Zuweisung & Datentypen', icon:'fa-robot',
  intro:'ARIA, die KI der Roboterzelle RZ-03, hat die Automatik abgeschaltet. Du übernimmst Greifer, Achse und Band von Hand — mit der Grundlage aller Grundlagen: der Zuweisung <code>:=</code> und den Datentypen BOOL, INT, REAL.',
  anim: A('<rect x="60" y="14" width="180" height="10" rx="3" fill="#2a2b20"/><g><animateTransform attributeName="transform" type="rotate" values="0 150 24;35 150 24;0 150 24;-25 150 24;0 150 24" dur="5s" repeatCount="indefinite"/><rect x="146" y="24" width="8" height="80" rx="3" fill="#e07f00"/><rect x="138" y="104" width="24" height="7" rx="2" fill="#9a9a9a"/><rect x="136" y="110" width="6" height="16" rx="2" fill="#d5d5d5"/><rect x="158" y="110" width="6" height="16" rx="2" fill="#d5d5d5"/></g><circle cx="150" cy="24" r="7" fill="#33352a" stroke="#39ff14" stroke-width="2"/><rect x="40" y="136" width="220" height="10" rx="3" fill="#1c1d12"/><text x="150" y="156" text-anchor="middle" font-size="9" fill="#39ff14">Achse_Grad := 35;<animate attributeName="opacity" values="0.3;1;0.3" dur="2.5s" repeatCount="indefinite"/></text>') });
defChapter({ n:2, title:'Sicherheitslogik', subtitle:'AND · OR · NOT · XOR', icon:'fa-shield-halved',
  intro:'Schutzzaun, Lichtschranken, Not-Halt: Einzelne Signale reichen nicht — sie müssen logisch korrekt verknüpft werden. ARIA sucht jede Lücke in deiner Logik. Lerne AND, OR, NOT, XOR, Klammern und die Selbsthaltung.',
  anim: A('<circle cx="120" cy="76" r="42" fill="none" stroke="#ff3333" stroke-width="3" opacity=".6"><animate attributeName="opacity" values=".4;.9;.4" dur="2.2s" repeatCount="indefinite"/></circle><circle cx="180" cy="76" r="42" fill="none" stroke="#1ec8e0" stroke-width="3" opacity=".6"><animate attributeName="opacity" values=".9;.4;.9" dur="2.2s" repeatCount="indefinite"/></circle><text x="150" y="83" text-anchor="middle" font-size="22" font-weight="700" fill="#39ff14">AND</text><text x="150" y="146" text-anchor="middle" font-size="9" fill="#8a8a8a">Freigabe := A AND NOT Stopp;</text>') });
defChapter({ n:3, title:'Messwerte', subtitle:'Vergleiche · Arithmetik · Funktionen', icon:'fa-gauge-high',
  intro:'Temperatur, Gewicht, Füllstand: Die Zelle misst ständig. Du vergleichst Messwerte mit Grenzen, rechnest mit INT und REAL, skalierst Analogwerte und begrenzt Sollwerte — und lernst die berüchtigte INT-Divisionsfalle kennen.',
  anim: A('<path d="M70 120 A80 80 0 0 1 230 120" fill="none" stroke="#2a2b20" stroke-width="12"/><path d="M70 120 A80 80 0 0 1 230 120" fill="none" stroke="#ff8c00" stroke-width="12" stroke-dasharray="251" stroke-dashoffset="251"><animate attributeName="stroke-dashoffset" values="251;60;120;40;251" dur="5s" repeatCount="indefinite"/></path><line x1="150" y1="120" x2="150" y2="56" stroke="#39ff14" stroke-width="3" stroke-linecap="round"><animateTransform attributeName="transform" type="rotate" values="-90 150 120;40 150 120;-10 150 120;60 150 120;-90 150 120" dur="5s" repeatCount="indefinite"/></line><circle cx="150" cy="120" r="6" fill="#39ff14"/><text x="150" y="150" text-anchor="middle" font-size="9" fill="#1ec8e0">Alarm := Temperatur &gt; 80;</text>') });
defChapter({ n:4, title:'Entscheidungen', subtitle:'IF · ELSIF · ELSE', icon:'fa-code-branch',
  intro:'Die Zelle muss entscheiden: greifen oder warten? Welche Lampe? Welche Priorität? Mit <code>IF/ELSIF/ELSE</code> gibst du ihr ein Gehirn — und lernst, warum Reihenfolge, Hysterese und Sicherheitspriorität über alles entscheiden.',
  anim: A('<rect x="110" y="16" width="80" height="26" rx="4" fill="#14150c" stroke="#1ec8e0"/><text x="150" y="33" text-anchor="middle" font-size="10" fill="#1ec8e0">IF Teil?</text><path d="M150 42 L90 90 M150 42 L210 90" stroke="#3c3c3c" stroke-width="2"/><rect x="50" y="90" width="80" height="26" rx="4" fill="#14150c" stroke="#39ff14"><animate attributeName="stroke-width" values="1;3;1" dur="2s" repeatCount="indefinite"/></rect><text x="90" y="107" text-anchor="middle" font-size="9" fill="#39ff14">greifen</text><rect x="170" y="90" width="80" height="26" rx="4" fill="#14150c" stroke="#ff8c00"><animate attributeName="stroke-width" values="3;1;3" dur="2s" repeatCount="indefinite"/></rect><text x="210" y="107" text-anchor="middle" font-size="9" fill="#ff8c00">warten</text><text x="118" y="70" font-size="8" fill="#39ff14">THEN</text><text x="170" y="70" font-size="8" fill="#ff8c00">ELSE</text>') });
defChapter({ n:5, title:'Betriebsarten', subtitle:'CASE', icon:'fa-diagram-project',
  intro:'Aus, Hand, Automatik, Wartung: Jede Betriebsart steuert die Zelle anders. ARIA versucht, sich in genau diese Verzweigungen einzuschleichen. Mit <code>CASE … OF</code> baust du übersichtliche Auswahltabellen — mit Listen, Bereichen und einem sicheren ELSE.',
  anim: A('<rect x="20" y="72" width="120" height="14" fill="#1c1d12" stroke="#3a3c2c"/><rect x="36" y="58" width="16" height="14" rx="2" fill="#9a9a9a"><animateTransform attributeName="transform" type="translate" values="0 0;90 0;90 0;0 0" dur="3s" repeatCount="indefinite"/></rect><g transform="translate(150,79)"><rect x="0" y="-3" width="40" height="6" rx="3" fill="#1ec8e0"><animateTransform attributeName="transform" type="rotate" values="0;-22;-22;22;22;0" dur="3s" repeatCount="indefinite"/></rect></g><rect x="200" y="36" width="80" height="12" fill="#15160f" stroke="#39ff14"/><rect x="200" y="112" width="80" height="12" fill="#15160f" stroke="#ff3333"/><text x="240" y="45" text-anchor="middle" font-size="8" fill="#39ff14">1: GUT</text><text x="240" y="121" text-anchor="middle" font-size="8" fill="#ff3333">2: AUSSCHUSS</text>') });
defChapter({ n:6, title:'Teile-Analyse', subtitle:'Arrays · FOR', icon:'fa-table-cells',
  intro:'Eine Charge hat dutzende Teile — einzelne Variablen reichen nicht mehr. <code>ARRAY</code> speichert viele Werte unter einem Namen, <code>FOR</code> durchläuft sie systematisch. Zählen, summieren, Maximum finden, verschieben: ARIA fälscht die Qualitätsberichte, du deckst es auf.',
  anim: A('<g transform="translate(46,48)">' + Array.from({length:10}).map((_,i)=>'<rect x="'+(i*21)+'" y="0" width="17" height="30" rx="3" fill="#1c1d12" stroke="#3a3c2c"><animate attributeName="fill" values="#1c1d12;#39ff14;#1c1d12" dur="2.5s" begin="'+(i*0.22).toFixed(2)+'s" repeatCount="indefinite"/></rect><text x="'+(i*21+8.5)+'" y="46" text-anchor="middle" font-size="8" fill="#5a5a5a">'+i+'</text>').join('') + '</g><text x="150" y="130" text-anchor="middle" font-size="10" fill="#1ec8e0">FOR i := 0 TO 9 DO</text>') });
defChapter({ n:7, title:'Schleifen-Labyrinth', subtitle:'WHILE · REPEAT · EXIT · CONTINUE', icon:'fa-rotate',
  intro:'Nicht jede Schleife hat eine feste Länge. Suchen, bis etwas gefunden ist. Wiederholen, bis ein Ziel erreicht ist. Aber Vorsicht: ARIA liebt Endlosschleifen — sie bringen jede SPS in den STOP.',
  anim: A('<circle cx="150" cy="76" r="44" fill="none" stroke="#2a2b20" stroke-width="6"/><circle cx="150" cy="76" r="44" fill="none" stroke="#1ec8e0" stroke-width="6" stroke-dasharray="60 217"><animateTransform attributeName="transform" type="rotate" from="0 150 76" to="360 150 76" dur="2s" repeatCount="indefinite"/></circle><text x="150" y="81" text-anchor="middle" font-size="12" fill="#39ff14">WHILE</text><text x="150" y="146" text-anchor="middle" font-size="9" fill="#ff3333">… bis EXIT<animate attributeName="opacity" values=".3;1;.3" dur="1.4s" repeatCount="indefinite"/></text>') });
defChapter({ n:8, title:'Impulse', subtitle:'R_TRIG · F_TRIG · CTU · CTD', icon:'fa-wave-square',
  intro:'Ein Taster ist gedrückt — über hunderte Zyklen. Ein Teil steht vor dem Sensor — sekundenlang. Wer richtig zählen, umschalten und quittieren will, muss <b>Zustand</b> von <b>Ereignis</b> unterscheiden. Hier lernst du Flanken und Zähler.',
  anim: A('<polyline points="30,110 80,110 80,50 190,50 190,110 270,110" fill="none" stroke="#8a8a8a" stroke-width="2"/><polyline points="30,140 80,140 80,122 92,122 92,140 270,140" fill="none" stroke="#39ff14" stroke-width="2.5"><animate attributeName="opacity" values=".3;1;.3" dur="1.2s" repeatCount="indefinite"/></polyline><text x="20" y="80" font-size="8" fill="#8a8a8a">CLK</text><text x="20" y="130" font-size="8" fill="#39ff14">Q</text><text x="150" y="30" text-anchor="middle" font-size="10" fill="#1ec8e0">R_TRIG: nur EIN Zyklus</text>') });
defChapter({ n:9, title:'Takt & Timing', subtitle:'TON · TOF · TP', icon:'fa-stopwatch',
  intro:'Nicht alles passiert sofort. Anlaufwarnungen, Nachlaufzeiten, Hupsignale, Zeitüberwachungen: Die drei IEC-Timer steuern die Zeit in jeder Maschine. ARIA hat die Einheiten vertauscht — achte auf jedes Zeichen.',
  anim: A('<circle cx="150" cy="74" r="46" fill="none" stroke="#2a2b20" stroke-width="5"/><circle cx="150" cy="74" r="46" fill="none" stroke="#ff8c00" stroke-width="5" stroke-dasharray="289" stroke-dashoffset="289"><animate attributeName="stroke-dashoffset" values="289;0" dur="3s" repeatCount="indefinite"/></circle><line x1="150" y1="74" x2="150" y2="36" stroke="#39ff14" stroke-width="3" stroke-linecap="round"><animateTransform attributeName="transform" type="rotate" from="0 150 74" to="360 150 74" dur="3s" repeatCount="indefinite"/></line><circle cx="150" cy="74" r="5" fill="#39ff14"/><text x="150" y="142" text-anchor="middle" font-size="10" fill="#1ec8e0">PT := T#3S</text>') });
defChapter({ n:10, title:'Aufstand der Maschinen', subtitle:'Schrittketten · Final Boss', icon:'fa-skull',
  intro:'Das Finale. ARIA übernimmt die gesamte Zelle. Du baust Schrittketten wie in der Industrie: Schritt für Schritt, mit Rückmeldungen, Timern und Not-Halt — und schreibst am Ende die komplette Zyklussteuerung, die ARIA endgültig entmachtet.',
  anim: A('<g font-size="10">' + [0,1,2,3].map(i=>'<circle cx="'+(60+i*60)+'" cy="70" r="18" fill="#14150c" stroke="#3a3c2c" stroke-width="2"><animate attributeName="stroke" values="#3a3c2c;#39ff14;#3a3c2c;#3a3c2c;#3a3c2c" dur="4s" begin="'+i+'s" repeatCount="indefinite"/></circle><text x="'+(60+i*60)+'" y="74" text-anchor="middle" fill="#e0e0e0">'+i+'</text>').join('') + '</g><path d="M78 70 H102 M138 70 H162 M198 70 H222" stroke="#3a3c2c" stroke-width="2"/><circle cx="40" cy="26" r="9" fill="#1a0a0a" stroke="#ff3333" stroke-width="2"><animate attributeName="opacity" values="1;.2;1" dur=".7s" repeatCount="indefinite"/></circle><text x="150" y="130" text-anchor="middle" font-size="10" fill="#ff3333">ARIA AKTIV<animate attributeName="opacity" values=".4;1;.4" dur=".9s" repeatCount="indefinite"/></text>') });

/* ---------- PROFI-STUFE ---------- */
defChapter({ n:11, pro:true, title:'Die Schnittstelle', subtitle:'Deklarationen · Datentypen · Speicherbereiche', icon:'fa-table-list',
  intro:'<b>Profi-Stufe.</b> ARIA ist besiegt — aber ein Backup hat überlebt und die Variablentabelle gelöscht. Ab jetzt schreibst du ganze Bausteine wie im TIA Portal: mit Schnittstelle, Datentypen, Startwerten und Konstanten. Und du lernst den wichtigsten Unterschied der Profis: was ein Baustein sich merkt (STAT) und was er vergisst (TEMP).',
  anim: A('<rect x="40" y="20" width="220" height="120" rx="6" fill="#14150c" stroke="#3a3c2c"/><text x="52" y="40" font-size="10" fill="#1ec8e0">VAR_INPUT</text><text x="64" y="56" font-size="10" fill="#e0e0e0">Start : Bool;</text><text x="52" y="76" font-size="10" fill="#1ec8e0">VAR</text><text x="64" y="92" font-size="10" fill="#39ff14">Zaehler : DInt := 0;<animate attributeName="opacity" values=".3;1;.3" dur="2s" repeatCount="indefinite"/></text><text x="52" y="112" font-size="10" fill="#1ec8e0">VAR_TEMP</text><text x="64" y="128" font-size="10" fill="#8a8a8a">Hilfe : Int;<animate attributeName="opacity" values="1;0;1" dur="1.2s" repeatCount="indefinite"/></text>') });
defChapter({ n:12, pro:true, title:'Werkzeuge bauen', subtitle:'Funktionen (FC) · IN / OUT / IN_OUT', icon:'fa-screwdriver-wrench',
  intro:'Der Werkmeister: „Du schreibst die Skalierung jetzt zum fünften Mal. Bau dir ein Werkzeug.“ Funktionen nehmen Werte entgegen und liefern ein Ergebnis — ohne Gedächtnis. Du baust deine eigene Bibliothek: Maximum, Skalierung, Grenzwerte, Sortieren, Messwert-Aufbereitung.',
  anim: A('<rect x="110" y="44" width="80" height="60" rx="6" fill="#14150c" stroke="#ff8c00" stroke-width="2"/><text x="150" y="79" text-anchor="middle" font-size="11" fill="#ff8c00">FC</text>' + [0,1,2].map(i=>'<circle cx="40" cy="'+(50+i*24)+'" r="5" fill="#1ec8e0"><animate attributeName="cx" values="40;110" dur="1.6s" begin="'+(i*0.3)+'s" repeatCount="indefinite"/></circle>').join('') + '<circle cx="190" cy="74" r="6" fill="#39ff14"><animate attributeName="cx" values="190;262" dur="1.6s" begin="0.9s" repeatCount="indefinite"/></circle><text x="150" y="140" text-anchor="middle" font-size="9" fill="#8a8a8a">Werte rein → Ergebnis raus</text>') });
defChapter({ n:13, pro:true, title:'Bausteine mit Gedächtnis', subtitle:'FB · Instanzen · Multiinstanzen', icon:'fa-memory',
  intro:'ARIA hat alle Motoren der Halle mit einer einzigen Instanz verdrahtet: Schaltet einer, schalten alle. Funktionsbausteine haben ein Gedächtnis — ihren Instanz-DB. Du baust Flanken, Motoren mit Überwachung und Zähler als FBs, verschachtelst sie als Multiinstanzen und entwickelst einen Motorbaustein nach Firmenstandard.',
  anim: A('<rect x="30" y="40" width="100" height="70" rx="6" fill="#14150c" stroke="#39ff14"/><text x="80" y="60" text-anchor="middle" font-size="10" fill="#39ff14">Band1_DB</text><rect x="170" y="40" width="100" height="70" rx="6" fill="#14150c" stroke="#1ec8e0"/><text x="220" y="60" text-anchor="middle" font-size="10" fill="#1ec8e0">Band2_DB</text><circle cx="80" cy="86" r="8" fill="#39ff14"><animate attributeName="opacity" values="1;.2;1" dur="1.4s" repeatCount="indefinite"/></circle><circle cx="220" cy="86" r="8" fill="#1ec8e0"><animate attributeName="opacity" values=".2;1;.2" dur="1.4s" repeatCount="indefinite"/></circle><text x="150" y="140" text-anchor="middle" font-size="9" fill="#8a8a8a">ein Gerät = eine Instanz</text>') });
defChapter({ n:14, pro:true, title:'Daten mit Struktur', subtitle:'STRUCT · UDT · DB · STRING', icon:'fa-sitemap',
  intro:'Die Teiledaten liegen in vierzig losen Variablen — ARIA vertauscht sie nach Belieben. Du bringst Ordnung hinein: Strukturen, eigene PLC-Datentypen, Arrays von Datensätzen und globale Datenbausteine. Und die Zelle lernt sprechen: mit Texten für HMI und Protokoll.',
  anim: A('<rect x="60" y="24" width="180" height="22" rx="4" fill="#14150c" stroke="#ff8c00"/><text x="150" y="39" text-anchor="middle" font-size="10" fill="#ff8c00">"UDT_Teil"</text>' + [0,1,2,3].map(i=>'<rect x="'+(60+i*46)+'" y="64" width="40" height="44" rx="3" fill="#14150c" stroke="#3a3c2c"><animate attributeName="stroke" values="#3a3c2c;#39ff14;#3a3c2c" dur="3s" begin="'+(i*0.4)+'s" repeatCount="indefinite"/></rect><text x="'+(80+i*46)+'" y="82" text-anchor="middle" font-size="8" fill="#e0e0e0">Nr</text><text x="'+(80+i*46)+'" y="98" text-anchor="middle" font-size="8" fill="#8a8a8a">g</text>').join('') + '<text x="150" y="140" text-anchor="middle" font-size="9" fill="#1ec8e0">\'Teil 17: 498 g OK\'</text>') });
defChapter({ n:15, pro:true, title:'Das Anlagenprogramm', subtitle:'OB1 · OB100 · Standard · Export nach TIA', icon:'fa-industry',
  intro:'Finale der Profi-Stufe. ARIA hat das ganze Programm in einen 2000-Zeilen-Block kopiert. Du baust es nach Standard neu: OB1 ruft den Anlagen-FB auf, der Anlagen-FB seine Geräte. Mit Anlauf-OB, entkoppelten Eingängen, Schrittkette als Baustein — und am Ende exportierst du deine Bausteine als echte TIA-Quelle.',
  anim: A('<rect x="120" y="14" width="60" height="22" rx="4" fill="#14150c" stroke="#39ff14"/><text x="150" y="29" text-anchor="middle" font-size="10" fill="#39ff14">OB1</text><rect x="110" y="58" width="80" height="22" rx="4" fill="#14150c" stroke="#1ec8e0"/><text x="150" y="73" text-anchor="middle" font-size="10" fill="#1ec8e0">FB_Zelle</text>' + [0,1,2].map(i=>'<rect x="'+(40+i*80)+'" y="104" width="60" height="22" rx="4" fill="#14150c" stroke="#ff8c00"><animate attributeName="stroke-width" values="1;3;1" dur="2.4s" begin="'+(i*0.5)+'s" repeatCount="indefinite"/></rect><text x="'+(70+i*80)+'" y="119" text-anchor="middle" font-size="9" fill="#ff8c00">'+['#Band','#Pick','#Weiche'][i]+'</text>').join('') + '<path d="M150 36 V58 M150 80 V92 H70 V104 M150 92 V104 M150 92 H230 V104" stroke="#3a3c2c" stroke-width="2" fill="none"/>') });
})();
