defIO({
  S_Start: 'Starttaster',
  H_Gruen: 'Grüne Meldelampe',
  H_Rot: 'Rote Meldelampe',
  H_Gelb: 'Gelbe Meldelampe',
  Roh_Wert: 'Analogwert Ofentemperatur (0…27648)',
  Temp_Ist: 'Ofentemperatur in °C',
  Freigabe: 'Freigabe der Anlage',
  Laufzeit: 'Betriebszeit seit dem Einschalten',
  Anzeige: 'Anzeige an der Zelle',
  Warnung: 'Warnlampe',
  Teil_Sensor: 'Sensor: Teil erkannt',
  Palette_Leer: 'Meldung Palette leer',
  Rest_Anzeige: 'Anzeige Restteile auf der Palette',
  Teil_Abgelegt: 'Sensor: Teil abgelegt',
  Quittieren: 'Quittiertaster',
  Palette_Voll: 'Meldung Palette voll',
  Plaetze_Frei: 'Anzahl freier Palettenplätze',
  Teile_Anzahl: 'Anzahl Teile auf der Palette',
  Waage_Gewicht: 'Gewicht der Auslaufwaage in g',
  Waage_Alarm: 'Alarm Teil zu schwer',
  Waage_Anzeige: 'Anzeige Waage',
  Messwerte: 'Zehn Messwerte der Qualitätssicherung',
  Mittelwert: 'Mittelwert der Messwerte',
  Tagesproduktion: 'Zähler Tagesproduktion',
  Umrichter_Status: 'Statuswort des Frequenzumrichters',
  Quit: 'Quittiertaster Umrichter',
  Fehlerbits: 'Ausgewertete Fehlerbits des Umrichters',
  Umrichter_Befehl: 'Steuerwort an den Frequenzumrichter',
  Teile: 'Teileanzeige',
  S_Stopp: 'Stopptaster',
  S_Quit: 'Quittiertaster',
  Band_Motor: 'Motor Förderband',
  Stueckzahl: 'Stückzahl-Anzeige',
  Wert1: 'Messwert 1',
  Wert2: 'Messwert 2',
  Wert3: 'Messwert 3',
  Groesster: 'Grösster Wert',
  Gewicht1: 'Gewicht Waage 1',
  Gewicht2: 'Gewicht Waage 2',
  Gewicht3: 'Gewicht Waage 3',
  Temp1: 'Temperatur Fühler 1',
  Temp2: 'Temperatur Fühler 2',
  Temp3: 'Temperatur Fühler 3',
  Schwerstes: 'Gewicht des schwersten Teils',
  Heissester: 'Höchste Temperatur der drei Fühler',
  AI_Fuellstand: 'Rohwert Füllstandgeber',
  AI_Druck: 'Rohwert Drucksensor',
  AI_Temp: 'Rohwert Temperaturfühler',
  Fuellstand: 'Füllstand skaliert',
  Druck: 'Druck skaliert in bar',
  Temperatur: 'Temperatur skaliert in °C',
  Sollwert: 'Sollwert Heizung bzw. HMI',
  Soll_Begrenzt: 'Begrenzter Sollwert',
  Gewicht: 'Gewicht des Teils in g',
  Farbe_OK: 'Farbprüfung in Ordnung',
  Weiche_Winkel: 'Stellwinkel der Weiche',
  Teil_Gut: 'Prüfergebnis: Teil gut',
  Messreihe: 'Fünf Messwerte der Prüfstation',
  Kleinster: 'Kleinster Messwert',
  Zellen_Zustand: 'Zustandsnummer der Zelle',
  Druck_Begrenzt: 'Auf 2…8 bar begrenzter Druck',
  Alarm_Hoch: 'Alarm Wert zu hoch',
  Alarm_Tief: 'Alarm Wert zu tief',
  Ventil_Auf: 'Ventil Druckbehälter',
  AI_Fuell: 'Rohwert Füllstandgeber',
  Temp: 'Temperatur skaliert in °C',
  Status_Temp: 'Status Messung Temperatur',
  Status_Druck: 'Status Messung Druck',
  Status_Fuell: 'Status Messung Füllstand',
  Alarm_Temp: 'Alarm Temperatur',
  Alarm_Druck: 'Alarm Druck',
  Alarm_Fuell: 'Alarm Füllstand',
  Sammelalarm: 'Sammelalarm der drei Messungen',
  Taster: 'Taster Tastendruck-Zähler',
  Impuls: 'Impulssignal',
  Zaehler: 'Zähler Tastendrücke',
  Taster_Plus: 'HMI-Taster Plus',
  Taster_Minus: 'HMI-Taster Minus',
  Schutztuer_zu: 'Schutztür geschlossen',
  Band1_Lauf: 'Motor Band 1 läuft',
  Band2_Lauf: 'Motor Band 2 läuft',
  S_Start1: 'Starttaster Band 1',
  S_Start2: 'Starttaster Band 2',
  RM_Band1: 'Rückmeldung Motor Band 1',
  RM_Band2: 'Rückmeldung Motor Band 2',
  Band_Lauf: 'Motor Band läuft',
  Band_Stoerung: 'Störmeldung Band',
  Sensor_1: 'Sensor Teilezähler Band 1',
  Reset: 'Rücksetztaster Zähler',
  Ist_1: 'Istwert Stückzähler Band 1',
  Voll_1: 'Meldung Auftrag Band 1 voll',
  Rest_1: 'Restteile Auftrag Band 1',
  Anzeige_Starts: 'Anzeige Anzahl Einschaltungen',
  Laufzeit_s: 'Anzeige Laufzeit in Sekunden',
  Wartung: 'Wartungsmeldung',
  Automatik: 'Betriebsart Automatik aktiv',
  Schrank_Temp: 'Temperatur im Schaltschrank in °C',
  Luefter: 'Schaltschranklüfter',
  Stoer_1: 'Störmeldung Band 1',
  Stoer_2: 'Störmeldung Band 2',
  Sammelstoerung: 'Sammelstörung der Bänder',
  Starts_Gesamt: 'Summe der Motorstarts',
  Teil_Nr: 'Teilenummer',
  Teil_Gewicht: 'Teilegewicht in g',
  Teil_OK: 'Prüfergebnis: Teil in Ordnung',
  Charge: 'Chargendaten (8 Teile)',
  Anzahl_OK: 'Anzahl guter Teile der Charge',
  Gesamtgewicht: 'Gesamtgewicht der Charge',
  Uebernehmen: 'Taste Teil übernehmen',
  Scan_Nr: 'Nummer des gescannten Teils',
  Waage: 'Gewicht der Waage in g',
  Summe: 'Summe der Chargengewichte',
  Zustand: 'Zustandsnummer der Zelle',
  HMI_Text: 'Textzeile auf dem HMI',
  Scanner: 'Barcode-Text vom Scanner',
  Typ: 'Teiletyp aus dem Barcode',
  Nummer: 'Teilenummer aus dem Barcode',
  Variante: 'Variante aus dem Barcode',
  Code_OK: 'Barcode gültig',
  Stoerung_Band: 'Nummer des gestörten Bandes',
  I_Lichtschranke: 'Lichtschranke Station (Rohsignal)',
  Teil_da: 'Teil an der Station',
  Gewicht_OK: 'Gewicht in Ordnung',
  Arm_Soll: 'Sollwinkel Roboterarm',
  Greifer_Auf: 'Greifer offen',
  I_Start: 'Starttaster (Schliesser)',
  I_Stopp_NC: 'Stopptaster (Öffner)',
  I_Lichtschranke_NC: 'Lichtschranke (Öffner, TRUE = Strahl frei)',
  I_Tuer: 'Schutztür (Rohsignal)',
  Q_Band: 'Ausgang Bandmotor',
  LS_Station: 'Lichtschranke Station',
  Pruef_OK: 'Prüfergebnis: Teil gut',
  Gegriffen: 'Greifer hat das Teil gefasst',
  WS_Hand: 'Wahlschalter Hand',
  WS_Auto: 'Wahlschalter Automatik',
  Modus: 'Betriebsart (0 Aus, 1 Hand, 2 Auto)',
  Greifer_zu: 'Rückmeldung Greifer geschlossen',
  Schritt: 'Aktueller Schritt der Kette',
  Sensor_Band1: 'Sensor Band 1',
  Sensor_Band2: 'Sensor Band 2',
  Anzahl_1: 'Teilezähler Band 1',
  Anzahl_2: 'Teilezähler Band 2',
  Betrieb: 'Anlage in Betrieb',
  Stoerung: 'Störung der Anlage',
  Wartung_faellig: 'Wartung fällig',
  RM_Band: 'Rückmeldung Bandmotor',
  Lager: 'Zähler Lager (gute Teile)',
  Nacharbeit: 'Zähler Nacharbeit (schlechte Teile)'
});
