defIO({
  Achse_Grad: 'Sollwinkel des Roboterarms in Grad (0 Station, 90 Ablage)',
  Aktiv: 'Blinken aktiv (Störfall), TRUE = aktiv',
  Alle_Geprueft: 'Meldung: alle Teile geprüft',
  Ampel_Gelb: 'Gelbe Signallampe',
  Ampel_Gruen: 'Grüne Signallampe',
  Ampel_Rot: 'Rote Signallampe',
  Andock_Signal: 'Meldung: Greifer ist angedockt',
  Anlage_Aktiv: 'Meldung: Anlage in Bewegung (Greifen oder Transport)',
  Anzahl: 'Stückzähler: Anzahl gezählter Teile',
  Anzahl_Defekt: 'Anzahl defekter Teile der Charge',
  Anzahl_Gut: 'Anzahl guter Teile der Charge',
  Anzeige: 'Zahlenanzeige am Panel',
  Arm_In_Ablage: 'Rückmeldung: Arm in Ablageposition (90 Grad)',
  Arm_In_Station: 'Rückmeldung: Arm an der Aufnahmestation (0 Grad)',
  Arm_Oben: 'Rückmeldung: Arm in oberer Endlage',
  Band_Laeuft: 'Rückmeldung: Förderband läuft',
  Band_Lauf: 'Förderband, TRUE = läuft',
  Bedarf: 'Bedarf an Teilen (Stück)',
  Belegt: 'Anzahl belegter Lagerplätze',
  Codes: 'Seriennummern der Charge (Array)',
  Defekt: 'Defektmarkierung je Teil (Array), TRUE = defekt',
  Doppelt: 'Meldung: Seriennummer doppelt vorhanden',
  Endlage_Zu: 'Endlagenmeldung: Greifer geschlossen',
  Entnahme: 'Sensor: Schraube aus dem Magazin entnommen',
  Erster_Schwer: 'Index des ersten Teils über 500 g (-1 = keins)',
  Fach_Nr: 'Am Panel gewählte Fachnummer',
  Farbe: 'Erkannte Teilefarbe (Code 1, 2 …)',
  Fertig: 'Meldung: Vorgang fertig',
  Frei_Platz: 'Index des ersten freien Lagerplatzes (-1 = voll)',
  Freigabe: 'Freigabe erteilt (TRUE = frei)',
  Gereinigt: 'Meldung: Greifer wurde gereinigt',
  Gewicht: 'Gewicht in Gramm (Einzelwert oder Liste je Teil)',
  Gewichte: 'Gewichte der Teile in Gramm (Array)',
  Greif_Impuls: 'Impuls: Greifbefehl auslösen',
  Greifer_Auf: 'Greifer öffnen (TRUE = offen, FALSE = zu)',
  Greifer_Bereit: 'Meldung: Unterdruck steht, Greifer bereit',
  Greifer_Offen: 'Rückmeldung: Greifer offen',
  Greifer_Zu: 'Rückmeldung: Greifer geschlossen',
  Gueltig: 'Anzahl gültiger Messwerte',
  Gut_Quote: 'Anteil guter Teile in Prozent (REAL)',
  Hupe: 'Signalhupe',
  Karton_Voll: 'Meldung: Karton voll',
  Kisten: 'Benötigte Versandkisten',
  Laenge: 'Teilelängen in mm (Array)',
  Lager: 'Lagerbelegung (Array): Teilenummer, 0 = frei',
  Lager_Voll: 'Meldung: Lager voll',
  Lampe: 'Gelbe Signallampe (Blinklicht)',
  Leer: 'Meldung: Magazin leer (Nachfüllen)',
  Licht: 'Hallenbeleuchtung der Zelle',
  Los: 'Losgrösse in Stück',
  Luefter_An: 'Kühllüfter des Bandmotors',
  Max_Gewicht: 'Grösstes Gewicht der Charge in Gramm',
  Max_Gut_Gewicht: 'Höchstes Gewicht unter den guten Teilen in Gramm',
  Merk_Farbe: 'Im Ablauf gemerkte Farbe des Teils',
  Messung: 'Temperaturmesswerte (Array), -1 = ungültig',
  Mittelwert: 'Durchschnittsgewicht in Gramm (REAL)',
  Motor_Laeuft: 'Rückmeldung: Bandmotor läuft',
  Nachgefuellt: 'Meldung: Magazin nachgefüllt',
  Neues_Teil: 'Teilenummer des neu eintreffenden Teils (0 = keins)',
  Not_Aus: 'Not-Halt, TRUE = ausgelöst',
  Platz: 'Belegung der 6 Bandplätze (Array)',
  Platz_Nr: 'Nummer des gefundenen freien Lagerplatzes (-1 = keiner)',
  Position: 'Index des gesuchten Eintrags (-1 = keiner)',
  Quittieren: 'Quittiertaster, TRUE = gedrückt',
  Rest: 'Noch nicht verpackte Teile (Hilfswert)',
  Restzeit: 'Restzeit des Aushärtevorgangs (TIME)',
  Schliessen: 'Befehl: Greifer schliessen',
  Schritt: 'Aktueller Schritt der Ablaufkette',
  Start: 'Startsignal, TRUE = Start angefordert',
  Start_Taster: 'Starttaster am Panel',
  Stoerung: 'Störungsmeldung, TRUE = Störung aktiv',
  Stopp_Taster: 'Stopptaster am Panel',
  Summe: 'Summenwert (Rechenergebnis)',
  Taster: 'Taster am Panel, TRUE = gedrückt',
  Teil_Da: 'Sensor: Teil an der Station',
  Teil_Erkannt: 'Lichtschranke: Teil erkannt',
  Teil_Typ: 'Erkannter Teiletyp (Code 1, 2 …)',
  Teil_Weg: 'Impuls: Teil hat die Station verlassen',
  Teile: 'Anzahl bestellter Teile',
  Teile_Bereit: 'Meldung: alle Teile bereit',
  Teile_Geprueft: 'Prüfmerker je Teil (Array), TRUE = geprüft',
  Teile_Gewichte: 'Gewichtsspeicher der Teile in Gramm (Array)',
  Teile_OK: 'Gutmeldung je Teil (Array), TRUE = in Ordnung',
  Teile_Sensoren: 'Teilesensoren der 5 Stationen (Array), TRUE = Teil da',
  Teile_Zaehler: 'Zähler der geprüften Teile',
  Temp: 'Hilfsvariable zum Tauschen von Werten',
  Warnung: 'Anlaufwarnung, TRUE = aktiv',
  Weiche_Pos: 'Sollwinkel der Weiche in Grad',
  Weiter: 'Freigabe zur Weitergabe des Teils',
  Zaehler: 'Zählerfeld (Array) für Durchläufe je Platz',
  Zyklen: 'Zähler der Greifzyklen',
  i: 'Laufvariable (Index) für die Suche'
});
