defIO({
  Greifer_Auf: 'Greifer offen (TRUE) / geschlossen (FALSE)',
  Achse_Grad: 'Achswinkel in Grad (0 = Greifstation)',
  Band_Lauf: 'Förderband läuft',
  Ampel_Gruen: 'Grüne Signallampe (TRUE = leuchtet)',
  Ampel_Gelb: 'Gelbe Signallampe (TRUE = leuchtet)',
  Ampel_Rot: 'Rote Signallampe (TRUE = leuchtet)',
  Teil_Erkannt: 'Lichtschranke: Werkstück erkannt',
  Anzeige_Gewicht: 'Gewichtsanzeige der Waage (REAL)',
  Start_Winkel: 'Startwinkel der Achse in Grad',
  Teile_Gesamt: 'Gesamtzahl der Teile',
  Teile_Defekt: 'Anzahl defekter Teile',
  Anzeige_Teile: 'Anzeige: Anzahl guter Teile',
  Sicherheit_OK: 'Sicherheitskreis in Ordnung',
  Freigabe: 'Freigabe der Zelle (TRUE = erteilt)',
  Taster_Links: 'Not-Halt-Taster links gedrückt',
  Taster_Rechts: 'Not-Halt-Taster rechts gedrückt',
  Not_Halt_Aktiv: 'Not-Halt ausgelöst',
  Tuer_Zu: 'Schutztür geschlossen',
  Zelle_Sicher: 'Zelle gesichert',
  Weg_Frei: 'Weg im Greifbereich frei',
  Hand_Links: 'Zweihand-Taster links gedrückt',
  Hand_Rechts: 'Zweihand-Taster rechts gedrückt',
  Warnung: 'Gelbe Warnlampe (TRUE = leuchtet)',
  Greifen_Erlaubt: 'Greifer darf arbeiten',
  Auto_Modus: 'Automatikbetrieb gewählt',
  Sensor_A: 'Lichtschranke A meldet Teil',
  Sensor_B: 'Lichtschranke B meldet Teil',
  Wartung: 'Wartungsmodus aktiv',
  Tuer_1_Offen: 'Tür 1 offen',
  Tuer_2_Offen: 'Tür 2 offen',
  Alarm: 'Alarmausgang (Hupe / Warnleuchte)',
  Start: 'Start-Taster gedrückt',
  Stopp: 'Stopp-Taster gedrückt',
  Motor: 'Motor läuft',
  Zaun_Offen: 'Schutzzaun offen',
  ARIA_Override: 'ARIA-Override aktiv (Fremdzugriff)',
  Temperatur: 'Gemessene Temperatur in °C',
  Gewicht: 'Gewicht des Werkstücks in Gramm',
  Gewicht_OK: 'Gewichtsprüfung bestanden',
  Gut: 'Anzahl guter Teile',
  Schlecht: 'Anzahl schlechter Teile (Ausschuss)',
  Gesamt: 'Gesamtzahl der Teile',
  Differenz: 'Differenz gute minus schlechte Teile',
  Teile_Nr: 'Laufende Nummer des Werkstücks',
  Pruefen: 'Werkstück zur Kontrolle ausschleusen',
  Wert_A: 'Messwert A',
  Wert_B: 'Messwert B',
  Mittelwert: 'Mittelwert aus Messwert A und B (REAL)',
  Rohwert: 'Analogrohwert Füllstandssensor (0…27648)',
  Fuellstand: 'Füllstand des Materialbunkers in Prozent',
  Soll_Pos: 'Soll-Position der Achse',
  Ist_Pos: 'Ist-Position der Achse',
  Schleppfehler: 'Schleppfehler der Achse',
  Soll_Winkel: 'Vorgegebener Soll-Winkel der Achse in Grad',
  Soll: 'Sollwert der Position',
  Ist: 'Istwert der Position',
  Abweichung: 'Betrag der Abweichung zwischen Soll und Ist',
  Toleranz_Fehler: 'Toleranzfehler (Abweichung zu gross)',
  Brutto: 'Bruttogewicht in Gramm',
  Tara: 'Tara (Verpackungsgewicht) in Gramm',
  Netto: 'Nettogewicht in Gramm',
  Abweichung_Prozent: 'Gewichtsabweichung vom Sollgewicht in Prozent (REAL)',
  Luefter_Stufe: 'Lüfterstufe des Antriebsmotors (0, 1, 2)',
  Luefter: 'Schaltschranklüfter läuft',
  Farbe: 'Farbcode des Werkstücks (1 = rot, 2 = grün)',
  Weiche_Pos: 'Weichenstellung (Bahn A positiv, Bahn B negativ)',
  Not_Aus: 'Not-Aus ausgelöst',
  Modus: 'Betriebsart (0 Aus, 1 Hand, 2 Automatik, 3 Wartung)',
  Lampe_Wartung: 'Wartungslampe (TRUE = leuchtet)',
  Teil_Typ: 'Teiletyp (1 = gut, 2 = Ausschuss)',
  Fehlercode: 'Aktueller Fehlercode der Zelle',
  Geschwindigkeit: 'Vorgegebene Bandgeschwindigkeit in Prozent',
  Band_Stufe: 'Antriebsstufe des Bandes (1 bis 3)',
  Stoerung: 'Störungsmeldung der Zelle',
  Position: 'Positionsnummer vom Leitrechner',
  Rezept: 'Gewähltes Rezept (Nummer)',
  Soll_Temp: 'Solltemperatur des Rezepts in °C',
  ARIA_Aktiv: 'ARIA hat die Anlage übernommen',
  Modus_Gesperrt: 'Betriebsartwahl gesperrt'
});
