/* PLC-Variablen SCL Quest (Feedback-Auftrag Paket 5.2) – erzeugt mit node gen_tags.js scl, Kommentare von Hand gepflegt.
   Dieselbe Variable hat in allen Aufgaben dieselbe Adresse. Eingänge %I, Ausgänge %Q, Merker %M; Texte/Felder im DB "Daten"; Timer/Zähler als IEC-Instanz. */
(function(root){
root.PLC_TAGS = {
  "Abweichung": { addr: "%QW64", type: "Int", comment: "Betrag Abweichung Soll/Ist in Grad" },
  "Abweichung_Prozent": { addr: "%MD200", type: "Real", comment: "Abweichung vom Sollgewicht in %" },
  "Achse_Grad": { addr: "%QW66", type: "Int", comment: "Sollwinkel Roboterachse in Grad" },
  "AI_Druck": { addr: "%IW64", type: "Int", comment: "Analogeingang Drucksensor (0…27648)" },
  "AI_Fuell": { addr: "%IW66", type: "Int", comment: "Analogeingang Füllstandsensor (0…27648)" },
  "AI_Fuellstand": { addr: "%IW68", type: "Int", comment: "Analogeingang Füllstand Tank (0…27648)" },
  "AI_Temp": { addr: "%IW70", type: "Int", comment: "Analogeingang Temperaturfühler (0…27648)" },
  "Aktiv": { addr: "%Q0.0", type: "Bool", comment: "Blinker einschalten" },
  "Alarm": { addr: "%Q0.1", type: "Bool", comment: "Alarmmeldung Zelle" },
  "Alarm_Druck": { addr: "%Q0.2", type: "Bool", comment: "Grenzwertalarm Druck" },
  "Alarm_Fuell": { addr: "%Q0.3", type: "Bool", comment: "Grenzwertalarm Füllstand" },
  "Alarm_Hoch": { addr: "%Q0.4", type: "Bool", comment: "Alarm Druck zu hoch" },
  "Alarm_Temp": { addr: "%Q0.5", type: "Bool", comment: "Grenzwertalarm Temperatur" },
  "Alarm_Tief": { addr: "%Q0.6", type: "Bool", comment: "Alarm Druck zu tief" },
  "Alle_Geprueft": { addr: "%Q0.7", type: "Bool", comment: "Meldung alle Teile geprüft" },
  "Ampel_Gelb": { addr: "%Q1.0", type: "Bool", comment: "Signalsäule gelb" },
  "Ampel_Gruen": { addr: "%Q1.1", type: "Bool", comment: "Signalsäule grün" },
  "Ampel_Rot": { addr: "%Q1.2", type: "Bool", comment: "Signalsäule rot" },
  "Andock_Signal": { addr: "%Q1.3", type: "Bool", comment: "Greifer angedockt" },
  "Anlage_Aktiv": { addr: "%Q1.4", type: "Bool", comment: "Meldung Anlage in Betrieb" },
  "Anlauf_Timer": { addr: "IEC-Instanz", type: "TON", comment: "Anlaufverzögerung Band (TON)" },
  "Anzahl": { addr: "%QW68", type: "Int", comment: "Anzahl gezählte Teile" },
  "Anzahl_1": { addr: "%QW70", type: "Int", comment: "Zählerstand Band 1" },
  "Anzahl_2": { addr: "%QW72", type: "Int", comment: "Zählerstand Band 2" },
  "Anzahl_Defekt": { addr: "%QW74", type: "Int", comment: "Anzahl defekte Teile" },
  "Anzahl_Gut": { addr: "%MW100", type: "Int", comment: "Anzahl gute Teile" },
  "Anzahl_OK": { addr: "%QW76", type: "Int", comment: "Anzahl OK-Teile der Charge" },
  "Anzeige": { addr: "%MD204", type: "Real", comment: "Anzeigewert am Bedienpanel" },
  "Anzeige_Gewicht": { addr: "%MD208", type: "Real", comment: "Gewichtsanzeige am Bedienpanel" },
  "Anzeige_Starts": { addr: "%MD212", type: "DInt", comment: "Anzeige Anzahl Motorstarts" },
  "Anzeige_Teile": { addr: "%QW78", type: "Int", comment: "Panelanzeige Anzahl Gutteile" },
  "ARIA_Aktiv": { addr: "%Q1.5", type: "Bool", comment: "ARIA greift in die Steuerung ein" },
  "ARIA_Override": { addr: "%Q1.6", type: "Bool", comment: "ARIA übersteuert die Zelle" },
  "Arm_In_Ablage": { addr: "%I0.0", type: "Bool", comment: "Endlage Arm an Ablage" },
  "Arm_In_Station": { addr: "%I0.1", type: "Bool", comment: "Endlage Arm an Greifstation" },
  "Arm_Oben": { addr: "%I0.2", type: "Bool", comment: "Endlage Arm oben" },
  "Arm_Soll": { addr: "%QW80", type: "Int", comment: "Sollwinkel Arm in Grad" },
  "Auto_Modus": { addr: "%Q1.7", type: "Bool", comment: "Betriebsart Automatik (FALSE = Hand)" },
  "Automatik": { addr: "%I0.3", type: "Bool", comment: "Betriebsart Automatik angewählt" },
  "Band_Laeuft": { addr: "%Q2.0", type: "Bool", comment: "Förderband ein (mit Nachlauf)" },
  "Band_Lauf": { addr: "%Q2.1", type: "Bool", comment: "Förderband Motor ein" },
  "Band_Motor": { addr: "%Q2.2", type: "Bool", comment: "Schütz Bandmotor" },
  "Band_Stoerung": { addr: "%I0.4", type: "Bool", comment: "Störung Bandmotor (keine Rückmeldung)" },
  "Band_Stufe": { addr: "%QW82", type: "Int", comment: "Antriebsstufe Förderband (1…3)" },
  "Band_Timer": { addr: "IEC-Instanz", type: "TON", comment: "Bandlaufzeit beim Sortieren (TON)" },
  "Band1_Lauf": { addr: "%Q2.3", type: "Bool", comment: "Förderband 1 ein" },
  "Band2_Lauf": { addr: "%Q2.4", type: "Bool", comment: "Förderband 2 ein" },
  "Bedarf": { addr: "%IW72", type: "Int", comment: "Benötigte Teilezahl" },
  "Belegt": { addr: "%IW74", type: "Int", comment: "Anzahl belegte Lagerplätze" },
  "Bereit_Timer": { addr: "IEC-Instanz", type: "TON", comment: "Wartezeit Unterdruck Greifer (TON)" },
  "Betrieb": { addr: "%I0.5", type: "Bool", comment: "Anlage in Betrieb" },
  "Brutto": { addr: "%IW76", type: "Int", comment: "Bruttogewicht Waage in g" },
  "Charge": { addr: "%MD216", type: "ARRAY[1..8] OF \"UDT_Teil\"", comment: "Charge mit 8 Teilen" },
  "Code_OK": { addr: "%Q2.5", type: "Bool", comment: "Barcode gültig" },
  "Codes": { addr: "\"Daten\".Codes", type: "Array", comment: "Gelesene Teilecodes" },
  "Defekt": { addr: "\"Daten\".Defekt", type: "Array", comment: "Defektmeldung je Teil (TRUE = defekt)" },
  "Differenz": { addr: "%QW84", type: "Int", comment: "Gute minus schlechte Teile" },
  "Doppelt": { addr: "%Q2.6", type: "Bool", comment: "Doppelter Teilecode gefunden" },
  "Druck": { addr: "%MD220", type: "Real", comment: "Druck in bar" },
  "Druck_Begrenzt": { addr: "%MD224", type: "Real", comment: "Druck begrenzt in bar" },
  "Endlage_Zu": { addr: "%I0.6", type: "Bool", comment: "Endlage Greifer geschlossen" },
  "Entnahme": { addr: "%Q2.7", type: "Bool", comment: "Schraube aus Magazin entnommen" },
  "Erster_Schwer": { addr: "%QW86", type: "Int", comment: "Index erstes Teil über 500 g" },
  "Fach_Nr": { addr: "%IW78", type: "Int", comment: "Gewählte Fachnummer am Panel" },
  "Farbe": { addr: "%IW80", type: "Int", comment: "Farbcode Teil (1 = rot, 2 = grün)" },
  "Farbe_OK": { addr: "%I0.7", type: "Bool", comment: "Farbprüfung in Ordnung" },
  "Fehlerbits": { addr: "%QW88", type: "Word", comment: "Fehlerbits aus Umrichter-Statuswort" },
  "Fehlercode": { addr: "%QW90", type: "Int", comment: "Aktueller Fehlercode der Zelle" },
  "Fertig": { addr: "%Q3.0", type: "Bool", comment: "Meldung Ablauf fertig" },
  "Frei_Platz": { addr: "%QW92", type: "Int", comment: "Index erster freier Lagerplatz" },
  "Freigabe": { addr: "%Q3.1", type: "Bool", comment: "Freigabe Zelle" },
  "Fuellstand": { addr: "%MD228", type: "Real", comment: "Füllstand Tank in %" },
  "Gegriffen": { addr: "%Q3.2", type: "Bool", comment: "Meldung Teil gegriffen" },
  "Gereinigt": { addr: "%Q3.3", type: "Bool", comment: "Quittung Greiferreinigung erledigt" },
  "Gesamt": { addr: "%QW94", type: "Int", comment: "Anzahl Teile gesamt" },
  "Gesamtgewicht": { addr: "%MD232", type: "Real", comment: "Gesamtgewicht der Charge in g" },
  "Geschwindigkeit": { addr: "%IW82", type: "Int", comment: "Bandgeschwindigkeit in %" },
  "Gewicht": { addr: "%MD236", type: "Real", comment: "Teilegewicht in g" },
  "Gewicht_OK": { addr: "%I1.0", type: "Bool", comment: "Gewicht im Toleranzbereich" },
  "Gewicht1": { addr: "%IW84", type: "Int", comment: "Gewicht Teil 1 in g" },
  "Gewicht2": { addr: "%IW86", type: "Int", comment: "Gewicht Teil 2 in g" },
  "Gewicht3": { addr: "%IW88", type: "Int", comment: "Gewicht Teil 3 in g" },
  "Gewichte": { addr: "\"Daten\".Gewichte", type: "Array", comment: "Gespeicherte Gewichte je Fach" },
  "Greif_Impuls": { addr: "%Q3.4", type: "Bool", comment: "Greifimpuls (ein Zyklus)" },
  "Greif_Timer": { addr: "IEC-Instanz", type: "TON", comment: "Greifzeit (TON)" },
  "Greifen_Erlaubt": { addr: "%Q3.5", type: "Bool", comment: "Freigabe Greifen" },
  "Greifer_Auf": { addr: "%Q3.6", type: "Bool", comment: "Greifer öffnen (TRUE = offen)" },
  "Greifer_Bereit": { addr: "%Q3.7", type: "Bool", comment: "Greifer bereit (Unterdruck steht)" },
  "Greifer_Offen": { addr: "%I1.1", type: "Bool", comment: "Endlage Greifer offen" },
  "Greifer_zu": { addr: "%I1.2", type: "Bool", comment: "Endlage Greifer geschlossen" },
  "Greifer_Zu": { addr: "%I1.3", type: "Bool", comment: "Endlage Greifer geschlossen" },
  "Groesster": { addr: "%QW96", type: "Int", comment: "Grösster Wert" },
  "Gueltig": { addr: "%IW90", type: "Int", comment: "Anzahl gültige Messwerte" },
  "Gut": { addr: "%IW92", type: "Int", comment: "Anzahl gute Teile" },
  "Gut_Quote": { addr: "%MD240", type: "Real", comment: "Anteil guter Teile in %" },
  "H_Gelb": { addr: "%Q4.0", type: "Bool", comment: "Meldeleuchte gelb" },
  "H_Gruen": { addr: "%Q4.1", type: "Bool", comment: "Meldeleuchte grün" },
  "H_Rot": { addr: "%Q4.2", type: "Bool", comment: "Meldeleuchte rot" },
  "Haerten": { addr: "IEC-Instanz", type: "TON", comment: "Härtezeit (TON)" },
  "Halte_Timer": { addr: "IEC-Instanz", type: "TON", comment: "Haltezeit Klebestation (TON)" },
  "Hand_Links": { addr: "%I1.4", type: "Bool", comment: "Handtaster links" },
  "Hand_Rechts": { addr: "%I1.5", type: "Bool", comment: "Handtaster rechts" },
  "Heb_Timer": { addr: "IEC-Instanz", type: "TON", comment: "Hebezeit Arm (TON)" },
  "Heissester": { addr: "%QW98", type: "Int", comment: "Höchste Temperatur in °C" },
  "HMI_Text": { addr: "%MD244", type: "STRING[24]", comment: "Textzeile Bedienpanel" },
  "Hupe": { addr: "%Q4.3", type: "Bool", comment: "Warnhupe" },
  "Hupen_Impuls": { addr: "IEC-Instanz", type: "TP", comment: "Hupenimpuls (TP)" },
  "i": { addr: "%MW102", type: "Int", comment: "Laufindex Schleife" },
  "I_Lichtschranke": { addr: "%I1.6", type: "Bool", comment: "Lichtschranke Station (Rohsignal)" },
  "I_Lichtschranke_NC": { addr: "%I1.7", type: "Bool", comment: "Lichtschranke Station, Öffner (TRUE = frei)" },
  "I_Start": { addr: "%I2.0", type: "Bool", comment: "Taster Start (Schliesser)" },
  "I_Stopp_NC": { addr: "%I2.1", type: "Bool", comment: "Taster Stopp (Öffner)" },
  "I_Tuer": { addr: "%Q4.4", type: "Bool", comment: "Schutztür geschlossen (Rohsignal)" },
  "Impuls": { addr: "%I2.2", type: "Bool", comment: "Flankenimpuls Taster" },
  "Ist": { addr: "%QW100", type: "Int", comment: "Istwinkel Achse in Grad" },
  "Ist_1": { addr: "%QW102", type: "Int", comment: "Zählerstand Band 1" },
  "Ist_Pos": { addr: "%QW104", type: "Int", comment: "Istposition Achse in Grad" },
  "Karton_Voll": { addr: "%Q4.5", type: "Bool", comment: "Karton voll" },
  "Karton_Zaehler": { addr: "IEC-Instanz", type: "CTU", comment: "Teilezähler Karton (CTU)" },
  "Kisten": { addr: "%QW106", type: "Int", comment: "Anzahl benötigte Kisten" },
  "Klebe_Timer": { addr: "IEC-Instanz", type: "TON", comment: "Klebezeit (TON)" },
  "Kleinster": { addr: "%IW94", type: "Int", comment: "Kleinster Messwert" },
  "Laenge": { addr: "\"Daten\".Laenge", type: "Array", comment: "Gemessene Teilelängen" },
  "Lager": { addr: "\"Daten\".Lager", type: "Array", comment: "Lagerbelegung bzw. Teile im Lager" },
  "Lager_Voll": { addr: "%Q4.6", type: "Bool", comment: "Lager voll" },
  "Lampe": { addr: "%Q4.7", type: "Bool", comment: "Blinklampe" },
  "Lampe_Wartung": { addr: "%Q5.0", type: "Bool", comment: "Meldeleuchte Wartung" },
  "Laufzeit": { addr: "%MD248", type: "Time", comment: "Laufzeit seit Einschalten" },
  "Laufzeit_s": { addr: "%MD252", type: "DInt", comment: "Laufzeit Band in Sekunden" },
  "Leer": { addr: "%Q5.1", type: "Bool", comment: "Magazin leer (Nachfüllen)" },
  "Licht": { addr: "%Q5.2", type: "Bool", comment: "Hallenlicht ein" },
  "Los": { addr: "%QW108", type: "Int", comment: "Losgrösse in Teilen" },
  "LS_Station": { addr: "%I2.3", type: "Bool", comment: "Lichtschranke Teil an Station" },
  "Luefter": { addr: "%Q5.3", type: "Bool", comment: "Lüfter ein" },
  "Luefter_An": { addr: "%Q5.4", type: "Bool", comment: "Lüfter ein (mit Nachlauf)" },
  "Luefter_Stufe": { addr: "%QW110", type: "Int", comment: "Lüfterstufe (0…2)" },
  "Luefter_Timer": { addr: "IEC-Instanz", type: "TOF", comment: "Lüfternachlauf (TOF)" },
  "Magazin": { addr: "IEC-Instanz", type: "CTD", comment: "Schraubenzähler Magazin (CTD)" },
  "Max_Gewicht": { addr: "%QW112", type: "Int", comment: "Grösstes Teilegewicht in g" },
  "Max_Gut_Gewicht": { addr: "%MW104", type: "Int", comment: "Grösstes Gewicht guter Teile in g" },
  "Merk_Farbe": { addr: "%IW96", type: "Int", comment: "Gemerkte Farbe des Teils" },
  "Messreihe": { addr: "%MD256", type: "ARRAY[1..5] OF INT", comment: "Messreihe (5 Werte)" },
  "Messung": { addr: "\"Daten\".Messung", type: "Array", comment: "Messwerte (negativ = ungültig)" },
  "Messwerte": { addr: "%MD260", type: "ARRAY[1..10] OF REAL", comment: "Messwerte (10 Werte)" },
  "Mittelwert": { addr: "%MD264", type: "Real", comment: "Mittelwert" },
  "Modus": { addr: "%QW114", type: "Int", comment: "Betriebsart (Nummer)" },
  "Modus_Gesperrt": { addr: "%Q5.5", type: "Bool", comment: "Betriebsart durch ARIA gesperrt" },
  "Motor": { addr: "%Q5.6", type: "Bool", comment: "Motor ein" },
  "Motor_Laeuft": { addr: "%I2.4", type: "Bool", comment: "Rückmeldung Motor läuft" },
  "Nacharbeit": { addr: "%QW116", type: "Int", comment: "Anzahl Teile Nacharbeit" },
  "Nachgefuellt": { addr: "%I2.5", type: "Bool", comment: "Magazin nachgefüllt" },
  "Nachlauf_Timer": { addr: "IEC-Instanz", type: "TOF", comment: "Bandnachlauf (TOF)" },
  "Netto": { addr: "%QW118", type: "Int", comment: "Nettogewicht in g" },
  "Neues_Teil": { addr: "%QW120", type: "Int", comment: "Nummer neues Teil (0 = keins)" },
  "Not_Aus": { addr: "%Q5.7", type: "Bool", comment: "Not-Aus betätigt" },
  "Not_Halt_Aktiv": { addr: "%Q6.0", type: "Bool", comment: "Not-Halt ausgelöst" },
  "Nummer": { addr: "%QW122", type: "Int", comment: "Teilenummer aus Barcode" },
  "Palette_Leer": { addr: "%Q6.1", type: "Bool", comment: "Palette leer" },
  "Palette_Voll": { addr: "%Q6.2", type: "Bool", comment: "Palette voll" },
  "Plaetze_Frei": { addr: "%QW124", type: "Int", comment: "Freie Plätze auf Palette" },
  "Platz": { addr: "\"Daten\".Platz", type: "Array", comment: "Bandplätze mit Teilenummer" },
  "Platz_Nr": { addr: "%QW126", type: "Int", comment: "Index gefundener freier Lagerplatz" },
  "Position": { addr: "%QW128", type: "Int", comment: "Positionsnummer bzw. gefundener Index" },
  "Pruef_OK": { addr: "%I2.6", type: "Bool", comment: "Prüfergebnis Teil gut" },
  "Pruefen": { addr: "%Q6.3", type: "Bool", comment: "Teil zur Stichprobe ausschleusen" },
  "Q_Band": { addr: "%Q6.4", type: "Bool", comment: "Schütz Förderband" },
  "Quit": { addr: "%I2.7", type: "Bool", comment: "Taster Quittieren" },
  "Quitt_Flanke": { addr: "IEC-Instanz", type: "R_TRIG", comment: "Flanke Quittiertaster (R_TRIG)" },
  "Quittieren": { addr: "%I3.0", type: "Bool", comment: "Taster Quittieren" },
  "Reset": { addr: "%I3.1", type: "Bool", comment: "Taster Zähler zurücksetzen" },
  "Rest": { addr: "%QW130", type: "Int", comment: "Restanzahl Teile" },
  "Rest_1": { addr: "%QW132", type: "Int", comment: "Restteile bis Sollmenge Band 1" },
  "Rest_Anzeige": { addr: "%QW134", type: "Int", comment: "Anzeige Restteile Palette" },
  "Restzeit": { addr: "%MD268", type: "Time", comment: "Restzeit Härten" },
  "Rezept": { addr: "%IW98", type: "Int", comment: "Gewähltes Rezept (Nummer)" },
  "RM_Band": { addr: "%I3.2", type: "Bool", comment: "Rückmeldung Bandmotor läuft" },
  "RM_Band1": { addr: "%I3.3", type: "Bool", comment: "Rückmeldung Band 1 läuft" },
  "RM_Band2": { addr: "%I3.4", type: "Bool", comment: "Rückmeldung Band 2 läuft" },
  "Roh_Wert": { addr: "%IW100", type: "Int", comment: "Analogwert roh (0…27648)" },
  "Rohwert": { addr: "%IW102", type: "Int", comment: "Füllstand Analogwert roh (0…27648)" },
  "S_Quit": { addr: "%I3.5", type: "Bool", comment: "Taster Quittieren" },
  "S_Start": { addr: "%I3.6", type: "Bool", comment: "Taster Start" },
  "S_Start1": { addr: "%I3.7", type: "Bool", comment: "Taster Start Band 1" },
  "S_Start2": { addr: "%I4.0", type: "Bool", comment: "Taster Start Band 2" },
  "S_Stopp": { addr: "%I4.1", type: "Bool", comment: "Taster Stopp" },
  "Sammelalarm": { addr: "%I4.2", type: "Bool", comment: "Sammelalarm Messwerte" },
  "Sammelstoerung": { addr: "%Q6.5", type: "Bool", comment: "Sammelstörung Bänder" },
  "Scan_Nr": { addr: "%MD272", type: "DInt", comment: "Gescannte Teilenummer" },
  "Scanner": { addr: "%MD276", type: "STRING[20]", comment: "Barcode vom Scanner" },
  "Schlecht": { addr: "%IW104", type: "Int", comment: "Anzahl schlechte Teile" },
  "Schleppfehler": { addr: "%Q6.6", type: "Bool", comment: "Schleppfehler Achse (Soll ungleich Ist)" },
  "Schliessen": { addr: "%Q6.7", type: "Bool", comment: "Befehl Greifer schliessen" },
  "Schrank_Temp": { addr: "%MD280", type: "Real", comment: "Schaltschranktemperatur in °C" },
  "Schritt": { addr: "%QW136", type: "Int", comment: "Aktueller Schritt der Schrittkette" },
  "Schutztuer_zu": { addr: "%Q7.0", type: "Bool", comment: "Schutztür geschlossen" },
  "Schwerstes": { addr: "%MD284", type: "DInt", comment: "Schwerstes Teil" },
  "Sensor_1": { addr: "%I4.3", type: "Bool", comment: "Teilesensor Band 1" },
  "Sensor_A": { addr: "%I4.4", type: "Bool", comment: "Teilesensor A am Band" },
  "Sensor_B": { addr: "%I4.5", type: "Bool", comment: "Teilesensor B am Band" },
  "Sensor_Band1": { addr: "%I4.6", type: "Bool", comment: "Teilesensor Band 1" },
  "Sensor_Band2": { addr: "%I4.7", type: "Bool", comment: "Teilesensor Band 2" },
  "Sicherheit_OK": { addr: "%I5.0", type: "Bool", comment: "Sicherheitskreis in Ordnung" },
  "Soll": { addr: "%IW106", type: "Int", comment: "Sollwinkel Achse in Grad" },
  "Soll_Begrenzt": { addr: "%MD288", type: "Real", comment: "Sollwert begrenzt" },
  "Soll_Pos": { addr: "%QW138", type: "Int", comment: "Sollposition Achse in Grad" },
  "Soll_Temp": { addr: "%QW140", type: "Int", comment: "Solltemperatur Ofen in °C" },
  "Soll_Winkel": { addr: "%QW142", type: "Int", comment: "Sollwinkel vom Bediener in Grad" },
  "Sollwert": { addr: "%MD292", type: "Real", comment: "Sollwert" },
  "Start": { addr: "%I5.1", type: "Bool", comment: "Taster Start" },
  "Start_Flanke": { addr: "IEC-Instanz", type: "R_TRIG", comment: "Flanke Starttaster (R_TRIG)" },
  "Start_Taster": { addr: "%I5.2", type: "Bool", comment: "Taster Start" },
  "Start_Trigger": { addr: "IEC-Instanz", type: "R_TRIG", comment: "Flanke Starttaster (R_TRIG)" },
  "Start_Winkel": { addr: "%QW144", type: "Int", comment: "Startwinkel Achse in Grad" },
  "Starts_Gesamt": { addr: "%MD296", type: "DInt", comment: "Motorstarts beider Bänder gesamt" },
  "Status_Druck": { addr: "%QW146", type: "Int", comment: "Messstatus Druck (0 = in Ordnung)" },
  "Status_Fuell": { addr: "%QW148", type: "Int", comment: "Messstatus Füllstand (0 = in Ordnung)" },
  "Status_Temp": { addr: "%QW150", type: "Int", comment: "Messstatus Temperatur (0 = in Ordnung)" },
  "Stoer_1": { addr: "%Q7.1", type: "Bool", comment: "Störung Band 1" },
  "Stoer_2": { addr: "%Q7.2", type: "Bool", comment: "Störung Band 2" },
  "Stoerung": { addr: "%Q7.3", type: "Bool", comment: "Störung Zelle" },
  "Stoerung_Band": { addr: "%IW108", type: "Int", comment: "Nummer des gestörten Bandes" },
  "Stopp": { addr: "%I5.3", type: "Bool", comment: "Taster Stopp" },
  "Stopp_Flanke": { addr: "IEC-Instanz", type: "R_TRIG", comment: "Flanke Stopptaster (R_TRIG)" },
  "Stopp_Taster": { addr: "%I5.4", type: "Bool", comment: "Taster Stopp" },
  "Stueckzahl": { addr: "%MD300", type: "DInt", comment: "Stückzahl gezählte Teile" },
  "Summe": { addr: "%MD304", type: "Real", comment: "Summe der Werte" },
  "Tagesproduktion": { addr: "%MD308", type: "DInt", comment: "Tagesproduktion in Teilen" },
  "Takt": { addr: "IEC-Instanz", type: "TON", comment: "Taktgeber Blinker (TON)" },
  "Tara": { addr: "%IW110", type: "Int", comment: "Taragewicht Behälter in g" },
  "Taster": { addr: "%I5.5", type: "Bool", comment: "Bedientaster" },
  "Taster_Links": { addr: "%I5.6", type: "Bool", comment: "Not-Halt-Taster links" },
  "Taster_Minus": { addr: "%I5.7", type: "Bool", comment: "Taster Sollwert minus" },
  "Taster_Plus": { addr: "%I6.0", type: "Bool", comment: "Taster Sollwert plus" },
  "Taster_Rechts": { addr: "%I6.1", type: "Bool", comment: "Not-Halt-Taster rechts" },
  "Taster_Trigger": { addr: "IEC-Instanz", type: "R_TRIG", comment: "Flanke Bedientaster (R_TRIG)" },
  "Teil_Abgelegt": { addr: "%Q7.4", type: "Bool", comment: "Meldung Teil abgelegt" },
  "Teil_da": { addr: "%I6.2", type: "Bool", comment: "Teil an Station" },
  "Teil_Da": { addr: "%I6.3", type: "Bool", comment: "Teil an Klebestation" },
  "Teil_Erkannt": { addr: "%I6.4", type: "Bool", comment: "Lichtschranke Teil erkannt" },
  "Teil_Gewicht": { addr: "%MD312", type: "Real", comment: "Teilegewicht in g" },
  "Teil_Gut": { addr: "%I6.5", type: "Bool", comment: "Teil gut" },
  "Teil_Nr": { addr: "%MD316", type: "DInt", comment: "Teilenummer" },
  "Teil_OK": { addr: "%I6.6", type: "Bool", comment: "Teil in Ordnung" },
  "Teil_Sensor": { addr: "%I6.7", type: "Bool", comment: "Teilesensor" },
  "Teil_Trigger": { addr: "IEC-Instanz", type: "R_TRIG", comment: "Flanke Lichtschranke Teil (R_TRIG)" },
  "Teil_Typ": { addr: "%IW112", type: "Int", comment: "Teiletyp (1 = gut, 2 = Ausschuss)" },
  "Teil_Weg": { addr: "%I7.0", type: "Bool", comment: "Teil hat Lichtschranke verlassen" },
  "Teile": { addr: "%QW152", type: "Int", comment: "Anzahl Teile" },
  "Teile_Anzahl": { addr: "%QW154", type: "Int", comment: "Anzahl Teile auf Palette" },
  "Teile_Bereit": { addr: "%I7.1", type: "Bool", comment: "Alle Teileplätze belegt" },
  "Teile_Defekt": { addr: "%IW114", type: "Int", comment: "Anzahl defekte Teile" },
  "Teile_Geprueft": { addr: "\"Daten\".Teile_Geprueft", type: "Array", comment: "Prüfstatus je Teil (TRUE = geprüft)" },
  "Teile_Gesamt": { addr: "%IW116", type: "Int", comment: "Anzahl Teile gesamt" },
  "Teile_Gewichte": { addr: "\"Daten\".Teile_Gewichte", type: "Array", comment: "Gewichte der Teile in g" },
  "Teile_Nr": { addr: "%QW156", type: "Int", comment: "Laufende Teilenummer" },
  "Teile_OK": { addr: "\"Daten\".Teile_OK", type: "Array", comment: "Prüfergebnis je Teil (TRUE = gut)" },
  "Teile_Sensoren": { addr: "\"Daten\".Teile_Sensoren", type: "Array", comment: "Sensoren der Teileplätze" },
  "Teile_Zaehler": { addr: "%QW158", type: "Int", comment: "Anzahl geprüfte Teile" },
  "Temp": { addr: "%MD320", type: "Real", comment: "Temperatur bzw. Zwischenspeicher" },
  "Temp_Ist": { addr: "%MD324", type: "Real", comment: "Isttemperatur in °C" },
  "Temp1": { addr: "%IW118", type: "Int", comment: "Temperatur Messstelle 1 in °C" },
  "Temp2": { addr: "%IW120", type: "Int", comment: "Temperatur Messstelle 2 in °C" },
  "Temp3": { addr: "%IW122", type: "Int", comment: "Temperatur Messstelle 3 in °C" },
  "Temperatur": { addr: "%MD328", type: "Real", comment: "Temperatur in °C" },
  "Toleranz_Fehler": { addr: "%Q7.5", type: "Bool", comment: "Abweichung ausserhalb Toleranz" },
  "Transport_Timer": { addr: "IEC-Instanz", type: "TON", comment: "Transportzeit (TON)" },
  "Tuer_1_Offen": { addr: "%I7.2", type: "Bool", comment: "Schutztür 1 offen" },
  "Tuer_2_Offen": { addr: "%I7.3", type: "Bool", comment: "Schutztür 2 offen" },
  "Tuer_Zu": { addr: "%I7.4", type: "Bool", comment: "Schutztür geschlossen" },
  "Typ": { addr: "%MD332", type: "STRING[1]", comment: "Teiletyp aus Barcode" },
  "Uebernehmen": { addr: "%I7.5", type: "Bool", comment: "Taster Teil übernehmen" },
  "Ueberwachung": { addr: "IEC-Instanz", type: "TON", comment: "Überwachungszeit Greifer (TON)" },
  "Umrichter_Befehl": { addr: "%QW160", type: "Word", comment: "Steuerwort an Umrichter" },
  "Umrichter_Status": { addr: "%IW124", type: "Word", comment: "Statuswort vom Umrichter" },
  "Variante": { addr: "%MD336", type: "STRING[1]", comment: "Variante aus Barcode" },
  "Ventil_Auf": { addr: "%Q7.6", type: "Bool", comment: "Ventil öffnen" },
  "Voll_1": { addr: "%Q7.7", type: "Bool", comment: "Sollmenge erreicht Band 1" },
  "Waage": { addr: "%MD340", type: "Real", comment: "Gewicht Waage in g" },
  "Waage_Alarm": { addr: "%Q8.0", type: "Bool", comment: "Alarm Teil zu schwer" },
  "Waage_Anzeige": { addr: "%MD344", type: "Real", comment: "Anzeige Waage in g" },
  "Waage_Gewicht": { addr: "%MD348", type: "Real", comment: "Gewicht von der Waage in g" },
  "Warnung": { addr: "%Q8.1", type: "Bool", comment: "Warnmeldung" },
  "Wartung": { addr: "%Q8.2", type: "Bool", comment: "Wartung (Anlage in Wartung bzw. fällig)" },
  "Wartung_faellig": { addr: "%I7.6", type: "Bool", comment: "Wartung fällig" },
  "Weg_Frei": { addr: "%I7.7", type: "Bool", comment: "Fahrweg Arm frei" },
  "Weg_Trigger": { addr: "IEC-Instanz", type: "F_TRIG", comment: "Fallende Flanke Lichtschranke (F_TRIG)" },
  "Weiche_Pos": { addr: "%QW162", type: "Int", comment: "Stellung Weiche in Grad" },
  "Weiche_Winkel": { addr: "%QW164", type: "Int", comment: "Winkel Weiche in Grad" },
  "Weiter": { addr: "%Q8.3", type: "Bool", comment: "Teil weitertransportieren" },
  "Wert_A": { addr: "%IW126", type: "Int", comment: "Messwert A" },
  "Wert_B": { addr: "%IW128", type: "Int", comment: "Messwert B" },
  "Wert1": { addr: "%IW130", type: "Int", comment: "Wert 1" },
  "Wert2": { addr: "%IW132", type: "Int", comment: "Wert 2" },
  "Wert3": { addr: "%IW134", type: "Int", comment: "Wert 3" },
  "WS_Auto": { addr: "%I8.0", type: "Bool", comment: "Wahlschalter Automatik" },
  "WS_Hand": { addr: "%I8.1", type: "Bool", comment: "Wahlschalter Hand" },
  "Zaehler": { addr: "IEC-Instanz", type: "CTU", comment: "Teilezähler" },
  "Zaun_Offen": { addr: "%I8.2", type: "Bool", comment: "Schutzzaun offen" },
  "Zelle_Sicher": { addr: "%I8.3", type: "Bool", comment: "Zelle sicher (Schutzkreis geschlossen)" },
  "Zellen_Zustand": { addr: "%QW166", type: "Int", comment: "Zustand Zelle (Nummer)" },
  "Zustand": { addr: "%QW168", type: "Int", comment: "Zustand Zelle (Nummer)" },
  "Zyklen": { addr: "%QW170", type: "Int", comment: "Arbeitszyklen seit Reinigung" }
};
})(typeof window !== 'undefined' ? window : globalThis);
