defIO({
  Block_raus: 'Lichtschranke Blockausgang: Block ausgelaufen (TRUE)',
  Block_rein: 'Lichtschranke Ofeneingang: Block wird eingeschoben (TRUE)',
  Stueck: 'Stückzähler: Anzahl gewalzter Blöcke',
  S_Reset: 'Taster Zähler löschen (Schichtleiter)',
  S_Laden: 'Taster Charge laden',
  Rest: 'Anzeige Restmenge (offene Blöcke der Charge / Stäbe der Reihe)',
  Lampe_Gelb: 'Gelbe Signallampe (TRUE = leuchtet)',
  Lampe_Gruen: 'Grüne Signallampe (TRUE = leuchtet)',
  Lampe_Rot: 'Rote Signallampe (TRUE = leuchtet)',
  Vorwahl: 'Chargengrösse: Vorwahl vom Leitstand (Anzahl Blöcke)',
  Im_Ofen: 'Anzeige: Anzahl Blöcke im Ofen',
  S_Start: 'Start-Taster gedrückt',
  S_Stopp: 'Stopp-Taster gedrückt',
  Ofen_voll: 'Meldelampe Ofen voll (TRUE = kein Platz frei)',
  S_Schicht: 'Taster Schichtbeginn',
  S_Quit: 'Taster Quittieren',
  Charge_aktiv: 'Merker: Charge läuft, noch nicht quittiert',
  Tag: 'Tageszähler: Anzahl gewalzter Blöcke heute',
  Hupe: 'Hupe (TRUE = hupt)',
  Temp: 'Ofentemperatur in °C (Messwert)',
  Anzeige: 'Grosse Anzeige am Leitstand (Zahlenwert)',
  Temp_Soll: 'Sollwert der Ofentemperatur in °C',
  Spalt_Soll: 'Sollwert des Walzspalts in mm',
  Spalt: 'Gemessener Walzspalt in mm',
  Walzkraft: 'Gemessene Walzkraft des letzten Blocks',
  Laenge: 'Gemessene Blocklänge',
  Stiche: 'Anzahl Stiche des Blocks',
  Dicke_ein: 'Blockdicke vor dem Stich in mm',
  Dicke_aus: 'Blockdicke nach dem Stich in mm',
  Fuehler_1: 'Temperaturfühler 1 (misst in Wahrheit den Ofenausgang)',
  Fuehler_2: 'Temperaturfühler 2 (misst in Wahrheit den Ofeneingang)',
  Temp_Ein: 'Temperatur am Ofeneingang in °C',
  Temp_Aus: 'Temperatur am Ofenausgang in °C',
  Nachlauf: 'Nachlaufzeit der Kühlung (TIME)',
  S_Spalt: 'Taster Anzeige Walzspalt',
  Mess_A: 'Messeingang A (Rohwert)',
  Mess_B: 'Messeingang B (Rohwert)',
  Kraft: 'Walzkraft für die Anzeige',
  Laenge_1: 'Länge Stück 1 nach dem Schnitt in mm',
  Laenge_2: 'Länge Stück 2 nach dem Schnitt in mm',
  Gesamt: 'Gesamtlänge der Stücke in mm',
  Abnahme: 'Stichabnahme: Dickenunterschied in mm',
  Breite: 'Blockbreite in mm',
  Dicke: 'Blockdicke in mm',
  Flaeche: 'Querschnitt des Blocks (Breite mal Dicke)',
  Staebe: 'Anzahl Stäbe auf dem Kühlbett',
  Reihen: 'Anzahl voller Reihen auf dem Kühlbett (je 8 Stäbe)',
  Temp_1: 'Temperatur Fühler 1 am Ofenausgang in °C',
  Temp_2: 'Temperatur Fühler 2 am Ofenausgang in °C',
  Mittel: 'Mittelwert der Ofentemperatur in °C (REAL)',
  Laenge_mm: 'Blocklänge in mm (REAL)',
  Zoll: 'Blocklänge in Zoll, gerundet (INT)',
  Weg: 'Zurückgelegter Weg auf dem Rollgang in m',
  Zeit: 'Benötigte Zeit für den Weg in s',
  Tempo: 'Durchschnittsgeschwindigkeit des Rollgangs in m/s (REAL)',
  Dicke_3: 'Blockdicke nach dem dritten Stich (INT)',
  Temp_OK: 'Temperatur im zulässigen Bereich',
  Druck: 'Hydraulikdruck in bar',
  Charge_fertig: 'Charge komplett (TRUE = fertig)',
  S_Walzen: 'Taster Walzen gedrückt',
  Walzen: 'Walzgerüst läuft (TRUE = Freigabe erteilt)',
  Warnung: 'Gelbe Warnlampe (TRUE = leuchtet)',
  Spalt_Ist: 'Istwert des Walzspalts in mm',
  Regler_aktiv: 'Spaltregelung arbeitet (gelbe Lampe)',
  Heizung: 'Ofenheizung (TRUE = ein)',
  Wahl_Spalt: 'Wahlschalter Anzeige: 1 = Walzspalt, 0 = Temperatur',
  S_Temp: 'Taster Anzeige Temperatur',
  M_Block: 'Flankenmerker der Lichtschranke Blockausgang',
  Not_Aus_OK: 'Not-Aus-Kreis in Ordnung (TRUE = kein Not-Aus)',
  S_Rollgang: 'Taster Rollgang ein',
  Rollgang: 'Rollgang läuft',
  Pro_Platz: 'Anzahl Stäbe pro Kühlbettplatz',
  Zaehler: 'Hilfsvariable: Schleifenzähler',
  Summe: 'Gesamtzahl der Stäbe auf dem Kühlbett',
  Betriebsart: 'Wahlschalter Betriebsart (1 Hand, 2 Halbauto, 3 Auto)',
  Lampe_Hand: 'Lampe Betriebsart Hand (TRUE = leuchtet)',
  Lampe_Halb: 'Lampe Betriebsart Halbautomatik (TRUE = leuchtet)',
  Lampe_Auto: 'Lampe Betriebsart Automatik (TRUE = leuchtet)',
  Wartung: 'Wartungsbetrieb aktiv',
  Block_da: 'Sensor: Block liegt auf dem Rollgang',
  Wahl_Stueck: 'Wahlschalter Anzeige: 1 = Stückzahl, 0 = Temperatur',
  Pumpe: 'Hydraulikpumpe läuft'
});
