defIO({
  S_Walzen_1: 'Taster Walzen Gerüst 1 gedrückt',
  Gitter_1: 'Schutzgitter Gerüst 1 geschlossen',
  Oel_OK: 'Ölstand im Tank in Ordnung',
  Walzen_1: 'Walzen-Befehl Gerüst 1 (Freigabe erteilt)',
  Temp: 'Ofentemperatur in °C (Messwert)',
  Temp_OK: 'Temperatur im zulässigen Bereich',
  S_Walzen_2: 'Taster Walzen Gerüst 2 gedrückt',
  Gitter_2: 'Schutzgitter Gerüst 2 geschlossen',
  Walzen_2: 'Walzen-Befehl Gerüst 2 (Freigabe erteilt)',
  Dicke_ein: 'Blockdicke vor dem Stich in mm',
  Dicke_aus: 'Blockdicke nach dem Stich in mm',
  Abnahme: 'Stichabnahme: Dickenunterschied in mm',
  Fuehler_1: 'Temperaturfühler 1 (misst in Wahrheit den Ofenausgang)',
  Fuehler_2: 'Temperaturfühler 2 (misst in Wahrheit den Ofeneingang)',
  Lampe_Gelb: 'Gelbe Signallampe (TRUE = leuchtet)',
  Stoerung: 'Störung steht an bzw. ist gespeichert',
  Walzen: 'Walzgerüst läuft (TRUE = Freigabe erteilt)',
  Lampe_Rot: 'Rote Signallampe (TRUE = leuchtet)',
  Lampe_Gruen: 'Grüne Signallampe (TRUE = leuchtet)',
  S_Walzen: 'Taster Walzen gedrückt',
  Gitter_zu: 'Schutzgitter geschlossen',
  S_Start: 'Start-Taster gedrückt',
  S_Stopp: 'Stopp-Taster gedrückt',
  Rollgang: 'Rollgang läuft',
  Druck_tief: 'Öldruck zu tief',
  Quittieren: 'Quittiertaste (gedrückt = 1)',
  S_Rollgang_Ein: 'Taster Rollgang Ein',
  S_Rollgang_Aus: 'Taster Rollgang Aus',
  S_Pumpe_Ein: 'Taster Hydraulikpumpe Ein',
  S_Pumpe_Aus: 'Taster Hydraulikpumpe Aus',
  Pumpe: 'Hydraulikpumpe läuft',
  Block_raus: 'Lichtschranke Blockausgang: Block ausgelaufen (TRUE)',
  S_Reset: 'Taster Zähler löschen (Schichtleiter)',
  Stueck: 'Stückzähler: Anzahl gewalzter Blöcke',
  Kuehlung: 'Kühlwasser der Walzen läuft',
  Schuetz_RM: 'Hilfskontakt Rollgang-Schütz: Motor hat angezogen',
  S1: 'Taster Rollgang Ein',
  S2: 'Taster Rollgang Aus',
  S3: 'Taster Walzen Ein',
  S4: 'Taster Walzen Aus',
  Druck_da: 'Hydraulikdruck vorhanden',
  Druck_OK: 'Öldruck in Ordnung',
  Spalt_Soll: 'Sollwert des Walzspalts in mm',
  G1_bereit: 'Gerüst 1 ist betriebsbereit',
  M_Block: 'Flankenmerker der Lichtschranke Blockausgang',
  Spalt: 'Gemessener Walzspalt in mm',
  Nr: 'Stichnummer vom Leitstand (1 bis 3)',
  Tempo_Soll: 'Sollwert der Walzgeschwindigkeit',
  S_Rollgang: 'Taster Rollgang ein',
  Not_Aus_OK: 'Not-Aus-Kreis in Ordnung (TRUE = kein Not-Aus)',
  Rollgang_RM: 'Rückmeldung: Rollgang-Motor läuft',
  S_Vor: 'Taster Rollgang vorwärts (gedrückt = 1)',
  S_Rueck: 'Taster Rollgang rückwärts (gedrückt = 1)',
  S_Halt: 'Halt-Taster (gedrückt = 1)',
  Rueckwaerts: 'Rollgang-Richtung rückwärts gewählt',
  Heizung: 'Ofenheizung (TRUE = ein)',
  Not_Aus_Halle_2: 'Not-Aus-Kreis der Halle 2 in Ordnung',
  Walzen_RM: 'Rückmeldung: Walzenmotor läuft',
  Automatik: 'Betriebsart Automatik gewählt',
  S_Tippen: 'Tipptaster Rollgang (gedrückt = 1)',
  Ablauf_Rollgang: 'Befehl Rollgang aus dem Ablauf (Automatik)',
  Block_1: 'Melder Block Walzlinie 1 durchgelaufen',
  Block_2: 'Melder Block Walzlinie 2 durchgelaufen',
  Oeldruck_tief: 'Meldung Öldruck zu tief',
  Wasser_fehlt: 'Meldung Kühlwasser fehlt',
  Takt_1Hz: 'Blinktakt 1 Hz (Systemtakt)',
  Lampe_Oel: 'Meldelampe Öldruck am Leitstand',
  Lampe_Wasser: 'Meldelampe Kühlwasser am Leitstand',
  Tuer_zu: 'Ofentür geschlossen',
  Anzeige: 'Grosse Anzeige am Leitstand (Zahlenwert)',
  Sicher_OK: 'Sammelmeldung: alle Sicherungen in Ordnung',
  Luefter: 'Motorlüfter läuft',
  Wasser_OK: 'Kühlwasser in Ordnung',
  Anzahl: 'Anzahl aktuell anstehender Meldungen',
  Sammelstoerung: 'Sammelstörung: mindestens eine Meldung steht an',
  Block_durch: 'Melder: Block ist durch das Gerüst gelaufen',
  Lampe_Ruhe: 'Ruhelampe: Anlage in Grundstellung',
  Hupe: 'Hupe (TRUE = hupt)',
  Walzen_Befehl: 'Befehl an den Walzenantrieb aus dem Ablauf'
});
