defIO({
  S_Rollgang: 'Taster Rollgang (gedrückt = 1)',
  Rollgang: 'Rollgang läuft',
  S_Walzen: 'Taster Walzgerüst (gedrückt = 1)',
  Gitter_zu: 'Schutzgitter geschlossen',
  Walzen: 'Walzgerüst läuft',
  Freigabe: 'Anlage freigegeben',
  Oel_OK: 'Ölstand im Tank in Ordnung',
  S_Pumpe: 'Taster Hydraulikpumpe (gedrückt = 1)',
  Pumpe: 'Hydraulikpumpe läuft',
  Wasser_OK: 'Kühlwasser in Ordnung',
  S_Kuehlung: 'Taster Kühlung (gedrückt = 1)',
  Kuehlung: 'Kühlwasser der Walzen läuft',
  Lampe_Gruen: 'Grüne Lampe am Leitstand leuchtet',
  S_Schere: 'Taster Schere (gedrückt = 1)',
  Block_da: 'Lichtschranke Schere: Block vorhanden',
  Schere: 'Schere schneidet',
  S_Heizen: 'Taster Ofen heizen (gedrückt = 1)',
  Tuer_zu: 'Ofentür geschlossen',
  Ofen_Heizung: 'Heizung Stossofen an (Ausgang Kapitel 1)',
  Lampe_Gelb: 'Gelbe Lampe am Leitstand leuchtet',
  Not_Aus_OK: 'Not-Aus in Ordnung (0 = gedrückt)',
  Druck_OK: 'Öldruck in Ordnung',
  Stoerung: 'Störung steht an bzw. ist gespeichert',
  S_Hupe_Pult: 'Hupentaster am Pult (gedrückt = 1)',
  S_Hupe_Kran: 'Hupentaster am Kran (gedrückt = 1)',
  Hupe: 'Warnhupe tutet',
  Lampe_Rot: 'Rote Lampe am Leitstand leuchtet',
  Oben: 'Endschalter Schere oben',
  Unten: 'Endschalter Schere unten',
  Lage_OK: 'Lage der Schere in Ordnung',
  Hand: 'Betriebsart Hand gewählt',
  S_Tippen: 'Tipptaster Rollgang (gedrückt = 1)',
  Automatik: 'Betriebsart Automatik gewählt',
  Block_bereit: 'Block ist bereit',
  Pumpe_1: 'Kühlpumpe 1 läuft',
  Pumpe_2: 'Kühlpumpe 2 läuft',
  Speicher_1: 'Druckspeicher 1 geladen',
  Speicher_2: 'Druckspeicher 2 geladen',
  Anlage_Ein: 'Anlage eingeschaltet',
  Stoerung_1: 'Störung 1 steht an',
  Stoerung_2: 'Störung 2 steht an',
  Schuetz_vor: 'Rückmeldung Schütz vorwärts angezogen',
  Schuetz_rueck: 'Rückmeldung Schütz rückwärts angezogen',
  S_Ein: 'Ein-Taster (gedrückt = 1)',
  S_Aus: 'Aus-Taster (gedrückt = 1)',
  Fehler: 'Fehler am Walzgerüst steht an',
  Quittieren: 'Quittiertaste (gedrückt = 1)',
  Stoermeldung: 'Gespeicherte Störmeldung',
  Lampe_Hand: 'Lampe Handbetrieb leuchtet',
  Temp_erreicht: 'Solltemperatur im Ofen erreicht',
  Tuer_offen: 'Ofentür offen',
  Heizung: 'Heizung Stossofen an',
  Druck_tief: 'Öldruck zu tief',
  S_Vor: 'Taster Rollgang vorwärts (gedrückt = 1)',
  S_Rueck: 'Taster Rollgang rückwärts (gedrückt = 1)',
  S_Halt: 'Halt-Taster (gedrückt = 1)',
  Vor: 'Schütz Rollgang vorwärts (Ausgang)',
  Rueck: 'Schütz Rollgang rückwärts (Ausgang)',
  S_Start: 'Start-Taster (gedrückt = 1)',
  S_Stopp: 'Stopp-Taster (gedrückt = 1)',
  S_Schnitt: 'Schnitt-Taster (gedrückt = 1)',
  M_Schnitt: 'Flankenmerker Schnitt-Taster',
  Lichtschranke: 'Lichtschranke hinter Walzgerüst (1 = Block)',
  M_LS: 'Flankenmerker Lichtschranke',
  Signal_durch: 'Meldung Block durch (Impuls)',
  M_Kuehl: 'Flankenmerker Kühltaster',
  Block_aus_Ofen: 'Meldung Block kommt aus dem Ofen',
  M_Ofen: 'Flankenmerker Block aus Ofen',
  Block_unterwegs: 'Gespeicherte Meldung Block unterwegs',
  M_Quit: 'Flankenmerker Quittiertaste',
  S_Wasser_aus: 'Taster Wasser aus (gedrückt = 1)',
  M_Walzen: 'Flankenmerker Walzgerüst',
  M_Takt: 'Flankenmerker Zähltakt',
  Takt: 'Zähltakt für den Leitstand (Impuls)',
  S_Richtung: 'Richtungstaster Rollgang (gedrückt = 1)',
  S_Fahren: 'Fahrtaster Rollgang (gedrückt = 1)',
  M_Richtung: 'Flankenmerker Richtungstaster',
  Rueckwaerts: 'Rollgang-Richtung rückwärts gewählt',
  M_Auf: 'Flankenmerker Tür geht auf',
  M_Zu: 'Flankenmerker Tür geht zu',
  S_Hand: 'Handtaster Schnitt (gedrückt = 1)',
  Schere_unten: 'Schere ist unten',
  M_Block: 'Flankenmerker Block da',
  M_Hand: 'Flankenmerker Handtaster',
  Schneiden: 'Schnitt aktiv (gespeichert)',
  Walzen_Frei: 'Walzen freigegeben',
  S_Hupe: 'Hupentaster (gedrückt = 1)',
  Schnitt: 'Schnittimpuls',
  Anlauf: 'Anlauf läuft (gespeichert)',
  Block_angekommen: 'Block an der Lichtschranke angekommen',
  S_Tuer: 'Türtaster Ofentür (gedrückt = 1)'
});
