/* PLC-Variablen AWL Quest (Feedback-Auftrag Paket 5.2) – erzeugt mit node gen_tags.js awl, Kommentare von Hand gepflegt.
   Dieselbe Variable hat in allen Aufgaben dieselbe Adresse. Eingänge %I, Ausgänge %Q, Merker %M; Texte/Felder im DB "Daten"; Timer/Zähler als IEC-Instanz. */
(function(root){
root.PLC_TAGS = {
  "Ablauf_Rollgang": { addr: "%I0.0", type: "Bool", comment: "Rollgang-Befehl vom Automatikablauf" },
  "Abnahme": { addr: "%QW64", type: "Int", comment: "Stichabnahme in mm" },
  "Anlage_Ein": { addr: "%I0.1", type: "Bool", comment: "Anlage eingeschaltet" },
  "Anlauf": { addr: "%M10.0", type: "Bool", comment: "Anlauf läuft (Speicher)" },
  "Anzahl": { addr: "%QW66", type: "Int", comment: "Anzahl anstehender Meldungen" },
  "Anzeige": { addr: "%QW68", type: "Int", comment: "Zahlenanzeige Leitstand" },
  "Automatik": { addr: "%I0.2", type: "Bool", comment: "Betriebsart Automatik gewählt" },
  "Betriebsart": { addr: "%IW64", type: "Int", comment: "Wahlschalter Betriebsart (1 Hand, 2 Halb, 3 Auto)" },
  "Block_1": { addr: "%I0.3", type: "Bool", comment: "Lichtschranke Block Linie 1" },
  "Block_2": { addr: "%I0.4", type: "Bool", comment: "Lichtschranke Block Linie 2" },
  "Block_angekommen": { addr: "%I0.5", type: "Bool", comment: "Lichtschranke Block angekommen" },
  "Block_aus_Ofen": { addr: "%Q0.0", type: "Bool", comment: "Block tritt aus dem Ofen" },
  "Block_bereit": { addr: "%Q0.1", type: "Bool", comment: "Block bereit zum Walzen" },
  "Block_da": { addr: "%I0.6", type: "Bool", comment: "Lichtschranke Block unter der Schere" },
  "Block_durch": { addr: "%I0.7", type: "Bool", comment: "Block hat Gerüst verlassen" },
  "Block_raus": { addr: "%I1.0", type: "Bool", comment: "Lichtschranke Block läuft aus" },
  "Block_rein": { addr: "%Q0.2", type: "Bool", comment: "Block in Ofen eingeschoben" },
  "Block_unterwegs": { addr: "%Q0.3", type: "Bool", comment: "Meldung Block unterwegs" },
  "Breite": { addr: "%IW66", type: "Int", comment: "Blockbreite in mm" },
  "Charge_aktiv": { addr: "%M10.1", type: "Bool", comment: "Charge läuft (Speicher)" },
  "Charge_fertig": { addr: "%Q0.4", type: "Bool", comment: "Meldung Charge fertig" },
  "Dicke": { addr: "%IW68", type: "Int", comment: "Blockdicke in mm" },
  "Dicke_3": { addr: "%QW70", type: "Int", comment: "Dicke nach drei Stichen in mm" },
  "Dicke_aus": { addr: "%QW72", type: "Int", comment: "Dicke nach dem Stich in mm" },
  "Dicke_ein": { addr: "%IW70", type: "Int", comment: "Dicke vor dem Stich in mm" },
  "Druck": { addr: "%QW74", type: "Int", comment: "Hydraulikdruck in bar" },
  "Druck_da": { addr: "%Q0.5", type: "Bool", comment: "Hydraulikdruck aufgebaut" },
  "Druck_OK": { addr: "%I1.1", type: "Bool", comment: "Öldruck OK" },
  "Druck_tief": { addr: "%I1.2", type: "Bool", comment: "Öldruck zu tief" },
  "Fehler": { addr: "%I1.3", type: "Bool", comment: "Fehlersignal Walzgerüst" },
  "Flaeche": { addr: "%QW76", type: "Int", comment: "Querschnitt in mm²" },
  "Freigabe": { addr: "%I1.4", type: "Bool", comment: "Anlage freigegeben" },
  "Fuehler_1": { addr: "%IW72", type: "Int", comment: "Temperaturfühler 1 Ofen in °C" },
  "Fuehler_2": { addr: "%IW74", type: "Int", comment: "Temperaturfühler 2 Ofen in °C" },
  "G1_bereit": { addr: "%Q0.6", type: "Bool", comment: "Gerüst 1 bereit" },
  "Gesamt": { addr: "%QW78", type: "Int", comment: "Gesamtlänge in cm" },
  "Gitter_1": { addr: "%I1.5", type: "Bool", comment: "Schutzgitter Gerüst 1 geschlossen" },
  "Gitter_2": { addr: "%I1.6", type: "Bool", comment: "Schutzgitter Gerüst 2 geschlossen" },
  "Gitter_zu": { addr: "%I1.7", type: "Bool", comment: "Schutzgitter geschlossen" },
  "Hand": { addr: "%I2.0", type: "Bool", comment: "Betriebsart Hand gewählt" },
  "Heizung": { addr: "%Q0.7", type: "Bool", comment: "Ofenheizung ein" },
  "Hupe": { addr: "%Q1.0", type: "Bool", comment: "Warnhupe" },
  "Im_Ofen": { addr: "%QW80", type: "Int", comment: "Anzahl Blöcke im Ofen" },
  "Kraft": { addr: "%QW82", type: "Int", comment: "Kraftanzeige Leitstand" },
  "Kuehlung": { addr: "%Q1.1", type: "Bool", comment: "Kühlwasser Walzen ein" },
  "Laenge": { addr: "%MW100", type: "Int", comment: "Blocklänge" },
  "Laenge_1": { addr: "%IW76", type: "Int", comment: "Länge erstes Stück in cm" },
  "Laenge_2": { addr: "%IW78", type: "Int", comment: "Länge zweites Stück in cm" },
  "Laenge_mm": { addr: "%MD200", type: "Real", comment: "Blocklänge in mm" },
  "Lage_OK": { addr: "%I2.1", type: "Bool", comment: "Endlage Schere plausibel" },
  "Lampe_Auto": { addr: "%Q1.2", type: "Bool", comment: "Meldelampe Automatik" },
  "Lampe_Gelb": { addr: "%Q1.3", type: "Bool", comment: "Meldelampe gelb" },
  "Lampe_Gruen": { addr: "%Q1.4", type: "Bool", comment: "Meldelampe grün" },
  "Lampe_Halb": { addr: "%Q1.5", type: "Bool", comment: "Meldelampe Halbautomatik" },
  "Lampe_Hand": { addr: "%Q1.6", type: "Bool", comment: "Meldelampe Handbetrieb" },
  "Lampe_Oel": { addr: "%Q1.7", type: "Bool", comment: "Meldelampe Öldruck" },
  "Lampe_Rot": { addr: "%Q2.0", type: "Bool", comment: "Meldelampe rot" },
  "Lampe_Ruhe": { addr: "%Q2.1", type: "Bool", comment: "Meldelampe Ruhestellung" },
  "Lampe_Wasser": { addr: "%Q2.2", type: "Bool", comment: "Meldelampe Kühlwasser" },
  "Lichtschranke": { addr: "%I2.2", type: "Bool", comment: "Lichtschranke hinter dem Walzgerüst" },
  "Luefter": { addr: "%Q2.3", type: "Bool", comment: "Motorlüfter ein" },
  "M_Auf": { addr: "%M10.2", type: "Bool", comment: "Flankenmerker Tür auf" },
  "M_Block": { addr: "%M10.3", type: "Bool", comment: "Flankenmerker Block" },
  "M_Hand": { addr: "%M10.4", type: "Bool", comment: "Flankenmerker Handschnitt" },
  "M_Kuehl": { addr: "%I2.3", type: "Bool", comment: "Flankenmerker Taster Kühlung" },
  "M_LS": { addr: "%I2.4", type: "Bool", comment: "Flankenmerker Lichtschranke" },
  "M_Ofen": { addr: "%M10.5", type: "Bool", comment: "Flankenmerker Block aus Ofen" },
  "M_Quit": { addr: "%M10.6", type: "Bool", comment: "Flankenmerker Quittieren" },
  "M_Richtung": { addr: "%I2.5", type: "Bool", comment: "Flankenmerker Taster Richtung" },
  "M_Schnitt": { addr: "%M10.7", type: "Bool", comment: "Flankenmerker Schnitt" },
  "M_Takt": { addr: "%M11.0", type: "Bool", comment: "Flankenmerker Zähltakt" },
  "M_Walzen": { addr: "%M11.1", type: "Bool", comment: "Flankenmerker Walzen" },
  "M_Zu": { addr: "%M11.2", type: "Bool", comment: "Flankenmerker Tür zu" },
  "Mess_A": { addr: "%IW80", type: "Int", comment: "Messeingang A" },
  "Mess_B": { addr: "%IW82", type: "Int", comment: "Messeingang B" },
  "Mittel": { addr: "%MD204", type: "Real", comment: "Mittlere Blocktemperatur in °C" },
  "Nachlauf": { addr: "%MD208", type: "Time", comment: "Nachlaufzeit Kühlung" },
  "Not_Aus_Halle_2": { addr: "%M11.3", type: "Bool", comment: "Not-Aus-Signal Halle 2" },
  "Not_Aus_OK": { addr: "%I2.6", type: "Bool", comment: "Not-Aus nicht betätigt (Öffner)" },
  "Nr": { addr: "%QW84", type: "Int", comment: "Stichnummer vom Leitstand" },
  "Oben": { addr: "%I2.7", type: "Bool", comment: "Endschalter Schere oben" },
  "Oel_OK": { addr: "%I3.0", type: "Bool", comment: "Ölstand OK" },
  "Oeldruck_tief": { addr: "%I3.1", type: "Bool", comment: "Öldruck zu tief" },
  "Ofen_Heizung": { addr: "%Q2.4", type: "Bool", comment: "Ofenheizung ein" },
  "Ofen_voll": { addr: "%Q2.5", type: "Bool", comment: "Meldung Ofen voll" },
  "Pro_Platz": { addr: "%IW84", type: "Int", comment: "Stäbe pro Kühlbettplatz" },
  "Pumpe": { addr: "%Q2.6", type: "Bool", comment: "Hydraulikpumpe ein" },
  "Pumpe_1": { addr: "%Q2.7", type: "Bool", comment: "Kühlpumpe 1 läuft" },
  "Pumpe_2": { addr: "%Q3.0", type: "Bool", comment: "Kühlpumpe 2 läuft" },
  "Quittieren": { addr: "%I3.2", type: "Bool", comment: "Taster Quittieren" },
  "Regler_aktiv": { addr: "%Q3.1", type: "Bool", comment: "Meldung Spaltregler aktiv" },
  "Reihen": { addr: "%QW86", type: "Int", comment: "Volle Reihen auf dem Kühlbett" },
  "Rest": { addr: "%QW88", type: "Int", comment: "Restwert (Charge bzw. Division)" },
  "Rollgang": { addr: "%Q3.2", type: "Bool", comment: "Rollgang Motor ein" },
  "Rollgang_RM": { addr: "%I3.3", type: "Bool", comment: "Rückmeldung Schütz Rollgang" },
  "Rueck": { addr: "%Q3.3", type: "Bool", comment: "Schütz Rollgang rückwärts" },
  "Rueckwaerts": { addr: "%Q3.4", type: "Bool", comment: "Richtung rückwärts gewählt" },
  "S_Aus": { addr: "%I3.4", type: "Bool", comment: "Taster Aus (Schliesser)" },
  "S_Ein": { addr: "%I3.5", type: "Bool", comment: "Taster Ein (Schliesser)" },
  "S_Fahren": { addr: "%I3.6", type: "Bool", comment: "Taster Rollgang fahren" },
  "S_Halt": { addr: "%I3.7", type: "Bool", comment: "Taster Halt" },
  "S_Hand": { addr: "%I4.0", type: "Bool", comment: "Taster Schnitt von Hand" },
  "S_Heizen": { addr: "%I4.1", type: "Bool", comment: "Taster Ofen heizen" },
  "S_Hupe": { addr: "%I4.2", type: "Bool", comment: "Taster Warnhupe" },
  "S_Hupe_Kran": { addr: "%I4.3", type: "Bool", comment: "Taster Hupe am Kran" },
  "S_Hupe_Pult": { addr: "%I4.4", type: "Bool", comment: "Taster Hupe am Pult" },
  "S_Kuehlung": { addr: "%I4.5", type: "Bool", comment: "Taster Kühlung" },
  "S_Laden": { addr: "%I4.6", type: "Bool", comment: "Taster Charge laden" },
  "S_Pumpe": { addr: "%I4.7", type: "Bool", comment: "Taster Pumpe ein" },
  "S_Pumpe_Aus": { addr: "%I5.0", type: "Bool", comment: "Taster Pumpe aus" },
  "S_Pumpe_Ein": { addr: "%I5.1", type: "Bool", comment: "Taster Pumpe ein" },
  "S_Quit": { addr: "%I5.2", type: "Bool", comment: "Taster Charge quittieren" },
  "S_Reset": { addr: "%I5.3", type: "Bool", comment: "Taster Zähler löschen" },
  "S_Richtung": { addr: "%I5.4", type: "Bool", comment: "Taster Richtung wechseln" },
  "S_Rollgang": { addr: "%I5.5", type: "Bool", comment: "Taster Rollgang ein (Schliesser)" },
  "S_Rollgang_Aus": { addr: "%I5.6", type: "Bool", comment: "Taster Rollgang aus" },
  "S_Rollgang_Ein": { addr: "%I5.7", type: "Bool", comment: "Taster Rollgang ein" },
  "S_Rueck": { addr: "%I6.0", type: "Bool", comment: "Taster Rückwärts" },
  "S_Schere": { addr: "%I6.1", type: "Bool", comment: "Taster Schere" },
  "S_Schicht": { addr: "%I6.2", type: "Bool", comment: "Taster Schichtbeginn" },
  "S_Schnitt": { addr: "%I6.3", type: "Bool", comment: "Taster Schnitt" },
  "S_Spalt": { addr: "%I6.4", type: "Bool", comment: "Taster Anzeige Walzspalt" },
  "S_Start": { addr: "%I6.5", type: "Bool", comment: "Taster Start" },
  "S_Stopp": { addr: "%I6.6", type: "Bool", comment: "Taster Stopp" },
  "S_Temp": { addr: "%I6.7", type: "Bool", comment: "Taster Anzeige Temperatur" },
  "S_Tippen": { addr: "%I7.0", type: "Bool", comment: "Tipptaster Rollgang" },
  "S_Tuer": { addr: "%I7.1", type: "Bool", comment: "Taster Ofentür öffnen" },
  "S_Vor": { addr: "%I7.2", type: "Bool", comment: "Taster Vorwärts" },
  "S_Walzen": { addr: "%I7.3", type: "Bool", comment: "Taster Walzen ein" },
  "S_Walzen_1": { addr: "%I7.4", type: "Bool", comment: "Taster Walzen Gerüst 1" },
  "S_Walzen_2": { addr: "%I7.5", type: "Bool", comment: "Taster Walzen Gerüst 2" },
  "S_Wasser_aus": { addr: "%I7.6", type: "Bool", comment: "Taster Kühlwasser aus" },
  "S1": { addr: "%I7.7", type: "Bool", comment: "Taster Rollgang ein" },
  "S2": { addr: "%I8.0", type: "Bool", comment: "Taster Rollgang aus" },
  "S3": { addr: "%I8.1", type: "Bool", comment: "Taster Walzen ein" },
  "S4": { addr: "%I8.2", type: "Bool", comment: "Taster Walzen aus" },
  "Sammelstoerung": { addr: "%Q3.5", type: "Bool", comment: "Sammelstörung" },
  "Schere": { addr: "%Q3.6", type: "Bool", comment: "Schere fährt ab (Schnitt)" },
  "Schere_unten": { addr: "%I8.3", type: "Bool", comment: "Rückmeldung Schere unten" },
  "Schneiden": { addr: "%M11.4", type: "Bool", comment: "Schnitt läuft (Speicher)" },
  "Schnitt": { addr: "%I8.4", type: "Bool", comment: "Schnittbefehl (Impuls)" },
  "Schuetz_RM": { addr: "%Q3.7", type: "Bool", comment: "Hilfskontakt Schütz Rollgang" },
  "Schuetz_rueck": { addr: "%Q4.0", type: "Bool", comment: "Schütz Rollgang rückwärts angezogen" },
  "Schuetz_vor": { addr: "%Q4.1", type: "Bool", comment: "Schütz Rollgang vorwärts angezogen" },
  "Sicher_OK": { addr: "%Q4.2", type: "Bool", comment: "Sicherheitskreis OK" },
  "Signal_durch": { addr: "%Q4.3", type: "Bool", comment: "Signal Block ist durch" },
  "Spalt": { addr: "%MD212", type: "Real", comment: "Walzspalt Messwert in mm" },
  "Spalt_Ist": { addr: "%IW86", type: "Int", comment: "Walzspalt Istwert in mm" },
  "Spalt_Soll": { addr: "%QW90", type: "Int", comment: "Walzspalt Sollwert in mm" },
  "Speicher_1": { addr: "%I8.5", type: "Bool", comment: "Druckspeicher 1 geladen" },
  "Speicher_2": { addr: "%I8.6", type: "Bool", comment: "Druckspeicher 2 geladen" },
  "Staebe": { addr: "%QW92", type: "Int", comment: "Anzahl Stäbe auf dem Kühlbett" },
  "Stiche": { addr: "%MW102", type: "Int", comment: "Anzahl Stiche" },
  "Stoermeldung": { addr: "%Q4.4", type: "Bool", comment: "Störmeldung Walzgerüst" },
  "Stoerung": { addr: "%Q4.5", type: "Bool", comment: "Störung Anlage" },
  "Stoerung_1": { addr: "%Q4.6", type: "Bool", comment: "Störung 1 steht an" },
  "Stoerung_2": { addr: "%I8.7", type: "Bool", comment: "Störung 2 steht an" },
  "Stueck": { addr: "%QW94", type: "Int", comment: "Stückzahl Blöcke" },
  "Summe": { addr: "%QW96", type: "Int", comment: "Summe Stäbe" },
  "Tag": { addr: "%QW98", type: "Int", comment: "Tageszähler Blöcke" },
  "Takt": { addr: "%Q4.7", type: "Bool", comment: "Zähltakt Leitstand" },
  "Takt_1Hz": { addr: "%I9.0", type: "Bool", comment: "Blinktakt 1 Hz" },
  "Temp": { addr: "%QW100", type: "Int", comment: "Ofentemperatur in °C" },
  "Temp_1": { addr: "%QW102", type: "Int", comment: "Blocktemperatur Fühler 1 in °C" },
  "Temp_2": { addr: "%IW88", type: "Int", comment: "Blocktemperatur Fühler 2 in °C" },
  "Temp_Aus": { addr: "%QW104", type: "Int", comment: "Temperatur Ofenausgang in °C" },
  "Temp_Ein": { addr: "%QW106", type: "Int", comment: "Temperatur Ofeneingang in °C" },
  "Temp_erreicht": { addr: "%I9.1", type: "Bool", comment: "Solltemperatur erreicht" },
  "Temp_OK": { addr: "%Q5.0", type: "Bool", comment: "Temperatur ausreichend" },
  "Temp_Soll": { addr: "%QW108", type: "Int", comment: "Solltemperatur Ofen in °C" },
  "Tempo": { addr: "%MD216", type: "Real", comment: "Rollganggeschwindigkeit in m/s" },
  "Tempo_Soll": { addr: "%MW104", type: "Int", comment: "Sollgeschwindigkeit Walzen" },
  "Tuer_offen": { addr: "%Q5.1", type: "Bool", comment: "Ofentür offen" },
  "Tuer_zu": { addr: "%Q5.2", type: "Bool", comment: "Ofentür geschlossen" },
  "Unten": { addr: "%I9.2", type: "Bool", comment: "Endschalter Schere unten" },
  "Vor": { addr: "%Q5.3", type: "Bool", comment: "Schütz Rollgang vorwärts" },
  "Vorwahl": { addr: "%IW90", type: "Int", comment: "Vorwahl Chargengrösse" },
  "Wahl_Spalt": { addr: "%I9.3", type: "Bool", comment: "Wahlschalter Anzeige Walzspalt" },
  "Wahl_Stueck": { addr: "%I9.4", type: "Bool", comment: "Wahlschalter Anzeige Stückzahl" },
  "Walzen": { addr: "%Q5.4", type: "Bool", comment: "Walzenantrieb ein" },
  "Walzen_1": { addr: "%Q5.5", type: "Bool", comment: "Walzenantrieb Gerüst 1" },
  "Walzen_2": { addr: "%Q5.6", type: "Bool", comment: "Walzenantrieb Gerüst 2" },
  "Walzen_Befehl": { addr: "%Q5.7", type: "Bool", comment: "Befehl Walzen ein" },
  "Walzen_Frei": { addr: "%Q6.0", type: "Bool", comment: "Freigabe Walzen" },
  "Walzen_RM": { addr: "%I9.5", type: "Bool", comment: "Rückmeldung Schütz Walzen" },
  "Walzkraft": { addr: "%QW110", type: "Int", comment: "Walzkraft in kN" },
  "Warnung": { addr: "%Q6.1", type: "Bool", comment: "Warnlampe Walzspalt zu eng" },
  "Wartung": { addr: "%I9.6", type: "Bool", comment: "Schalter Wartungsbetrieb" },
  "Wasser_fehlt": { addr: "%M11.5", type: "Bool", comment: "Kühlwasser fehlt" },
  "Wasser_OK": { addr: "%Q6.2", type: "Bool", comment: "Kühlwasser vorhanden" },
  "Weg": { addr: "%IW92", type: "Int", comment: "Zurückgelegter Weg in m" },
  "Zaehler": { addr: "%MW106", type: "Int", comment: "Schleifenzähler" },
  "Zeit": { addr: "%IW94", type: "Int", comment: "Fahrzeit in s" },
  "Zoll": { addr: "%QW112", type: "Int", comment: "Blocklänge in Zoll" }
};
})(typeof window !== 'undefined' ? window : globalThis);
