/* ===== SENSORWERKSTATT: Glossar ===== */
(function(root){
root.SENSOR_GLOSSARY = {
  'Schaltabstand': 'Abstand, bei dem ein Näherungsschalter schaltet. Der Nennschaltabstand Sn auf dem Typenschild gilt für Stahl; andere Materialien verkürzen ihn.',
  'Reduktionsfaktor': 'Faktor, um den sich der Schaltabstand eines induktiven Sensors für ein anderes Metall verkleinert (Richtwerte: Stahl 1,0, Edelstahl 0,7, Messing 0,5, Aluminium 0,4). Die genauen Werte stehen im Datenblatt.',
  'bündig': 'Einbauart eines Näherungsschalters: Er darf bündig in Metall eingebaut werden, weil sein Feld nur nach vorne austritt. Dafür ist der Schaltabstand kleiner als bei nicht bündigen Sensoren.',
  'Funktionsreserve': 'Wie viel mehr Licht bei einem optischen Sensor ankommt, als zum Schalten nötig ist. Eine blinkende Stabilitäts-LED zeigt: Die Reserve ist knapp, ausrichten oder reinigen.',
  'Hintergrundausblendung': 'Lichttaster, der die Entfernung des Objekts auswertet und alles hinter der eingelernten Tastweite ignoriert. So wird z. B. das Band ausgeblendet, Teile darauf aber erkannt.',
  'hellschaltend': 'Der Ausgang eines optischen Sensors ist 1, wenn Licht auf den Empfänger fällt. Beim Lichttaster: Objekt da; bei der Lichtschranke: Strahl frei.',
  'dunkelschaltend': 'Der Ausgang eines optischen Sensors ist 1, wenn kein Licht auf den Empfänger fällt. Bei der Lichtschranke: Strahl unterbrochen, Objekt da.',
  'antivalent': 'Sensor mit zwei entgegengesetzten Ausgängen (NO auf BK, NC auf WH). Sind beide länger gleich, liegt ein Fehler vor, z. B. ein Drahtbruch.',
  'Live Zero': 'Der Messanfang wird nicht mit 0, sondern mit einem Wert grösser 0 übertragen, bei 4–20 mA mit 4 mA. So lässt sich „Messwert 0“ von „Drahtbruch“ unterscheiden.',
  'Messumformer': 'Gerät, das eine physikalische Grösse (Druck, Temperatur, Durchfluss) in ein Normsignal wie 4–20 mA oder 0–10 V umwandelt. Auch Transmitter genannt.',
  'Transmitter': 'Anderer Name für Messumformer. 2-Leiter-Transmitter werden über die Stromschleife versorgt, 4-Leiter-Transmitter haben eine eigene Versorgung.',
  'Bürde': 'Gesamtwiderstand in einer Stromschleife (SPS-Eingang, Leitung, Anzeiger). Sie darf nicht grösser sein, als der Transmitter oder Stromausgang laut Datenblatt treiben kann.',
  'Rohwert': 'Zahl, die die Analogbaugruppe aus dem Signal macht (Datentyp Int). Bei S7-1200/1500 entspricht der Nennbereich 0 … 27648.',
  'Nennbereich': 'Der vorgesehene Signalbereich, z. B. 4–20 mA oder 0–10 V, bei S7-1200/1500 als Rohwert 0 … 27648 dargestellt.',
  'Übersteuerung': 'Signal etwas oberhalb des Nennbereichs (Rohwert 27649 … 32511). Die Baugruppe misst noch, der Wert liegt aber ausserhalb des Messbereichs des Sensors.',
  'Schirmauflage': 'Grossflächige Verbindung des Leitungsschirms einer Analogleitung mit der Schirmschiene. Ohne sie koppeln Störungen ein und der Messwert rauscht.',
  'Querbrücker': 'Steckbrücke, die dieselbe Ebene (z. B. alle L+ oder alle M) mehrerer nebeneinanderliegender Klemmen verbindet. In der Werkstatt sind sie schon gesteckt.',
  'Initiatorenklemme': 'Mehrstockklemme für 3-Leiter-Sensoren mit den Ebenen L+ (oben), Signal (Mitte) und M (unten), oft mit LED für das Signal.',
  'Trennklemme': 'Klemme mit Trennmesser: Geöffnet unterbricht sie den Stromkreis, über Messbuchsen kann man dann in Reihe messen oder einen Kalibrator einspeisen.',
  'Loop-Check': 'Prüfung einer analogen Messkette bei der Inbetriebnahme: Kalibrator speist z. B. 4, 12 und 20 mA ein, man kontrolliert Rohwert und Anzeige (0 %, 50 %, 100 %).',
  'PNP': 'Plusschaltender Sensorausgang (sourcing): Bei Erkennung liegt +24 V auf der Signalader BK. An der S7-1200 gehört 1M dann auf M.',
  'NPN': 'Minusschaltender Sensorausgang (sinking): Bei Erkennung liegt 0 V (M) auf der Signalader BK. An der S7-1200 gehört 1M dann auf L+.',
  'Schliesser': 'Kontakt oder Sensorausgang (NO), der bei Betätigung bzw. Erkennung 1 liefert und in Ruhe 0.',
  'Öffner': 'Kontakt oder Sensorausgang (NC), der in Ruhe 1 und bei Betätigung 0 liefert. Drahtbruchsicher: Ein Bruch wirkt wie „betätigt“.',
  '1M': 'Bezugsanschluss einer Eingangsgruppe der S7-1200. Auf M gelegt für PNP-Sensoren (Eingang stromziehend), auf L+ für NPN-Sensoren (Eingang stromliefernd).',
  'Prozessabbild': 'Speicherbereich der CPU, in den sie zu Beginn jedes Zyklus alle Eingänge einliest und aus dem sie am Zyklusende alle Ausgänge schreibt. Das Programm arbeitet mit diesem Abbild.',
  'Untersteuerung': 'Signal etwas unterhalb des Nennbereichs, bei 4–20 mA zwischen ca. 1,185 und 4 mA (Rohwert −1 … −4864). Noch gemessen, aber unter dem Messbereich des Sensors.',
  'Überlauf': 'Signal weit über dem Messbereich. Die Baugruppe liefert den Sonderwert 32767 (16#7FFF), der Messwert ist ungültig.',
  'Drahtbruchdiagnose': 'Kanalweise freischaltbare Diagnose bei 4–20 mA: Fliesst kaum noch Strom, meldet der Kanal einen Sonderwert und einen Eintrag im Diagnosepuffer.',
  'Glättung': 'Filter der Analogbaugruppe (keine/schwach/mittel/stark), der den Messwert über mehrere Zyklen mittelt. Ruhiger, aber träger.',
  'Offset': 'Konstanter Fehler oder Anfangswert einer Geraden: der Wert beim Rohwert 0. Ein Nullpunktfehler wird durch Abziehen des Offsets korrigiert.',
  'Hysterese': 'Abstand zwischen Ein- und Ausschaltpunkt. Verhindert, dass ein Ausgang an einer Grenze flattert.',
  'NORM_X': 'Anweisung, die einen Wert zwischen MIN und MAX auf 0,0 … 1,0 abbildet (Ergebnis Real). Typisch für Rohwert → Anteil.',
  'SCALE_X': 'Anweisung, die einen Anteil 0,0 … 1,0 auf den Bereich MIN … MAX abbildet. Typisch für Anteil → physikalischer Wert oder → Rohwert der Analogausgabe.',
  'Kalibrator': 'Messgerät, das einen genau einstellbaren Strom (z. B. 0–24 mA) einspeist. Damit prüft man eine Analogkette ohne echten Sensor (Loop-Check).',
  'M12': 'Genormter Rundsteckverbinder mit Gewinde M12 für Sensoren, meist 4-polig A-codiert: 1 BN = L+, 2 WH, 3 BU = M, 4 BK = Signal.'
};
})(typeof window !== 'undefined' ? window : globalThis);
