/* Sensorwerkstatt: Texte der 30 angezeigten Aufgaben nach der Textdiät (Umbau 29.09.2026, Paket W7).
   story ≤ 2 Sätze, brief (Auftrag) ≤ 25 Wörter und zuoberst, info = Infokarte (max. 3 Sätze, Tabellen/Listen erlaubt) direkt in der Aufgabe.
   Mechanik (Montage, Stecker, Hülsen, Einschalten, Laden) macht das Spiel; Texte nennen keine Werkzeughandlungen mehr.
   Die bisherigen Texte in m1.js … m6.js bleiben für die versteckten Aufgaben und als Verlauf. */
(function(root){
const C = root.SCL_CONTENT;
const T = {
  // Modul 1
  w1_b1_anschliessen: { story: 'ARIA hat die Adern von -B1 abgeklemmt. Die Sortierstrecke erkennt kein Metall mehr.',
    brief: 'Lege die drei Adern von <b>-B1</b> auf die Initiatorenklemme <b>-X2:5</b>. Dann Laufen lassen und ein Stahlteil vorbeiführen.',
    info: '<b>Farbe = Aufgabe:</b> BN (braun) = +24 V → L+, BU (blau) = 0 V → M, BK (schwarz) = Signal → S. Die Signalebene von -X2:5 führt zum Eingang %I0.4.' },
  w1_start_stopp: { story: 'Am Bedienpult fehlen die Adern von Start und Stopp. Stopp ist ein Öffner.',
    brief: 'Schliesse <b>-S1</b> Start an <b>-X2:1</b> und <b>-S2</b> Stopp an <b>-X2:2</b> an. Beantworte danach die zwei Fragen.',
    info: 'Taster haben zwei Kontakte: der erste kommt auf L+, der zweite auf die Signalebene. Ein <b>Schliesser</b> (13/14) meldet 1 beim Drücken, ein <b>Öffner</b> (11/12) meldet 1 in Ruhe.' },
  w1_variablentabelle: { story: 'ARIA hat die PLC-Variablentabelle gelöscht. Ohne Namen weiss niemand, was %I0.4 bedeutet.',
    brief: 'Lege im Fenster <b>PLC-Variablen</b> die sechs Variablen aus der Infokarte an: Name, Datentyp Bool, Adresse.',
    info: '<table class="sv-info-t"><tr><th>Name</th><th>Adresse</th></tr><tr><td>Start</td><td>%I0.0</td></tr><tr><td>Stopp</td><td>%I0.1</td></tr><tr><td>Ind_Metall</td><td>%I0.4</td></tr><tr><td>Rutsche_Voll</td><td>%I1.0</td></tr><tr><td>Haube_Zu</td><td>%I1.3</td></tr><tr><td>Band</td><td>%Q0.0</td></tr></table>' },
  w1_band_selbsthaltung: { story: 'Die Sortierstrecke ist verdrahtet, jetzt braucht das Band ein Programm. ARIA wettet, dass du den Öffner falsch auswertest.',
    brief: '<b>"Band"</b> startet mit <b>"Start"</b> und hält sich selbst. <b>"Stopp"</b> (Öffner) oder offene Haube schalten es aus.',
    info: 'Selbsthaltung: Band := (Start ODER Band) UND Stopp UND Haube_Zu. Weil Stopp ein Öffner ist, ist <b>"Stopp" = 1</b>, solange niemand drückt.' },
  w1_boss_sortierstrecke: { story: 'ARIA hat die Sortierstrecke zerlegt: Adern gezogen, Querbrücker weg, Programm gelöscht. Bis Schichtende soll das Band wieder laufen.',
    brief: 'Verdrahte fünf Geräte, lege die Variablen an und programmiere das Band mit Selbsthaltung. Volle Rutsche stoppt es.',
    info: '-S1 → -X2:1, -S2 → -X2:2, -B1 → -X2:5, -B5 → -X2:9, -S5 → -X2:12. Variablen: Start, Stopp, Ind_Metall, Rutsche_Voll, Haube_Zu, Band. Aus bei Stopp, offener Haube oder "Rutsche_Voll" = 1.' },
  // Modul 2
  w2_pnp_messen: { story: 'Der Werkmeister drückt dir das Multimeter in die Hand. „Glauben ist gut, messen ist besser.“',
    brief: 'Miss mit dem Multimeter die Spannung zwischen <b>-X2:5 Signal</b> und <b>-X2:5 M</b>, mit und ohne Stahlteil vor -B1.',
    info: 'Rote Spitze auf das Signal, schwarze Spitze (COM) auf M. Ein <b>PNP</b>-Sensor schaltet beim Erkennen +24 V auf seinen Ausgang.' },
  w2_1m_cpu: { story: 'Die Sensor-LEDs leuchten, doch die Eingänge der CPU bleiben dunkel. Ein Aushilfselektriker hat 1M auf L+ gelegt.',
    brief: 'Klemme <b>-A1:1M</b> von L+ auf M um. Danach müssen %I0.4, %I1.0 und %I0.0 wieder kommen.',
    info: '1M ist das Bezugspotential der Eingangsgruppe. Bei PNP-Sensoren muss 1M auf <b>M</b> liegen, damit Strom vom Signal durch den Eingang nach M fliesst.' },
  w2_teilezaehler: { story: 'Die Produktion will wissen, wie viele Metallteile heute gelaufen sind. ARIA zählt 4 872 Teile in zehn Sekunden.',
    brief: 'Zähle jedes Metallteil an <b>"Ind_Metall"</b> genau einmal in <b>"Teile_Anzahl"</b>. <b>"HMI_Reset"</b> setzt auf 0.',
    info: 'Ein Teil liegt mehrere Zyklen vor dem Sensor – ohne <b>Flanke</b> zählt es in jedem Zyklus. SCL: Instanz "Flanke_B1" (R_TRIG), FUP: P(…).' },
  w2_fehler_npn_pnp: { story: 'Ein Kollege hat den NPN-Sensor -N1 an die SM 1221 angeschlossen. Die LED am Sensor leuchtet, %I16.0 bleibt 0.',
    brief: 'Finde heraus, warum %I16.0 nicht kommt, und behebe es. -B8 an %I16.4 muss weiter funktionieren.',
    info: 'Ein <b>NPN</b>-Sensor schaltet den Ausgang nach M. Die Eingangsgruppe braucht dann ihr Bezugspotential (1M bzw. 2M) auf <b>L+</b> – und PNP und NPN gehören nie in dieselbe Gruppe.' },
  w2_boss_umbau: { story: 'Am Auswerfer sitzt künftig ein NPN-Sensor, und ARIA hat alle Sensoradern gezogen. „PNP an die CPU, NPN an die SM 1221“, sagt der Werkmeister.',
    brief: 'Verdrahte drei PNP-Sensoren an die CPU und -N1 an die SM 1221. Der Auswerfer reagiert dann auf "Ind_Auswerfer".',
    info: '-B1 → -X2:5, -B2 → -X2:6, -B5 → -X2:9, -N1 → -X2:21 (%I16.0), 1M der SM 1221 auf L+. Variable Ind_Auswerfer (Bool, %I16.0). Auswerfen nur bei laufendem Band; volle Rutsche stoppt das Band und schaltet "Lampe_Rot".' },
  // Modul 3
  w3_schaltabstand: { story: 'Das Typenschild von -B1 sagt Sn 8 mm. Für welches Material gilt das?',
    brief: 'Schiebe den Abstandsregler von -B1, bis die LED ausgeht, und notiere den Schaltabstand für Stahl und Aluminium. Zum Schluss 4 mm.',
    info: 'Der letzte Abstand, bei dem die gelbe LED noch leuchtet, ist der Schaltabstand. Nichteisenmetalle haben einen <b>Reduktionsfaktor</b>: Aluminium wird nur auf kürzere Distanz erkannt.' },
  w3_b3_teach: { story: 'Der Lichttaster -B3 sieht seit ARIAs Besuch das Band selbst als Teil. Er muss den Hintergrund neu lernen.',
    brief: 'Stelle -B3 auf <b>60 mm</b> über dem Band, drücke bei leerem Band <b>Teach-in</b> und prüfe mit einem schwarzen Teil.',
    info: 'Ein Lichttaster mit <b>Hintergrundausblendung</b> ignoriert alles, was weiter weg ist als die eingelernte Distanz. Deshalb lernt man bei leerem Band: der Hintergrund ist das Band.' },
  w3_materialsortierung: { story: 'Metall soll in Rutsche A, Kunststoff in Behälter B. -B1 sitzt aber weit vor dem Auswerfer.',
    brief: 'Merke dir ein Metallteil in <b>"Ist_Metall"</b> und wirf es bei <b>"LS_Band"</b> aus. <b>"Zyl_Vorne"</b> löscht die Merkung.',
    info: '"Ind_Metall" → Setzen "Ist_Metall"; "LS_Band" UND "Ist_Metall" → "Auswerfer"; "Zyl_Vorne" → Rücksetzen "Ist_Metall". Kunststoff läuft durch in Behälter B.' },
  w3_fehler_alu: { story: 'Aluminiumteile landen im Kunststoffbehälter, Stahl wird sauber aussortiert. ARIA: „Metall ist Metall, oder?“',
    brief: 'Finde heraus, warum -B1 Aluminium nicht erkennt, und stelle den Abstand so ein, dass alle Metalle sicher schalten.',
    info: 'Aluminium hat beim induktiven Sensor einen Reduktionsfaktor von etwa 0,4. Der sichere Einbauabstand richtet sich nach dem <b>ungünstigsten</b> Material.' },
  w3_boss_sieben: { story: 'Grossauftrag mit sieben Werkstoffen, und ARIA hat alle Sensoren verstellt. Glas gehört nicht auf diese Strecke und soll gemeldet werden.',
    brief: 'Stelle -B1 und -B2 richtig ein, fülle die Logiktabelle und programmiere <b>"Teil_Art"</b>: Metall auswerfen, Glas melden.',
    info: '-B1 induktiv ("Ind_Metall"), -B2 kapazitiv ("Kap_Teil", Kunststoff ja, Band nein), -B4 Lichtschranke ("LS_Band"). "Teil_Art": 0 kein Teil, 1 Metall, 2 Kunststoff, 3 Glas → "Lampe_Rot".' },
  // Modul 4
  w4_b10_anschliessen: { story: 'Über dem Tank hängt der Ultraschallsensor -B10, ohne Anschluss. Ab jetzt sind Signale nicht mehr nur 0 oder 1.',
    brief: 'Schliesse <b>-B10</b> (0–10 V) an den Analogeingang AI0 der CPU an und miss die Spannung bei drei Füllständen.',
    info: 'BN → -X1:L+6, BU → -X1:M5, BK → -X3:4 (a), -X3:4 (b) → -A1:AI0, -A1:2M → -X1:M6. Füllstand = 800 mm − Abstand; den Füllstand stellst du mit dem Regler in ④ ein.' },
  w4_b11_2leiter: { story: 'Der Drucktransmitter -B11 hat nur zwei Adern. „Der Strom ist das Signal“, grinst der Werkmeister.',
    brief: 'Verdrahte die <b>2-Leiter-Schleife</b> von -B11 an Kanal 0 der SM 1231 und stelle den Kanal auf 4–20 mA ein.',
    info: '-X1:L+2 → B11:+, B11:− → -X3:1 (a), -X3:1 (b) → -A2:0+, -A2:0− → -X1:M7. Gerätesicht Kanal 0: Strom 2-Draht, 4–20 mA, Drahtbruch ein.' },
  w4_loopcheck: { story: 'Vor der Inbetriebnahme wird jeder Kanal abgenommen. „12 mA am Klemmenkasten müssen 12 mA in der SPS sein.“',
    brief: 'Speise mit dem <b>Kalibrator</b> 4, 12 und 20 mA in Kanal 1 ein und notiere jeweils "Temp_Roh".',
    info: 'Das Trennmesser -X3:2 ist offen, der Transmitter also abgetrennt. Kalibrator an Kanal 1 anklemmen, Wert wählen, Rohwert in der Beobachtung ablesen.' },
  w4_rohwert_status: { story: 'ARIA will bei Drahtbruch einfach 118 mbar anzeigen. Der Werkmeister will jeden ungültigen Rohwert gemeldet haben.',
    brief: 'Schreibe den Status von <b>"Druck_Roh"</b> in <b>"Druck_Status"</b> (0–4). Bei Status 3 oder 4 leuchtet "Lampe_Rot".',
    info: '<table class="sv-info-t"><tr><th>Rohwert</th><th>Status</th></tr><tr><td>0 … 27648</td><td>0 in Ordnung</td></tr><tr><td>27649 … 32511</td><td>1 Übersteuerung</td></tr><tr><td>−4864 … −1</td><td>2 Untersteuerung</td></tr><tr><td>32767</td><td>3 Überlauf / Drahtbruch</td></tr><tr><td>−32768</td><td>4 Unterlauf</td></tr></table>' },
  w4_boss_tank: { story: 'ARIA hat an der Tankstation alle Analogleitungen gezogen. Vier Messstellen werden angeschlossen, konfiguriert und abgenommen.',
    brief: 'Schliesse -B10 bis -B13 an, konfiguriere die SM 1231 und trage die Rohwerte der Abnahme ins Protokoll ein.',
    info: '-B10 → AI0 über -X3:4, -B11 → Kanal 0 über -X3:1, -B12 → Kanal 1 über -X3:2, -B13 (4-Leiter) → Kanal 2 über -X3:3. Kanal 0/1 Strom 2-Draht, Kanal 2 Strom 4-Draht, alle 4–20 mA mit Drahtbruch.' },
  // Modul 5
  w5_von_hand: { story: 'Der Sollwertsteller -R1 liefert den Rohwert 13824. Wie viel Prozent sind das?',
    brief: 'Rechne die fünf Fragen von Hand: normieren (Rohwert / 27648), dann skalieren auf 0–100 %.',
    info: 'Skalieren ist eine Gerade durch zwei Punkte: (0 | 0 %) und (27648 | 100 %). 0–10 V entsprechen den Rohwerten 0–27648.' },
  w5_druck: { story: 'Am HMI steht beim Druck nur „0.0 mbar“. Der Bediener will echte Einheiten sehen.',
    brief: 'Skaliere <b>"Druck_Roh"</b> mit <b>NORM_X</b> und <b>SCALE_X</b> auf <b>"Druck_mbar"</b> (0–100 mbar).',
    info: 'NORM_X: MIN 0, VALUE "Druck_Roh", MAX 27648 → 0.0…1.0. SCALE_X: MIN 0.0, VALUE Ergebnis, MAX 100.0 → mbar. In FUP liegt der Zwischenwert in "Hilf_Norm".' },
  w5_pumpe_aq: { story: 'Der Umrichter der Pumpe erwartet 0–10 V als Sollwert. Diesmal läuft die Skalierung rückwärts.',
    brief: 'Gib <b>"Pumpe_Prozent"</b> (0–100 %) als <b>"Pumpe_Soll_Roh"</b> aus und miss die Spannung am Ausgang bei 50 %.',
    info: 'NORM_X: 0.0…100.0 % → 0…1, SCALE_X: 0…27648 in eine Int-Variable. Messen mit dem Multimeter an der SM 1232 (AQ 0 gegen 0M).' },
  w5_fehler_0_20: { story: 'Der Tank ist leer, das HMI zeigt trotzdem 20 mbar. Das Programm ist dasselbe wie gestern.',
    brief: 'Finde heraus, warum der leere Tank 20 % anzeigt, und korrigiere die Konfiguration von Kanal 0.',
    info: 'Ein 4–20-mA-Transmitter liefert bei 0 mbar <b>4 mA</b> (Live Zero). Ist der Kanal auf 0–20 mA eingestellt, sind 4 mA schon 20 % des Bereichs.' },
  w5_boss_hmi: { story: 'Morgen kommt der Kunde zur Abnahme der Tankstation. ARIA hat das Programm bis auf die Druckanzeige gelöscht.',
    brief: 'Skaliere alle Messwerte in echte Einheiten, lass die Pumpe dem Sollwert folgen und melde Widersprüche zwischen Ultraschall und Druck.',
    info: '"Fuellstand_mm" = 800 − Abstand (60–800 mm), "Pegel_mm" aus "Druck_mbar" (1 mm ≈ 0,0981 mbar), "Temp_C", "Durchfluss_lmin", "Sollwert_Prozent" → "Pumpe_Soll_Roh". Abweichung > 30 mm → "Plausi_Fehler" und "Lampe_Rot".' },
  // Modul 6
  w6_heizung_hysterese: { story: 'Das Wasser soll etwa 60 °C haben. ARIAs Heizung schaltet bei 60,0 °C und klickt im Takt des Rauschens.',
    brief: 'Steuere <b>"Heizung"</b> mit Hysterese: unter 58 °C ein, über 62 °C aus, dazwischen Zustand halten.',
    info: 'Eine <b>Hysterese</b> verhindert ständiges Ein- und Ausschalten: zwei Schwellen statt einer. Zwischen den Schwellen merkt sich die Heizung ihren letzten Zustand.' },
  w6_zweipunkt: { story: 'Der Werkmeister traut keiner Formel, die er nicht selbst geprüft hat. Kalibriert wird mit zwei bekannten Pegeln.',
    brief: 'Lies "Druck_Roh" bei <b>100 mm</b> und <b>500 mm</b> ab und trage beide Punkte in NORM_X/SCALE_X für <b>"Pegel_mm"</b> ein.',
    info: 'NORM_X: MIN und MAX sind die beiden Rohwerte, SCALE_X: MIN 100.0, MAX 500.0 mm. Werte ausserhalb der Punkte rechnet die Gerade weiter.' },
  w6_plausi: { story: 'Ultraschall und Druck messen beide den Füllstand, auf völlig verschiedene Art. ARIA hält schon ein Tuch über -B10.',
    brief: 'Weichen <b>"Fuellstand_mm"</b> und <b>"Pegel_mm"</b> länger als 2 s um mehr als 30 mm ab, melde <b>"Plausi_Fehler"</b>.',
    info: 'Abweichung in beide Richtungen prüfen (ABS). Zeitinstanz "T_Plausi" (TON, 2 s) – Wellen beim Befüllen sind kein Fehler. Meldung auch auf "Lampe_Rot".' },
  w6_fehler_b8: { story: 'Der Messtank ist übergelaufen, obwohl -B8 „Tank voll“ angezeigt hat. Das Programm fragt den Öffner korrekt ab.',
    brief: 'Finde den Verdrahtungsfehler an <b>-X2:13</b> und lege den <b>Öffner</b> von -B8 richtig auf.',
    info: '-B8 hat zwei Ausgänge: BK = Schliesser (1 bei vollem Tank), WH = Öffner (1 bei nicht vollem Tank). Auf -X2:13 ("Tank_Nicht_Voll") gehört der Öffner – drahtbruchsicher.' },
  w6_finale: { story: 'ARIA hat die ganze Werkstatt sabotiert: Verdrahtung, Konfiguration und Programm. Finde alle Fehler.',
    brief: 'Bringe Sortierstrecke und Tankstation wieder in Betrieb: Analogschleifen schliessen, SM 1231 korrigieren, Programm reparieren.',
    info: 'Kanal 0/1: Strom 2-Draht, 4–20 mA. Programm: Band mit Selbsthaltung, "Druck_mbar" 0–100, "Temp_C" 0–100, Heizung 58/62 °C, "Pumpe_Frei" nur bei Vorrat und Tank nicht voll.' }
};
C.tasks.forEach(t => { const x = T[t.id]; if(!x || t.hidden) return; t.story = x.story; t.briefing = x.brief; t.info = x.info || ''; });
root.SW_TEXTE = T;
})(typeof window !== 'undefined' ? window : globalThis);
