/* ===== SPS Quest Portal: Anleitungen für Lernende, Dozenten und Admin (#/anleitung/…) ===== */
(function(){
'use strict';
const P = window.SPSQ, $ = id => document.getElementById(id);
const step = (n, t, body) => '<div class="man-step"><div class="man-n">' + n + '</div><div><h3>' + t + '</h3>' + body + '</div></div>';
const TABS = [
  { id:'lernende', label:'Lernende', icon:'🎮', title:'Anleitung für Lernende', lead:'So spielst du die Quests, meldest dich mit deiner Klasse an und machst bei einer Live-Challenge mit.', html:
    step(1, 'Eine Halle wählen', '<p>Auf der Titelseite stehen fünf Tore: <b>SCL</b> (Roboterzelle), <b>KOP</b> (Seilbahn), <b>FUP</b> (Stellwerk), <b>AWL</b> (Walzwerk) und die <b>Sensorwerkstatt</b> (Prüfstand mit S7-1200: Sensoren montieren, anschliessen, messen, konfigurieren und programmieren). Klick auf ein offenes Tor startet das Spiel direkt im Browser — auch ohne Konto und nach dem ersten Laden auch offline.</p>') +
    step(2, 'Anmelden mit Klassencode', '<p>Deine Lehrperson gibt dir entweder ein <b>fertiges Konto</b> (Benutzername + Startpasswort) oder einen <b>6-stelligen Klassencode</b>.</p><ul><li><b>Konto erhalten:</b> Oben rechts <i>Anmelden</i> → Benutzername und Startpasswort → beim ersten Login ein eigenes Passwort wählen.</li><li><b>Klassencode:</b> <i>Anmelden</i> → <i>[KLASSENCODE]</i> → Code eingeben, ein <b>Pseudonym</b> wählen (kein echter Name!) und ein Passwort festlegen.</li></ul><p>Mit Konto wandert dein Fortschritt mit — auf jedes Gerät. Hast du vorher schon ohne Konto gespielt, fragt das Spiel beim ersten Login, ob dieser Stand übernommen werden soll.</p>') +
    step(3, 'Im Spiel', '<ul><li>Jedes Kapitel: <b>Theorie A</b> → Aufgaben 1–5 → <b>Theorie B</b> → Aufgaben 6–10. Eine Theorie ist bestanden ab 4 von 5 richtigen Antworten.</li><li>Code schreiben (bzw. im KOP/FUP-Editor zeichnen), dann <kbd>Strg</kbd>+<kbd>Enter</kbd> oder <i>In SPS laden &amp; testen</i>. Die Anlage links zeigt, was dein Programm wirklich tut.</li><li>Festgefahren? <i>Hinweis</i> gibt bis zu drei gestufte Tipps (kostet Punkte). Das <i>Handbuch</i> oben rechts erklärt jeden Befehl.</li><li>Nach Kapitel 10 gibt es das Zertifikat <b>Grundstufe</b>, nach Kapitel 15 das Zertifikat mit <b>Profi-Stufe</b>. Dein Name darauf bleibt nur in deinem Browser.</li></ul>') +
    step(4, 'Live-Challenge im Unterricht', '<p>Wenn deine Lehrperson eine Challenge startet, steht am Beamer ein <b>4-stelliger Code</b>. Im Portal <i>Live-Challenge</i> → Code eingeben → das richtige Spiel öffnet sich und wartet auf den Start. Beim <b>Sprint</b> lösen alle dieselbe Aufgabe, bei der <b>Störungsjagd</b> suchst du einen eingebauten Fehler. Schnell sein bringt Punkte, Fehlversuche und Hinweise kosten welche.</p>') +
    step(5, 'Zertifikat mit Prüfung', '<ul><li>Menü <i>Zertifikate</i>: pro Quest gibt es eine Prüfung für die <b>Grundstufe</b> (60 min, 6 Aufgaben + 12 Theoriefragen) und die <b>Profi-Stufe</b> (90 min, 4 Aufgaben + 10 Fragen). Voraussetzung: im Spiel 80 % der Aufgaben der Stufe inkl. Final Boss gelöst; für die Profi-Stufe zuerst die Grundstufe.</li><li>Während der Prüfung sind Handbuch und Glossar erlaubt, Hinweise und Musterlösungen gesperrt. <i>Testen</i> prüft mit Beispiel-Tests, <i>Abgeben</i> bewertet der Server mit verdeckten Tests. Bestanden ab 70 %, ab 90 % mit Auszeichnung. Ein Versuch pro 24 Stunden, höchstens drei in 30 Tagen.</li><li>Bestanden? Namen eingeben, Einwilligung bestätigen, <i>Zertifikat ausstellen</i>. Danach drucken bzw. als PDF oder Bild speichern, Link kopieren oder zu LinkedIn hinzufügen. Jeder kann die Echtheit über den QR-Code bzw. <code>/z/Prüfcode</code> prüfen. Zurückziehen löscht den Namen.</li><li><b>Unter Aufsicht:</b> Deine Lehrperson nennt einen 6-stelligen Code → <i>Zertifikate</i> → <i>Prüfung unter Aufsicht beitreten</i>.</li></ul>') +
    step(6, 'Pikettdienst', '<ul><li>Auf der Titelseite (unter den Toren) oder im Spiel über <i>Pikettdienst</i> übernimmst du eine <b>Schicht als Instandhalter</b>: Die Anlage produziert, Störungen kommen zeitversetzt, jede Minute Stillstand kostet.</li><li>Bei einer Meldung: beobachten, <b>Diagnose</b> stellen (Programm, Hardware mit Bauteil oder Bedienung am HMI), beheben und <b>Wieder anfahren</b>. Eine falsche Diagnose zählt als Fehlversuch.</li><li>Störungen kommen nur aus Kapiteln, die du gespielt hast. <b>Tagschicht</b> für alle, <b>Spätschicht</b> ab Rang Monteur, <b>Nachtschicht</b> ab Servicetechniker.</li><li>Angemeldet prüft der Server deine Behebungen nach; Punkte und Rang gelten im Konto. Der Rang <b>Pikettchef</b> erscheint auf dem Zertifikat der Profi-Stufe. Das Handbuch im Spiel hat eine Seite <i>Fehlersuche im Betrieb</i>.</li></ul>') +
    step(7, 'Konto und Daten', '<ul><li>Unter <i>Konto</i> änderst du dein Passwort oder löschst dein Konto samt Spielständen.</li><li>Deine Lehrperson sieht deinen Fortschritt, deine Punkte und deinen Programmcode — sonst nichts. Es gibt keine E-Mail und keine echten Namen.</li><li>Passwort vergessen? Deine Lehrperson kann es zurücksetzen.</li><li><i>Abmelden</i> lädt deinen Stand hoch und entfernt ihn aus dem Browser — wichtig an gemeinsam genutzten Schulrechnern.</li></ul>') +
    step(8, 'Feedback und Fehler melden', '<p>Unten links ist überall – im Portal und in jeder Quest – der Knopf <b>💬</b>. Damit schickst du jederzeit ein kurzes <b>Feedback</b> oder meldest einen <b>Fehler</b>. Wo du gerade bist (Quest, Aufgabe) und dein Benutzername werden automatisch mitgeschickt; ohne Anmeldung bleibt die Meldung anonym.</p><p>Nach dem Praxistest bittet dich deine Lehrperson zusätzlich um die Umfrage: Titelseite → <i>Feedback geben</i> (etwa 3 Minuten, für die Lehrperson anonym).</p>') },
  { id:'dozenten', label:'Dozenten', icon:'🧑‍🏫', title:'Anleitung für Dozentinnen und Dozenten', lead:'Klassen anlegen, Konten verteilen, Fortschritt verfolgen und Live-Challenges am Beamer durchführen.', html:
    step(1, 'Erster Login', '<p>Du bekommst deinen Benutzernamen und ein <b>Startpasswort</b> vom Admin. Oben rechts <i>Anmelden</i> → einloggen → beim ersten Login ein eigenes Passwort setzen. Danach landest du im <b>Leitstand</b>.</p>') +
    step(2, 'Klasse anlegen', '<p><i>Leitstand</i> → <i>Neue Klasse</i> → Name eingeben (z. B. „EM 3a – Automatik“). Jede Klasse bekommt einen <b>Klassencode</b>.</p>') +
    step(3, 'Lernende aufnehmen — zwei Wege', '<ul><li><b>Konten erzeugen:</b> In der Klasse ein Präfix (z. B. <code>em3a_</code>) und eine Anzahl eingeben → <i>Nummeriert erzeugen</i>, oder <i>Namensliste …</i> mit einem Pseudonym pro Zeile. Die Startpasswörter werden <b>nur einmal</b> angezeigt → <i>Zugangszettel drucken</i> und verteilen.</li><li><b>Selbstanmeldung:</b> Häkchen <i>Selbstanmeldung offen</i> setzen und den Code bzw. den Direktlink an die Tafel schreiben. Lernende wählen ihr Pseudonym selbst. Danach die Selbstanmeldung wieder schliessen oder mit <i>Neuen Code erzeugen</i> den alten Code ungültig machen.</li></ul><p class="muted">Bitte nur Pseudonyme verwenden — keine echten Namen.</p>') +
    step(4, 'Fortschritt verfolgen', '<ul><li>Die Klassenliste zeigt pro Konto Stand, Fortschrittsbalken, Aufgaben, Theorien, Punkte und letzte Aktivität. Oben schaltest du zwischen <b>SCL, KOP, FUP und AWL</b> um.</li><li>Ein Klick auf ein Pseudonym öffnet das Aufgabenraster: Farbe = Sterne, Klick auf eine Zelle zeigt die eingereichte <b>Lösung</b> oder den aktuellen <b>Entwurf</b> (KOP als Leiterbild, FUP als Funktionsplan).</li><li><span class="pill warn">Start-PW</span> heisst: Das Startpasswort wurde noch nicht geändert.</li><li><i>Passwort</i> erzeugt ein neues Startpasswort, <i>✕</i> löscht ein Konto samt Spielständen.</li></ul>') +
    step(5, 'Live-Challenge durchführen', '<ol><li><i>Leitstand</i> → <i>Neue Live-Challenge</i>.</li><li>Modus wählen: <b>Sprint</b> (alle lösen dieselbe Aufgabe), <b>Störungsjagd</b> (eine Anlage mit eingebautem Fehler) oder <b>Pikett-Challenge</b> (alle fahren dieselbe Schicht mit mehreren Störungen bis zum gewählten Kapitel, Rangliste nach Punkten). Quest, Kapitel und Aufgabe bzw. Störung, Dauer und optional die Klasse wählen.</li><li>Die <b>Beamer-Ansicht</b> öffnet sich mit einem 4-stelligen Code. Lernende treten über <i>Live-Challenge</i> im Portal bei; die Aufgabe bleibt bis zum Start verborgen.</li><li><i>Start</i> → Countdown und Live-Rangliste (Pseudonym, Zeit, Versuche, Tipps, Punkte).</li><li>Am Ende Siegerehrung mit Podest. Mit <i>Lösung zeigen</i> besprichst du eine Lösung anonym im Vergleich zur Musterlösung.</li></ol>') +
    step(6, 'Prüfung unter Aufsicht', '<ol><li><i>Leitstand</i> → Karte <i>Prüfungen unter Aufsicht</i>: Quest, Stufe, Klasse, Beginn und Zeitfenster wählen → <i>Prüfung anlegen</i>.</li><li>Die Übersicht zeigt einen <b>6-stelligen Code</b> gross (beamertauglich). Lernende treten im Portal unter <i>Zertifikate</i> bei; die Voraussetzungen aus dem Spiel entfallen, die Wartefristen bleiben.</li><li>Live sichtbar: wer schreibt, abgegebene und bestandene Aufgaben, beantwortete Theoriefragen, <b>Fokusverluste</b> (Wechsel in andere Fenster – nur protokolliert) und Ergebnisse.</li><li><i>Annullieren</i> (Begründung Pflicht) macht eine Prüfung ungültig und widerruft ein bereits ausgestelltes Zertifikat.</li></ol><p>Zertifikate aus Prüfungen unter Aufsicht tragen den Vermerk „unter Aufsicht abgelegt bei …“ mit deinem <b>Anzeigenamen</b> (einstellbar unter <i>Konto</i>) und der Klasse. In der Klassenansicht siehst du alle Zertifikate und Prüfungsversuche deiner Lernenden.</p>') +
    step(7, 'Pikett-Tafel', '<p>In der Klassenansicht zeigt die Karte <b>Pikett-Tafel</b> je Quest Rang, Punkte, Schichten, Nachtschichten, beste Verfügbarkeit, mittlere Reparaturzeit (MTTR) und die letzten Schichten mit <b>Übergabetext</b>. Gezählt werden nur Schichten, die im Portal gefahren und vom Server nachgeprüft wurden (Programmcode gegen die Tests, Diagnosen gegen die Störung).</p>') +
    step(8, 'Feedback auswerten', '<p>Meldungen über den Knopf <b>💬</b> (Feedback und Fehler, mit Quest, Aufgabe und Pseudonym) stehen im Menü <i>Meldungen</i> bzw. im Leitstand unter <i>Feedback und Fehlermeldungen</i>, filterbar nach Typ und Quest.</p><p>Lernende füllen das Formular unter <code>' + P.esc(location.origin) + '/#/feedback</code> aus. Die Auswertung (Mittelwerte, Verteilungen, Texte — ohne Namen) steht unten in der Klassenansicht. Den Ablauf eines Praxistests beschreibt <code>docs/TESTPLAN.md</code>.</p>') +
    step(9, 'Aufräumen', '<p><i>Klasse löschen</i> entfernt die Klasse mit <b>allen Konten und Spielständen</b> endgültig — zum Beispiel am Ende des Semesters.</p>') },
  { id:'admin', label:'Admin', icon:'🛠️', title:'Anleitung für den Admin', lead:'Das Admin-Konto verwaltet die Dozentenkonten. Lernende und Klassen verwalten die Dozenten selbst.', html:
    step(1, 'Admin-Zugang', '<p>Benutzername und Passwort des Admins kommen aus den Worker-Secrets <code>ADMIN_USER</code> und <code>ADMIN_PASSWORD</code> (Cloudflare-Dashboard → Worker <b>scl-quest</b> → Einstellungen → Variablen und Secrets). Beim ersten Login wird das Admin-Konto automatisch angelegt. Geändert wird dieses Passwort nur dort, nicht im Portal.</p><p>Zusätzlich gibt es Admin-Konten mit eigenem Passwort (z. B. aus lokalen Startdaten, siehe <code>dev/seed.js</code>). Sie ändern ihr Passwort unter <i>Konto</i> und können zugleich <b>Dozent</b> sein: Menü <i>Leitstand</i> → eigene Klassen, Konten, Live-Challenge.</p>') +
    step(2, 'Dozenten anlegen', '<p><i>Administration</i> → <i>Neuer Dozent</i> → Benutzername (z. B. Kürzel) → <i>Anlegen</i>. Das <b>Startpasswort</b> wird nur einmal angezeigt; die Dozentin oder der Dozent muss es beim ersten Login ändern.</p>') +
    step(3, 'Meldungen', '<p>Unter <i>Meldungen</i> siehst du alle Feedbacks und Fehlermeldungen aus Portal und Quests (Knopf <b>💬</b>) mit Quest, Aufgabe, Benutzer und Browser. Filter nach Typ und Ort; <i>erledigt</i> abhaken oder löschen.</p>') +
    step(4, 'Zertifikate', '<p>Unter <i>Administration</i> → <i>Zertifikate</i> stehen alle ausgestellten Zertifikate mit Prüfcode. Bei Missbrauch <i>Widerrufen</i> (Begründung Pflicht) – die Prüfseite zeigt dann „widerrufen“. Zertifikate sind in der Testphase gratis; ein Schalter <code>CERT_FEE</code> (Worker-Variable) für späteres Prüfungsguthaben ist vorbereitet, eine Zahlungsanbindung gibt es nicht.</p>') +
    step(5, 'Dozenten verwalten', '<ul><li>Die Kennzahlen oben zeigen Dozenten, Klassen, Lernende und gespeicherte Spielstände.</li><li><i>Passwort</i> erzeugt ein neues Startpasswort (alle Geräte werden abgemeldet).</li><li><i>✕</i> löscht einen Dozenten — <b>mit allen Klassen und Lernendenkonten</b>. Das kann nicht rückgängig gemacht werden.</li></ul>') +
    step(6, 'Sicherheit und Datenschutz', '<ul><li>Passwörter werden nur gehasht gespeichert (PBKDF2). Nach 5 Fehlversuchen pro Konto bzw. 40 pro IP in 15 Minuten wird der Login kurz gesperrt.</li><li>Konten bestehen nur aus Pseudonym und Passwort — keine E-Mail, keine echten Namen.</li><li>Vor dem Betrieb <b>Impressum</b> und <b>Datenschutzerklärung</b> ausfüllen: In <code>dev/portal/impressum.html</code> und <code>datenschutz.html</code> alle <code>[[…]]</code>-Platzhalter ersetzen, neu bauen und rechtlich prüfen lassen.</li></ul>') +
    step(7, 'Betrieb und Updates', '<ul><li>Hosting: Cloudflare Worker <b>scl-quest</b> mit Workers Builds (Gratis-Tarif) und D1-Datenbank <b>spsquest</b>. Die Tabellen legt der Code selbst an.</li><li>Jeder Merge nach <code>main</code> auf GitHub wird automatisch gebaut und veröffentlicht; Nebenzweige erzeugen eine Vorschau-Adresse. Den Build-Status zeigt der GitHub-Check „Workers Builds: scl-quest“.</li><li>Nach einem Update laden Browser die neue Version beim nächsten Besuch (Service Worker); notfalls hilft <kbd>Strg</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd>.</li><li>Den aktuellen Projektstand beschreibt <code>docs/STAND.md</code> im Repository.</li></ul>') }
];
function view(m){
  const tab = TABS.find(t => t.id === (m && m[1])) || TABS[0];
  $('view').innerHTML = '<div class="console man"><div class="crumbs"><a href="#/">HALLEN</a> / ANLEITUNG</div><h1>' + tab.title + '</h1><p class="lead">' + tab.lead + '</p>' +
    '<div class="man-tabs" role="tablist">' + TABS.map(t => '<a role="tab" aria-selected="' + (t === tab) + '" class="man-tab' + (t === tab ? ' active' : '') + '" href="#/anleitung/' + t.id + '"><span aria-hidden="true">' + t.icon + '</span> ' + t.label + '</a>').join('') + '</div>' +
    '<div class="panel man-body">' + tab.html + '</div></div>';
}
P.routes.push({ re: /^#\/anleitung(?:\/(lernende|dozenten|admin))?$/, view });
})();
