defIO({
  Taste_A: 'Taste am Stelltisch: Signal A auf Fahrt stellen',
  Signal_A: 'Einfahrsignal A (TRUE = Fahrt, FALSE = Halt)',
  Gleis1_frei: 'Gleis 1 frei von Fahrzeugen (TRUE = frei)',
  Zug_meldet: 'Einschaltkontakt: ein Zug nähert sich dem Bahnübergang',
  Schranke_zu: 'Schranke des Bahnübergangs (TRUE = geschlossen)',
  Taste_B: 'Taste am Stelltisch: Signal B auf Fahrt stellen',
  Ausfahrt_frei: 'Ausfahrt frei (TRUE = Strecke hinter dem Bahnhof frei)',
  Signal_B: 'Ausfahrsignal B (TRUE = Fahrt, FALSE = Halt)',
  W1_Endlage: 'Weiche 1 in einer Endlage (TRUE = Endlage erreicht)',
  Melder_Gruen: 'Grüne Lampe am Stelltisch (Signal auf Fahrt)',
  Blinklicht: 'Blinklicht des Bahnübergangs (TRUE = blinkt)',
  Schranke_unten: 'Rückmeldung: Schranke unten, Übergang gesperrt',
  Taste_W1: 'Taste am Stelltisch: Weiche 1 stellen bzw. umlegen',
  Weichengleis_frei: 'Gleis über Weiche 1 frei (TRUE = frei)',
  Signal_A_Halt: 'Rückmeldung: Signal A steht auf Halt',
  W1_Freigabe: 'Freigabe zum Umstellen von Weiche 1 (TRUE = erlaubt)',
  Stoerung: 'Störung im Stellwerk (TRUE = Störung steht an)',
  Not_Aus: 'Not-Aus-Taster (TRUE = gedrückt)',
  Melder_Rot: 'Rote Lampe am Stelltisch (Halt bzw. Störung)',
  Gleis1_besetzt: 'Gleis 1 besetzt (TRUE = Fahrzeug im Gleis)',
  W1_links: 'Weiche 1 meldet Endlage links (TRUE = erreicht)',
  W1_rechts: 'Weiche 1 meldet Endlage rechts (TRUE = erreicht)',
  W1_Lage_OK: 'Lagemeldung Weiche 1 gültig (TRUE = in Ordnung)',
  Taste_Stelltisch: 'Umstelltaste für Weiche 1 am Stelltisch',
  Taste_Ort: 'Ortsschalter an der Weiche 1 (Umstellen vor Ort)',
  Zug_links: 'Einschaltkontakt: Zug kommt von links',
  Zug_rechts: 'Einschaltkontakt: Zug kommt von rechts',
  Melder_Gelb: 'Gelbe Warnlampe am Stelltisch',
  Automatik: 'Automatikbetrieb aktiv (TRUE = Automatik)',
  Not_Aus_OK: 'Not-Aus-Kreis in Ordnung (FALSE = Not-Aus ausgelöst)',
  Taste_Rechts: 'Taste am Stelltisch: Weiche 1 nach rechts stellen',
  W1_Endlage_rechts: 'Weiche 1 in Endlage rechts (TRUE = erreicht)',
  W1_nach_rechts: 'Antrieb Weiche 1 läuft nach rechts (TRUE = Motor an)',
  Taste_Halt: 'Haltetaste am Stelltisch (Signal auf Halt)',
  Taste_Wecker: 'Weckertaste am Stelltisch (Wecker einschalten)',
  Taste_Ab: 'Abstelltaste am Stelltisch (Wecker abstellen)',
  Wecker: 'Wecker am Stelltisch (TRUE = klingelt)',
  Taste_Links: 'Taste am Stelltisch: Weiche 1 nach links stellen',
  W1_Endlage_links: 'Weiche 1 in Endlage links (TRUE = erreicht)',
  W1_nach_links: 'Antrieb Weiche 1 läuft nach links (TRUE = Motor an)',
  Zug_faehrt: 'Zug in der Simulation fährt (TRUE = in Fahrt)',
  Zug_angekommen: 'Zug im Zielgleis angekommen (TRUE = angekommen)',
  Zug_weg: 'Zug hat den Bahnübergang verlassen (TRUE = weg)',
  Unten: 'Schranke in unterer Endlage (TRUE = erreicht)',
  Oben: 'Schranke in oberer Endlage (TRUE = erreicht)',
  Senken: 'Schrankenantrieb senkt (TRUE = Motor an)',
  Heben: 'Schrankenantrieb hebt (TRUE = Motor an)',
  Taste_FS: 'Fahrstrassentaste am Stelltisch (Fahrstrasse einstellen)',
  Aufloesung: 'Taste am Stelltisch: Fahrstrasse auflösen',
  FS_eingestellt: 'Fahrstrasse eingestellt (gespeichert, TRUE = aktiv)',
  W1_Fehler: 'Fehlermeldung Weiche 1 (TRUE = Fehler steht an)',
  Quittieren: 'Quittiertaste am Stelltisch',
  Setzen: 'Setzimpuls für den Flipflop-Vergleich',
  Ruecksetzen: 'Rücksetzimpuls für den Flipflop-Vergleich',
  Merker_SR: 'Merker: Ergebnis des SR-Flipflops (Rücksetzen vorrangig)',
  Merker_RS: 'Merker: Ergebnis des RS-Flipflops (Setzen vorrangig)',
  W2_Fehler: 'Fehlermeldung Weiche 2 (TRUE = Fehler steht an)',
  St_W1: 'Gespeicherte Störung Weiche 1 (TRUE = gestört)',
  St_W2: 'Gespeicherte Störung Weiche 2 (TRUE = gestört)',
  Achse: 'Achszähler-Impuls am Zählpunkt (TRUE = Achse über dem Kontakt)',
  Achsen: 'Zählerstand der Achsen (Anzeige)',
  Ausschaltkontakt: 'Ausschaltkontakt hinter dem Bahnübergang (TRUE = belegt)',
  Impuls: 'Hilfsmerker: Impuls einer Tastenbetätigung',
  Zuege_heute: 'Zugzähler für heute (Anzeige)',
  Neuer_Tag: 'Meldung Tageswechsel (TRUE = neuer Tag)'
});
