defIO({
  Zug_meldet: 'Meldung: Zug nähert sich dem Bahnübergang (TRUE)',
  Zug_im_BUE: 'Meldung: Zug befindet sich im Bahnübergang (TRUE)',
  Zug_steht: 'Meldung: Zug steht im Bahnhof auf Gleis 1 (TRUE)',
  Schranke_zu: 'Ausgang Schranke schliessen (TRUE = Schranke unten)',
  Schranke_unten: 'Rückmeldung: Schranke in unterer Endlage (TRUE)',
  Schranke_auf: 'Ausgang Schranke öffnen (TRUE = Schranke geht auf)',
  Glocke: 'Glocke am Bahnübergang (TRUE = läutet)',
  Blinklicht: 'Blinklicht am Bahnübergang (TRUE = leuchtet)',
  Taste_A: 'Stelltaste Signal A (Einfahrt), gedrückt = TRUE',
  Taste_B: 'Stelltaste Signal B (Ausfahrt), gedrückt = TRUE',
  Signal_A: 'Einfahrsignal A (TRUE = Fahrt, FALSE = Halt)',
  Signal_B: 'Ausfahrsignal B (TRUE = Fahrt, FALSE = Halt)',
  Taste_W2: 'Stelltaste Weiche 2 (gedrückt = TRUE)',
  W2_Motor: 'Antriebsmotor Weiche 2 (TRUE = Motor läuft)',
  W1_Fehler: 'Fehlermeldung des Antriebs von Weiche 1 (TRUE)',
  W1_laeuft: 'Weiche 1 läuft gerade um (TRUE = in Bewegung)',
  Quittieren: 'Quittiertaste (gedrückt = TRUE)',
  Stoerung: 'Störungsspeicher (TRUE = Störung liegt an)',
  Weichenstoerung: 'Weichenstörung gespeichert (TRUE = Störung)',
  Wecker: 'Wecker im Stellwerk (TRUE = klingelt)',
  Zug_Nachlauf: 'Merker Nachlauf: Zug im Bahnübergang, plus Nachlaufzeit',
  Takt_1Hz: 'Taktmerker 1 Hz (wechselt alle 0,5 s zwischen 0 und 1)',
  Impuls: 'Hilfsmerker Taktimpuls (kurz TRUE alle 0,5 s)',
  Blink: 'Blinksignal (wechselt bei jedem Taktimpuls)',
  Lampe_links: 'Linke rote Lampe am Andreaskreuz (TRUE = leuchtet)',
  Lampe_rechts: 'Rechte rote Lampe am Andreaskreuz (TRUE = leuchtet)',
  BUE_frei: 'Meldung: Bahnübergang frei von Zügen (TRUE = frei)',
  Laeuten: 'Merker Vorläuten (TRUE = Vorläuten aktiv)',
  Gleis1_besetzt: 'Gleis 1 besetzt (TRUE = Zug auf Gleis 1)',
  Achse: 'Zählpunkt: eine Achse erkannt (Impuls)',
  Grundstellung: 'Taste Grundstellung: setzt den Zähler zurück',
  Zug_komplett: 'Meldung: Zug vollständig eingefahren (TRUE)',
  Anzeige: 'Zählerstandsanzeige am Stelltisch (Zahl)',
  W2_umgestellt: 'Weiche 2 wurde umgestellt (Impuls je Umstellung)',
  Wartung_OK: 'Meldung: Wartung erledigt, Zähler neu laden (TRUE)',
  Wartung_faellig: 'Meldung: Wartung von Weiche 2 fällig (TRUE)',
  Achse_ein: 'Zählpunkt Einfahrt: Achse fährt in den Abschnitt ein',
  Achse_aus: 'Zählpunkt Ausfahrt: Achse fährt aus dem Abschnitt aus',
  Ueberlauf_Ein: 'Zähler Achsen ein: Endwert erreicht (TRUE)',
  Ueberlauf_Aus: 'Zähler Achsen aus: Endwert erreicht (TRUE)',
  Abschnitt_besetzt: 'Gleisabschnitt besetzt (TRUE = Achsen im Abschnitt)',
  Kontrolle_OK: 'Meldung: Kontrolle des Bahnübergangs erledigt (TRUE)',
  Melder_Gelb: 'Gelbe Melderlampe am Stelltisch (TRUE = leuchtet)',
  Melder_Rot: 'Rote Melderlampe am Stelltisch (TRUE = leuchtet)',
  Tempo: 'Zuggeschwindigkeit in km/h (Zahl)',
  Warnung: 'Geschwindigkeitswarnung (TRUE = Warnung aktiv)',
  Zwangsbremsung: 'Zwangsbremsung (TRUE = Zug wird gebremst)',
  Zugnummer: 'Nummer des gemeldeten Zuges (Zahl)',
  W1_abzweig: 'Stellbefehl: Weiche 1 auf abzweigend (TRUE)',
  W1_rechts: 'Rückmeldung: Weiche 1 liegt rechts / abzweigend (TRUE)',
  Fahrt: 'Anforderung: Signal soll Fahrt zeigen (TRUE)',
  Begriff_A: 'Signalbegriff Signal A (Zahl: 0 Halt, 1 Fahrt, 2 Warnung)',
  Achsen: 'Anzahl Achsen des Zuges (Zahl)',
  Laenge_m: 'Zuglänge in Metern (Zahl)',
  Gleis2_passt: 'Zug passt ins Gleis 2 (TRUE = passt)',
  Ist_min: 'Ist-Ankunft in Minuten nach Mitternacht',
  Soll_min: 'Soll-Ankunft in Minuten nach Mitternacht',
  Verspaetung: 'Verspätung in Minuten (Zahl)',
  V_zul: 'Zulässige Geschwindigkeit in km/h (Zahl)',
  V_brems: 'Bremsgrenze in km/h (Zahl)',
  Taste_FS: 'Fahrstrassentaste (gedrückt = TRUE)',
  FS_eingestellt: 'Fahrstrasse eingestellt (gespeichert, TRUE)',
  FS_gesichert: 'Fahrstrasse gesichert (TRUE = Signal darf Fahrt zeigen)',
  Aufloesung: 'Fahrstrasse auflösen (TRUE = Auflösung)',
  W1_Endlage_links: 'Rückmeldung: Weiche 1 in Endlage links / gerade (TRUE)',
  W1_nach_links: 'Stellbefehl: Weiche 1 nach links (TRUE)',
  Gleis1_frei: 'Gleis 1 frei (TRUE = frei)',
  Einfahrt_besetzt: 'Einfahrabschnitt besetzt (TRUE = Zug im Abschnitt)',
  Taste_FS1: 'Taste Fahrstrasse nach Gleis 1 (gedrückt = TRUE)',
  Taste_FS2: 'Taste Fahrstrasse nach Gleis 2 (gedrückt = TRUE)',
  FS1: 'Fahrstrasse nach Gleis 1 eingestellt (TRUE)',
  FS2: 'Fahrstrasse nach Gleis 2 eingestellt (TRUE)',
  W2_gerade: 'Rückmeldung: Weiche 2 liegt gerade (TRUE)',
  W2_nach_gerade: 'Stellbefehl: Weiche 2 nach gerade (TRUE)',
  FS1_gesichert: 'Fahrstrasse nach Gleis 1 gesichert (TRUE)',
  Automatik: 'Automatikbetrieb gewählt (TRUE, nachts)',
});
