defIO({
  Taste_A: 'Fahrtanforderung Signal A (Taste am Stellpult)',
  Gleis1_frei: 'Freimelder Gleis 1',
  W1_Endlage: 'Weiche 1 in Endlage',
  Signal_A: 'Einfahrsignal A, Ausgang Fahrt',
  Taste_B: 'Fahrtanforderung Signal B (Taste am Stellpult)',
  Ausfahrt_frei: 'Freimelder der Ausfahrt',
  W2_Endlage: 'Weiche 2 in Endlage',
  Signal_B: 'Ausfahrsignal B, Ausgang Fahrt',
  Tempo: 'Gemessene Zuggeschwindigkeit in km/h',
  Warnung: 'Warnmelder: Zug zu schnell',
  Einschaltkontakt: 'Einschaltkontakt Bahnübergang (Zug nähert sich)',
  Ausschaltkontakt: 'Ausschaltkontakt Bahnübergang (Zug hat verlassen)',
  Schranke_zu: 'Schranke des Bahnübergangs schliessen / ist zu',
  Achsen: 'Gezählte Achsen des Zuges',
  Laenge_m: 'Berechnete Zuglänge in Metern',
  W1_links: 'Weiche 1 Lagemeldung links',
  W1_rechts: 'Weiche 1 Lagemeldung rechts',
  W1_OK: 'Weiche 1 Lage eindeutig (in Ordnung)',
  Melder_Gelb: 'Gelber Melder am Stelltisch',
  Melder_Rot: 'Roter Melder am Stelltisch',
  Melder_Gruen: 'Grüner Melder am Stelltisch',
  Stoerung: 'Sammelstörung der Anlage',
  Zug_meldet: 'Zugmeldung am Bahnübergang',
  Lagefehler: 'Meldung: Weichenlage nicht eindeutig',
  W1_Taste_L: 'Weiche 1: Taste links stellen',
  W1_Taste_R: 'Weiche 1: Taste rechts stellen',
  W1_End_L: 'Weiche 1: Endlage links erreicht',
  W1_End_R: 'Weiche 1: Endlage rechts erreicht',
  W1_nach_L: 'Weiche 1: Antrieb läuft nach links',
  W1_nach_R: 'Weiche 1: Antrieb läuft nach rechts',
  W1_Fehler: 'Weiche 1: Fehlermeldung',
  Quittieren: 'Quittiertaste am Stelltisch',
  W2_Taste_L: 'Weiche 2: Taste links stellen',
  W2_Taste_R: 'Weiche 2: Taste rechts stellen',
  W2_End_L: 'Weiche 2: Endlage links erreicht',
  W2_End_R: 'Weiche 2: Endlage rechts erreicht',
  W2_nach_L: 'Weiche 2: Antrieb läuft nach links',
  W2_nach_R: 'Weiche 2: Antrieb läuft nach rechts',
  Achse: 'Impuls des Achszählers (Achse erkannt)',
  Grundstellung: 'Taste Grundstellung des Achszählers',
  Achse_ein: 'Achszählpunkt am Abschnittsanfang (Achse fährt ein)',
  Achse_aus: 'Achszählpunkt am Abschnittsende (Achse fährt aus)',
  Gleis1_besetzt: 'Besetztmeldung Gleis 1',
  Ueberlauf: 'Meldung: Achszähler an der Zählgrenze',
  Zug_1: 'Zugmeldung Bahnübergang 1',
  Zug_2: 'Zugmeldung Bahnübergang 2',
  Schranke_1: 'Schranke Bahnübergang 1 schliessen',
  Schranke_2: 'Schranke Bahnübergang 2 schliessen',
  W1_Stoerung: 'Störungsmeldung Weiche 1',
  V_zul: 'Zulässige Geschwindigkeit in km/h',
  W1_Lage_OK: 'Weiche 1: Lage in Ordnung',
  Strecke_frei: 'Meldung: Strecke frei',
  Zug_angekommen: 'Meldung: Zug ist im Gleis angekommen',
  W1_befahrbar: 'Weiche 1 befahrbar',
  W2_befahrbar: 'Weiche 2 befahrbar',
  Fahrweg_OK: 'Fahrweg in Ordnung',
  FS_gesichert: 'Meldung: Fahrstrasse gesichert',
  Blinklicht: 'Blinklicht am Bahnübergang',
  Glocke: 'Warnglocke am Bahnübergang',
  FS_B: 'Fahrstrasse für Signal B gesichert',
  Stoerung_B: 'Störungsmeldung für Signal B',
  Automatik: 'Betriebsartschalter: Automatik ein',
  Taste_FS: 'Taste Fahrstrasse einstellen',
  FS_Anforderung: 'Anforderung einer Fahrstrasse',
  Zug_West: 'Zählpunkt Einfahrt West',
  Zug_Ost: 'Zählpunkt Einfahrt Ost',
  BUE_Stoerung: 'Störungsmeldung Bahnübergang',
  Takt_1Hz: 'Taktgeber 1 Hz für Blinkmeldungen',
  Lampe_Weiche: 'Meldelampe Weichenstörung am Stelltisch',
  Lampe_BUE: 'Meldelampe Bahnübergangsstörung am Stelltisch',
  Signal_Fahrt: 'Fahrtsignal (Ausgang Fahrt)',
  Anzeige: 'Anzeige Zugzähler am Stelltisch',
  Gleis_frei: 'Freimelder des Fahrwegs',
  Weiche_Endlage: 'Weichen des Fahrwegs in Endlage',
  Not_Aus_OK: 'Not-Aus-Kreis in Ordnung',
  Taste_Fahrt: 'Taste Fahrt am Stelltisch',
  Taste_Halt: 'Taste Halt am Stelltisch',
  Sicher_OK: 'Meldung: Sicherung in Ordnung',
  FS_fest: 'Meldung: Fahrstrasse festgelegt',
  Zug_durch: 'Meldung: Zug hat die Fahrstrasse verlassen',
  Anzahl: 'Anzahl der anstehenden Meldungen',
  Sammelstoerung: 'Sammelstörungsmeldung',
  Melder_Ruhe: 'Ruhemelder: Fahrstrasse in Grundstellung',
  Weiche_laeuft: 'Meldung: Weiche wird gestellt',
  Fahrt: 'Ausgang Fahrt der Fahrstrasse',
  Halt: 'Ausgang Halt der Fahrstrasse'
});
