/* PLC-Variablen FUP Quest (Feedback-Auftrag Paket 5.2) – erzeugt mit node gen_tags.js fup, Kommentare von Hand gepflegt.
   Dieselbe Variable hat in allen Aufgaben dieselbe Adresse. Eingänge %I, Ausgänge %Q, Merker %M; Texte/Felder im DB "Daten"; Timer/Zähler als IEC-Instanz. */
(function(root){
root.PLC_TAGS = {
  "Abschnitt_besetzt": { addr: "%I0.0", type: "Bool", comment: "Gleisabschnitt besetzt (Achszähler)" },
  "Achse": { addr: "%I0.1", type: "Bool", comment: "Achse am Zählpunkt (Achszählimpuls)" },
  "Achse_aus": { addr: "%I0.2", type: "Bool", comment: "Achse am Zählpunkt Ausfahrt" },
  "Achse_ein": { addr: "%I0.3", type: "Bool", comment: "Achse am Zählpunkt Einfahrt" },
  "Achsen": { addr: "%QW64", type: "Int", comment: "Anzahl gezählte Achsen" },
  "Anzahl": { addr: "%QW66", type: "Int", comment: "Anzahl aktive Meldungen" },
  "Anzeige": { addr: "%QW68", type: "Int", comment: "Zahlenanzeige am Stelltisch" },
  "Aufloesung": { addr: "%M10.0", type: "Bool", comment: "Fahrstrasse auflösen" },
  "Ausfahrt_frei": { addr: "%I0.4", type: "Bool", comment: "Ausfahrgleis frei (Gleisfreimeldung)" },
  "Ausschaltkontakt": { addr: "%I0.5", type: "Bool", comment: "Ausschaltkontakt hinter dem Bahnübergang" },
  "Automatik": { addr: "%I0.6", type: "Bool", comment: "Betriebsart Automatik" },
  "Begriff_A": { addr: "%QW70", type: "Int", comment: "Signalbegriff Signal A (0/1/2)" },
  "Blink": { addr: "%Q0.0", type: "Bool", comment: "Blinksignal (selbst erzeugter Takt)" },
  "Blinklicht": { addr: "%Q0.1", type: "Bool", comment: "Blinklicht Bahnübergang" },
  "BUE_frei": { addr: "%Q0.2", type: "Bool", comment: "Bahnübergang frei (kein Zug)" },
  "BUE_Stoerung": { addr: "%M10.1", type: "Bool", comment: "Störung Bahnübergang" },
  "Einfahrt_besetzt": { addr: "%I0.7", type: "Bool", comment: "Einfahrgleis besetzt (Gleisfreimeldung)" },
  "Einschaltkontakt": { addr: "%I1.0", type: "Bool", comment: "Einschaltkontakt vor dem Bahnübergang" },
  "Fahrt": { addr: "%Q0.3", type: "Bool", comment: "Fahrt freigegeben" },
  "Fahrweg_OK": { addr: "%Q0.4", type: "Bool", comment: "Fahrweg befahrbar (beide Weichen)" },
  "FS_Anforderung": { addr: "%Q0.5", type: "Bool", comment: "Fahrstrasse angefordert" },
  "FS_B": { addr: "%M10.2", type: "Bool", comment: "Fahrstrasse für Signal B gesichert" },
  "FS_eingestellt": { addr: "%Q0.6", type: "Bool", comment: "Fahrstrasse eingestellt" },
  "FS_fest": { addr: "%Q0.7", type: "Bool", comment: "Fahrstrasse festgelegt" },
  "FS_gesichert": { addr: "%Q1.0", type: "Bool", comment: "Fahrstrasse gesichert" },
  "FS1": { addr: "%Q1.1", type: "Bool", comment: "Fahrstrasse nach Gleis 1 eingestellt" },
  "FS1_gesichert": { addr: "%Q1.2", type: "Bool", comment: "Fahrstrasse nach Gleis 1 gesichert" },
  "FS2": { addr: "%Q1.3", type: "Bool", comment: "Fahrstrasse nach Gleis 2 eingestellt" },
  "Gleis_frei": { addr: "%I1.1", type: "Bool", comment: "Gleis frei (Gleisfreimeldung)" },
  "Gleis1_besetzt": { addr: "%I1.2", type: "Bool", comment: "Gleis 1 besetzt (Gleisfreimeldung)" },
  "Gleis1_frei": { addr: "%I1.3", type: "Bool", comment: "Gleis 1 frei (Gleisfreimeldung)" },
  "Gleis2_passt": { addr: "%Q1.4", type: "Bool", comment: "Zug passt in Gleis 2" },
  "Glocke": { addr: "%Q1.5", type: "Bool", comment: "Glocke Bahnübergang" },
  "Grundstellung": { addr: "%I1.4", type: "Bool", comment: "Taste Grundstellung (Zähler zurücksetzen)" },
  "Halt": { addr: "%Q1.6", type: "Bool", comment: "Signal auf Halt" },
  "Heben": { addr: "%Q1.7", type: "Bool", comment: "Schrankenantrieb heben" },
  "Impuls": { addr: "%M10.3", type: "Bool", comment: "Hilfsmerker Impuls (ein Zyklus)" },
  "Ist_min": { addr: "%IW64", type: "Int", comment: "Ist-Ankunftszeit in Minuten" },
  "Kontrolle_OK": { addr: "%I1.5", type: "Bool", comment: "Taste Kontrolle erledigt" },
  "Laenge_m": { addr: "%QW72", type: "Int", comment: "Zuglänge in Metern" },
  "Laeuten": { addr: "%M10.4", type: "Bool", comment: "Merker Vorläuten aktiv" },
  "Lagefehler": { addr: "%I1.6", type: "Bool", comment: "Weiche ohne gültige Endlage" },
  "Lampe_BUE": { addr: "%Q2.0", type: "Bool", comment: "Störlampe Bahnübergang" },
  "Lampe_links": { addr: "%Q2.1", type: "Bool", comment: "Rote Lampe links am Andreaskreuz" },
  "Lampe_rechts": { addr: "%Q2.2", type: "Bool", comment: "Rote Lampe rechts am Andreaskreuz" },
  "Lampe_Weiche": { addr: "%Q2.3", type: "Bool", comment: "Störlampe Weiche" },
  "Melder_Gelb": { addr: "%Q2.4", type: "Bool", comment: "Gelbe Lampe am Stelltisch" },
  "Melder_Gruen": { addr: "%Q2.5", type: "Bool", comment: "Grüne Lampe am Stelltisch" },
  "Melder_Rot": { addr: "%Q2.6", type: "Bool", comment: "Rote Lampe am Stelltisch" },
  "Melder_Ruhe": { addr: "%Q2.7", type: "Bool", comment: "Lampe Ruhestellung am Stelltisch" },
  "Merker_RS": { addr: "%Q3.0", type: "Bool", comment: "Speicher, Setzen dominant" },
  "Merker_SR": { addr: "%Q3.1", type: "Bool", comment: "Speicher, Rücksetzen dominant" },
  "Neuer_Tag": { addr: "%I1.7", type: "Bool", comment: "Tageswechsel (Zählung neu beginnen)" },
  "Not_Aus": { addr: "%I2.0", type: "Bool", comment: "Not-Aus gedrückt" },
  "Not_Aus_OK": { addr: "%I2.1", type: "Bool", comment: "Not-Aus in Ordnung (nicht gedrückt)" },
  "Oben": { addr: "%I2.2", type: "Bool", comment: "Endschalter Schranke oben" },
  "Quittieren": { addr: "%I2.3", type: "Bool", comment: "Taste Quittieren am Stelltisch" },
  "Ruecksetzen": { addr: "%I2.4", type: "Bool", comment: "Taste Rücksetzen" },
  "Sammelstoerung": { addr: "%Q3.2", type: "Bool", comment: "Lampe Sammelstörung" },
  "Schranke_1": { addr: "%Q3.3", type: "Bool", comment: "Schranke Bahnübergang 1 schliessen" },
  "Schranke_2": { addr: "%Q3.4", type: "Bool", comment: "Schranke Bahnübergang 2 schliessen" },
  "Schranke_auf": { addr: "%Q3.5", type: "Bool", comment: "Schranke öffnen" },
  "Schranke_unten": { addr: "%I2.5", type: "Bool", comment: "Schranke liegt unten (Endlage)" },
  "Schranke_zu": { addr: "%Q3.6", type: "Bool", comment: "Schranke schliessen" },
  "Senken": { addr: "%Q3.7", type: "Bool", comment: "Schrankenantrieb senken" },
  "Setzen": { addr: "%I2.6", type: "Bool", comment: "Taste Setzen" },
  "Sicher_OK": { addr: "%Q4.0", type: "Bool", comment: "Sicherheitskette in Ordnung" },
  "Signal_A": { addr: "%Q4.1", type: "Bool", comment: "Einfahrsignal A auf Fahrt" },
  "Signal_A_Halt": { addr: "%I2.7", type: "Bool", comment: "Einfahrsignal A zeigt Halt" },
  "Signal_B": { addr: "%Q4.2", type: "Bool", comment: "Ausfahrsignal B auf Fahrt" },
  "Signal_Fahrt": { addr: "%Q4.3", type: "Bool", comment: "Hauptsignal auf Fahrt" },
  "Soll_min": { addr: "%IW66", type: "Int", comment: "Soll-Ankunftszeit in Minuten" },
  "St_W1": { addr: "%Q4.4", type: "Bool", comment: "Störung Weiche 1 gespeichert" },
  "St_W2": { addr: "%Q4.5", type: "Bool", comment: "Störung Weiche 2 gespeichert" },
  "Stoerung": { addr: "%Q4.6", type: "Bool", comment: "Störung im Stellwerk" },
  "Stoerung_B": { addr: "%Q4.7", type: "Bool", comment: "Störung Ausfahrsignal B" },
  "Strecke_frei": { addr: "%Q5.0", type: "Bool", comment: "Ganze Strecke frei" },
  "Takt_1Hz": { addr: "%I3.0", type: "Bool", comment: "Taktmerker 1 Hz" },
  "Taste_A": { addr: "%I3.1", type: "Bool", comment: "Taste Signal A am Stelltisch" },
  "Taste_Ab": { addr: "%I3.2", type: "Bool", comment: "Taste Wecker abstellen" },
  "Taste_B": { addr: "%I3.3", type: "Bool", comment: "Taste Signal B am Stelltisch" },
  "Taste_Fahrt": { addr: "%I3.4", type: "Bool", comment: "Taste Fahrt am Stelltisch" },
  "Taste_FS": { addr: "%I3.5", type: "Bool", comment: "Taste Fahrstrasse einstellen" },
  "Taste_FS1": { addr: "%I3.6", type: "Bool", comment: "Taste Fahrstrasse nach Gleis 1" },
  "Taste_FS2": { addr: "%I3.7", type: "Bool", comment: "Taste Fahrstrasse nach Gleis 2" },
  "Taste_Halt": { addr: "%I4.0", type: "Bool", comment: "Taste Halt am Stelltisch" },
  "Taste_Links": { addr: "%I4.1", type: "Bool", comment: "Taste Weiche 1 nach links" },
  "Taste_Ort": { addr: "%I4.2", type: "Bool", comment: "Ortsschalter an der Weiche" },
  "Taste_Rechts": { addr: "%I4.3", type: "Bool", comment: "Taste Weiche 1 nach rechts" },
  "Taste_Stelltisch": { addr: "%I4.4", type: "Bool", comment: "Weichentaste am Stelltisch" },
  "Taste_W1": { addr: "%I4.5", type: "Bool", comment: "Taste Weiche 1 am Stelltisch" },
  "Taste_W2": { addr: "%I4.6", type: "Bool", comment: "Taste Weiche 2 am Stelltisch" },
  "Taste_Wecker": { addr: "%I4.7", type: "Bool", comment: "Wecker auslösen (Meldung)" },
  "Tempo": { addr: "%QW74", type: "Int", comment: "Zuggeschwindigkeit in km/h" },
  "Ueberlauf": { addr: "%M10.5", type: "Bool", comment: "Überlauf Achszähler" },
  "Ueberlauf_Aus": { addr: "%M10.6", type: "Bool", comment: "Überlauf Zähler Ausfahrt" },
  "Ueberlauf_Ein": { addr: "%M10.7", type: "Bool", comment: "Überlauf Zähler Einfahrt" },
  "Unten": { addr: "%I5.0", type: "Bool", comment: "Endschalter Schranke unten" },
  "V_brems": { addr: "%QW76", type: "Int", comment: "Grenze Zwangsbremsung in km/h" },
  "V_zul": { addr: "%QW78", type: "Int", comment: "Zulässige Geschwindigkeit in km/h" },
  "Verspaetung": { addr: "%QW80", type: "Int", comment: "Verspätung in Minuten" },
  "W1_abzweig": { addr: "%Q5.1", type: "Bool", comment: "Weiche 1 auf abzweigend stellen" },
  "W1_befahrbar": { addr: "%Q5.2", type: "Bool", comment: "Weiche 1 befahrbar" },
  "W1_End_L": { addr: "%I5.1", type: "Bool", comment: "Weiche 1 Endlage links" },
  "W1_End_R": { addr: "%I5.2", type: "Bool", comment: "Weiche 1 Endlage rechts" },
  "W1_Endlage": { addr: "%I5.3", type: "Bool", comment: "Weiche 1 in Endlage" },
  "W1_Endlage_links": { addr: "%I5.4", type: "Bool", comment: "Weiche 1 in Endlage links" },
  "W1_Endlage_rechts": { addr: "%I5.5", type: "Bool", comment: "Weiche 1 in Endlage rechts" },
  "W1_Fehler": { addr: "%Q5.3", type: "Bool", comment: "Weiche 1 Fehler (Antrieb klemmt)" },
  "W1_Freigabe": { addr: "%Q5.4", type: "Bool", comment: "Freigabe Weiche 1 umstellen" },
  "W1_laeuft": { addr: "%Q5.5", type: "Bool", comment: "Weiche 1 läuft um" },
  "W1_Lage_OK": { addr: "%Q5.6", type: "Bool", comment: "Weiche 1 Lage gültig" },
  "W1_links": { addr: "%I5.6", type: "Bool", comment: "Weiche 1 liegt links" },
  "W1_nach_L": { addr: "%Q5.7", type: "Bool", comment: "Weichenantrieb 1 nach links" },
  "W1_nach_links": { addr: "%Q6.0", type: "Bool", comment: "Weichenantrieb 1 nach links" },
  "W1_nach_R": { addr: "%Q6.1", type: "Bool", comment: "Weichenantrieb 1 nach rechts" },
  "W1_nach_rechts": { addr: "%Q6.2", type: "Bool", comment: "Weichenantrieb 1 nach rechts" },
  "W1_OK": { addr: "%Q6.3", type: "Bool", comment: "Weiche 1 Lage in Ordnung" },
  "W1_rechts": { addr: "%Q6.4", type: "Bool", comment: "Weiche 1 liegt rechts (abzweigend)" },
  "W1_Stoerung": { addr: "%Q6.5", type: "Bool", comment: "Störung Weiche 1" },
  "W1_Taste_L": { addr: "%I5.7", type: "Bool", comment: "Taste Weiche 1 links" },
  "W1_Taste_R": { addr: "%I6.0", type: "Bool", comment: "Taste Weiche 1 rechts" },
  "W2_befahrbar": { addr: "%Q6.6", type: "Bool", comment: "Weiche 2 befahrbar" },
  "W2_End_L": { addr: "%I6.1", type: "Bool", comment: "Weiche 2 Endlage links" },
  "W2_End_R": { addr: "%I6.2", type: "Bool", comment: "Weiche 2 Endlage rechts" },
  "W2_Endlage": { addr: "%I6.3", type: "Bool", comment: "Weiche 2 in Endlage" },
  "W2_Fehler": { addr: "%Q6.7", type: "Bool", comment: "Weiche 2 Fehler (Antrieb klemmt)" },
  "W2_gerade": { addr: "%I6.4", type: "Bool", comment: "Weiche 2 liegt gerade" },
  "W2_Motor": { addr: "%Q7.0", type: "Bool", comment: "Weichenmotor 2 (Stellimpuls)" },
  "W2_nach_gerade": { addr: "%Q7.1", type: "Bool", comment: "Weiche 2 auf gerade stellen" },
  "W2_nach_L": { addr: "%Q7.2", type: "Bool", comment: "Weichenantrieb 2 nach links" },
  "W2_nach_R": { addr: "%Q7.3", type: "Bool", comment: "Weichenantrieb 2 nach rechts" },
  "W2_Taste_L": { addr: "%I6.5", type: "Bool", comment: "Taste Weiche 2 links" },
  "W2_Taste_R": { addr: "%I6.6", type: "Bool", comment: "Taste Weiche 2 rechts" },
  "W2_umgestellt": { addr: "%Q7.4", type: "Bool", comment: "Weiche 2 umgestellt (Impuls)" },
  "Warnung": { addr: "%Q7.5", type: "Bool", comment: "Warnung Geschwindigkeit zu hoch" },
  "Wartung_faellig": { addr: "%Q7.6", type: "Bool", comment: "Wartung Weiche 2 fällig" },
  "Wartung_OK": { addr: "%I6.7", type: "Bool", comment: "Taste Wartung erledigt" },
  "Wecker": { addr: "%Q7.7", type: "Bool", comment: "Wecker am Stelltisch" },
  "Weiche_Endlage": { addr: "%I7.0", type: "Bool", comment: "Weiche in Endlage" },
  "Weiche_laeuft": { addr: "%Q8.0", type: "Bool", comment: "Weiche läuft um" },
  "Weichengleis_frei": { addr: "%I7.1", type: "Bool", comment: "Weichengleis frei (Gleisfreimeldung)" },
  "Weichenstoerung": { addr: "%Q8.1", type: "Bool", comment: "Weichenstörung (Laufzeit überschritten)" },
  "Zuege_heute": { addr: "%QW82", type: "Int", comment: "Anzahl Züge heute" },
  "Zug_1": { addr: "%I7.2", type: "Bool", comment: "Zug meldet an Bahnübergang 1" },
  "Zug_2": { addr: "%I7.3", type: "Bool", comment: "Zug meldet an Bahnübergang 2" },
  "Zug_angekommen": { addr: "%I7.4", type: "Bool", comment: "Zug im Zielgleis angekommen" },
  "Zug_durch": { addr: "%Q8.2", type: "Bool", comment: "Zug hat Fahrstrasse durchfahren" },
  "Zug_faehrt": { addr: "%Q8.3", type: "Bool", comment: "Zug fährt (Simulation)" },
  "Zug_im_BUE": { addr: "%I7.5", type: "Bool", comment: "Zug im Bahnübergang" },
  "Zug_komplett": { addr: "%Q8.4", type: "Bool", comment: "Zug vollständig eingefahren" },
  "Zug_links": { addr: "%I7.6", type: "Bool", comment: "Einschaltkontakt Bahnübergang links" },
  "Zug_meldet": { addr: "%I7.7", type: "Bool", comment: "Einschaltkontakt meldet Zug" },
  "Zug_Nachlauf": { addr: "%M11.0", type: "Bool", comment: "Merker Nachlaufzeit Schranke" },
  "Zug_Ost": { addr: "%Q8.5", type: "Bool", comment: "Zug fährt von Osten ein" },
  "Zug_rechts": { addr: "%I8.0", type: "Bool", comment: "Einschaltkontakt Bahnübergang rechts" },
  "Zug_steht": { addr: "%I8.1", type: "Bool", comment: "Zug steht am Bahnsteig" },
  "Zug_weg": { addr: "%I8.2", type: "Bool", comment: "Zug hat Bahnübergang verlassen" },
  "Zug_West": { addr: "%Q8.6", type: "Bool", comment: "Zug fährt von Westen ein" },
  "Zugnummer": { addr: "%IW68", type: "Int", comment: "Nummer des gemeldeten Zuges" },
  "Zwangsbremsung": { addr: "%Q8.7", type: "Bool", comment: "Zwangsbremsung auslösen" },
  "Hilf_1": { addr: "%M99.0", type: "Bool", comment: "Hilfsmerker 1 (frei für eigene Zwischenergebnisse)" },
  "Hilf_2": { addr: "%M99.1", type: "Bool", comment: "Hilfsmerker 2 (frei für eigene Zwischenergebnisse)" },
  "Hilf_3": { addr: "%M99.2", type: "Bool", comment: "Hilfsmerker 3 (frei für eigene Zwischenergebnisse)" },
  "Hilf_4": { addr: "%M99.3", type: "Bool", comment: "Hilfsmerker 4 (frei für eigene Zwischenergebnisse)" },
  "Hilfswert_1": { addr: "%MW196", type: "Int", comment: "Hilfswert 1 (frei für eigene Zwischenwerte)" },
  "Hilfswert_2": { addr: "%MW198", type: "Int", comment: "Hilfswert 2 (frei für eigene Zwischenwerte)" }
};
})(typeof window !== 'undefined' ? window : globalThis);
