-- Testklasse SPS2026 — ERZEUGT von dev/seed.js, nicht von Hand ändern.
-- ⚠ Passwort = Vorname (nur Testklasse). steven: Admin-Passwort nach dem ersten Login ändern.
-- Ausführen (optional, der Worker legt die Daten beim ersten Aufruf selbst an):
--   npx wrangler d1 execute spsquest --remote --file=worker/seed.sql
INSERT OR IGNORE INTO users (username, pw, role, created_at, notice_ack, must_change) VALUES ('steven', 'pbkdf2$100000$2yBa5bYmqFjShB1iiCefrg==$kxIFoiFiMufPIl1rOQfMTaMucQiJgu+H+ZGNKoAaF9o=', 'admin', CAST(strftime('%s','now') AS INTEGER) * 1000, 1, 0);
UPDATE users SET pw = 'pbkdf2$100000$acIyqMRijNLoi9QxoC7k4Q==$JVptNOZ0NwnOqMqdZoPVAWGniMSj5l1tDSPAfJ+2Uwk=' WHERE username = 'steven' AND pw = '!secret';
UPDATE users SET role = 'admin', class_id = NULL WHERE username = 'steven';
INSERT OR IGNORE INTO classes (name, teacher_id, code, self_signup, created_at) SELECT 'SPS2026', id, 'SPSQ26', 0, CAST(strftime('%s','now') AS INTEGER) * 1000 FROM users WHERE username = 'steven' AND (SELECT c.id FROM classes c JOIN users u ON u.id = c.teacher_id WHERE c.name = 'SPS2026' AND u.username = 'steven' LIMIT 1) IS NULL;
INSERT OR IGNORE INTO users (username, pw, role, class_id, created_by, created_at, notice_ack, must_change) SELECT 'Noel', 'pbkdf2$100000$CSsSnDs4ZFmBYjz8/cPfIg==$wyZ1I2t5489nmZKNoL9hH3gZWnQkV3KfEzDNaFJQfQ4=', 'student', (SELECT c.id FROM classes c JOIN users u ON u.id = c.teacher_id WHERE c.name = 'SPS2026' AND u.username = 'steven' LIMIT 1), (SELECT id FROM users WHERE username = 'steven'), CAST(strftime('%s','now') AS INTEGER) * 1000, 0, 0 WHERE (SELECT c.id FROM classes c JOIN users u ON u.id = c.teacher_id WHERE c.name = 'SPS2026' AND u.username = 'steven' LIMIT 1) IS NOT NULL;
INSERT OR IGNORE INTO users (username, pw, role, class_id, created_by, created_at, notice_ack, must_change) SELECT 'Eric', 'pbkdf2$100000$DXVIIOp73/wtAbS9LmyRgg==$l9SXN41vk53zWHyS2GpdaZKyUHzPxoNxPAqKOUH25cU=', 'student', (SELECT c.id FROM classes c JOIN users u ON u.id = c.teacher_id WHERE c.name = 'SPS2026' AND u.username = 'steven' LIMIT 1), (SELECT id FROM users WHERE username = 'steven'), CAST(strftime('%s','now') AS INTEGER) * 1000, 0, 0 WHERE (SELECT c.id FROM classes c JOIN users u ON u.id = c.teacher_id WHERE c.name = 'SPS2026' AND u.username = 'steven' LIMIT 1) IS NOT NULL;
INSERT OR IGNORE INTO users (username, pw, role, class_id, created_by, created_at, notice_ack, must_change) SELECT 'Eliah', 'pbkdf2$100000$PJ/goengM+g9I2P5+fLUIQ==$vqq5QmVWrxm17trzKdpzY+o7VBToi6GG1G5Rqa7JqxQ=', 'student', (SELECT c.id FROM classes c JOIN users u ON u.id = c.teacher_id WHERE c.name = 'SPS2026' AND u.username = 'steven' LIMIT 1), (SELECT id FROM users WHERE username = 'steven'), CAST(strftime('%s','now') AS INTEGER) * 1000, 0, 0 WHERE (SELECT c.id FROM classes c JOIN users u ON u.id = c.teacher_id WHERE c.name = 'SPS2026' AND u.username = 'steven' LIMIT 1) IS NOT NULL;
INSERT OR IGNORE INTO users (username, pw, role, class_id, created_by, created_at, notice_ack, must_change) SELECT 'Alicia', 'pbkdf2$100000$zgsqRk6BMI25rIlwNMZE5g==$wdSX4w0ew8VfWmxh0ySmejo3YqQY7+4wMcpwrMvK2d0=', 'student', (SELECT c.id FROM classes c JOIN users u ON u.id = c.teacher_id WHERE c.name = 'SPS2026' AND u.username = 'steven' LIMIT 1), (SELECT id FROM users WHERE username = 'steven'), CAST(strftime('%s','now') AS INTEGER) * 1000, 0, 0 WHERE (SELECT c.id FROM classes c JOIN users u ON u.id = c.teacher_id WHERE c.name = 'SPS2026' AND u.username = 'steven' LIMIT 1) IS NOT NULL;
INSERT OR IGNORE INTO users (username, pw, role, class_id, created_by, created_at, notice_ack, must_change) SELECT 'Finn', 'pbkdf2$100000$vafaIwlMRX5krkvPGNRGfA==$bgVmLfZkkNzWqd6U+9hFeokaaOGIPedt6nzQEvqZU94=', 'student', (SELECT c.id FROM classes c JOIN users u ON u.id = c.teacher_id WHERE c.name = 'SPS2026' AND u.username = 'steven' LIMIT 1), (SELECT id FROM users WHERE username = 'steven'), CAST(strftime('%s','now') AS INTEGER) * 1000, 0, 0 WHERE (SELECT c.id FROM classes c JOIN users u ON u.id = c.teacher_id WHERE c.name = 'SPS2026' AND u.username = 'steven' LIMIT 1) IS NOT NULL;
